In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
BASE_PATH = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource"

TRAIN_PATH = f"{BASE_PATH}/dataset/train"
TEST_PATH = f"{BASE_PATH}/dataset/test"
UTILS_PATH = f"{BASE_PATH}/utils"

print("Base Path :", BASE_PATH)
print("Train Path:", TRAIN_PATH)
print("Test Path :", TEST_PATH)
print("Utils Path:", UTILS_PATH)

Base Path : /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource
Train Path: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/dataset/train
Test Path : /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/dataset/test
Utils Path: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/utils

In [ ]:
import os

print("===== TRAIN FILES =====")
for file in os.listdir(TRAIN_PATH):
    print(file)

print("\n===== TEST FILES =====")
for file in os.listdir(TEST_PATH):
    print(file)

print("\n===== UTILS FILES =====")
for file in os.listdir(UTILS_PATH):
    print(file)

===== TRAIN FILES =====
train_ground_truth.tsv
train_source2.tsv
train_source3.tsv
train_source1.tsv

===== TEST FILES =====
test_source2.tsv
test_source3.tsv
test_source1.tsv

===== UTILS FILES =====
validate_submission.py

In [ ]:
# ============================================
# CELL 4 - DATASET STRUCTURE INSPECTION
# ============================================

import pandas as pd
import os

# Training files
train_files = [
    "train_source1.tsv",
    "train_source2.tsv",
    "train_source3.tsv",
    "train_ground_truth.tsv"
]

# Testing files
test_files = [
    "test_source1.tsv",
    "test_source2.tsv",
    "test_source3.tsv"
]


# Function to inspect TSV file
def inspect_tsv(folder, filename):

    file_path = os.path.join(folder, filename)

    print("\n" + "=" * 70)
    print("FILE:", filename)
    print("=" * 70)

    # Read only first 5 rows
    df = pd.read_csv(
        file_path,
        sep="\t",
        nrows=5
    )

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nFirst 5 Rows:")
    display(df)

    print("\nData Types:")
    print(df.dtypes)

    # File size
    size_mb = os.path.getsize(file_path) / (1024 * 1024)

    print(f"\nFile Size: {size_mb:.2f} MB")


# ============================================
# TRAIN DATA
# ============================================

print("\n\n########## TRAIN DATA ##########")

for file in train_files:
    inspect_tsv(TRAIN_PATH, file)


# ============================================
# TEST DATA
# ============================================

print("\n\n########## TEST DATA ##########")

for file in test_files:
    inspect_tsv(TEST_PATH, file)

########## TRAIN DATA ##########

======================================================================
FILE: train_source1.tsv
======================================================================

Columns:
['entity_id', 'business_name', 'business_address', 'country']

First 5 Rows:

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

Data Types:
entity_id           object
business_name       object
business_address    object
country             object
dtype: object

File Size: 200.34 MB

======================================================================
FILE: train_source2.tsv
======================================================================

Columns:
['entity_id', 'business_name', 'business_address', 'country']

First 5 Rows:

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US

Data Types:
entity_id           object
business_name       object
business_address    object
country             object
dtype: object

File Size: 466.63 MB

======================================================================
FILE: train_source3.tsv
======================================================================

Columns:
['entity_id', 'business_name', 'business_address', 'country']

First 5 Rows:

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India

Data Types:
entity_id           object
business_name       object
business_address    object
country             object
dtype: object

File Size: 480.37 MB

======================================================================
FILE: train_ground_truth.tsv
======================================================================

Columns:
['source1_entity_id', 'matched_entity_ids']

First 5 Rows:

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

Data Types:
source1_entity_id     object
matched_entity_ids    object
dtype: object

File Size: 121.13 MB


########## TEST DATA ##########

======================================================================
FILE: test_source1.tsv
======================================================================

Columns:
['entity_id', 'business_name', 'business_address', 'country']

First 5 Rows:

,entity_id,business_name,business_address,country
0,S1-714132312,Zephay Labs Inc,"2621 Cotten Road, Tyler, TX",US
1,S1-106407869,Vision Partners Corp,"IA, Iowa City, 1064 Newton Rd, Unit 11",US
2,S1-156285671,<< Team Ecole,"175 Boulevard du Président Franklin Roosevelt,...",France
3,S1-689823050,Red Perfect Trading,"Mirzapur, Ews 12, Uttar Pradesh, Mirzapursadar...",India
4,S1-921369899,ZNB Club SARL,"Nouvelle-Aquitaine, La Teste-de-Buch, 5 bis Ru...",France

Data Types:
entity_id           object
business_name       object
business_address    object
country             object
dtype: object

File Size: 166.91 MB

======================================================================
FILE: test_source2.tsv
======================================================================

Columns:
['entity_id', 'business_name', 'business_address', 'country']

First 5 Rows:

,entity_id,business_name,business_address,country
0,S2-192345572,Brahma Infosoft,"COIMATORE COLONY, HUNSUR TQMYSORE DIST., Karna...",India
1,S2-566025912,Marina Ecole France Sarl,"63 R. DE DIEPPE, LILLE, Hauts-de-France",France
2,S2-158121477,SCI Ptit Àmicale,"18 RUE JEN ZAY, Dunkerque, Nord",France
3,S2-89663826,Apex Summit,"67 KENTUCKY ST, SALYERSVILLE, KY",US
4,S2-884102769,Fresh Truist,"8264 FILLY COURT, ROANOKE COUNTY, VA",US

Data Types:
entity_id           object
business_name       object
business_address    object
country             object
dtype: object

File Size: 485.86 MB

======================================================================
FILE: test_source3.tsv
======================================================================

Columns:
['entity_id', 'business_name', 'business_address', 'country']

First 5 Rows:

,entity_id,business_name,business_address,country
0,S3-462677478,मॉडर्न फाइनेंस,"No 10 Enkay Square, 448A, Udyog Vihar Phase V,...",India
1,S3-374810425,Shri Sai Infratech Co,"3/115, East Delhi, DL",India
2,S3-198586129,Fractales Amis Groupe S.A.S,"23 Rue Icmre, La Teste-de-buch, Gironde",France
3,S3-10300249,Shri Supreme Consulting Private (Limited),"H.no 910 A 3503, Mumbai, महाराष्ट्र",India
4,S3-604980231,Prime Realty Ventures Public Limited,"G.t. Karnal Road, Industrial Area, New Delhi, ...",India

Data Types:
entity_id           object
business_name       object
business_address    object
country             object
dtype: object

File Size: 482.56 MB

In [ ]:
# ============================================
# CELL 5 - CHUNK-WISE DATA PROCESSING
# ============================================

import pandas as pd
import os

CHUNK_SIZE = 100_000


def process_file_in_chunks(file_path, chunk_size=CHUNK_SIZE):

    total_rows = 0
    chunk_number = 0

    print("\nProcessing:", os.path.basename(file_path))

    for chunk in pd.read_csv(
        file_path,
        sep="\t",
        chunksize=chunk_size
    ):
        chunk_number += 1
        rows = len(chunk)
        total_rows += rows

        print(
            f"Chunk {chunk_number}: "
            f"{rows:,} rows | "
            f"Total processed: {total_rows:,}"
        )

    print(
        f"Completed: {os.path.basename(file_path)} | "
        f"Total rows: {total_rows:,}"
    )

    return total_rows


# ============================================
# TRAIN DATA
# ============================================

print("========== TRAIN DATA ==========")

train_row_counts = {}

for filename in train_files:

    file_path = os.path.join(TRAIN_PATH, filename)

    train_row_counts[filename] = process_file_in_chunks(
        file_path
    )


# ============================================
# TEST DATA
# ============================================

print("\n========== TEST DATA ==========")

test_row_counts = {}

for filename in test_files:

    file_path = os.path.join(TEST_PATH, filename)

    test_row_counts[filename] = process_file_in_chunks(
        file_path
    )


# ============================================
# SUMMARY
# ============================================

print("\n\n========== ROW COUNT SUMMARY ==========")

print("\nTRAIN FILES:")

for filename, count in train_row_counts.items():
    print(f"{filename}: {count:,} rows")

print("\nTEST FILES:")

for filename, count in test_row_counts.items():
    print(f"{filename}: {count:,} rows")

========== TRAIN DATA ==========

Processing: train_source1.tsv
Chunk 1: 100,000 rows | Total processed: 100,000
Chunk 2: 100,000 rows | Total processed: 200,000
Chunk 3: 100,000 rows | Total processed: 300,000
Chunk 4: 100,000 rows | Total processed: 400,000
Chunk 5: 100,000 rows | Total processed: 500,000
Chunk 6: 100,000 rows | Total processed: 600,000
Chunk 7: 100,000 rows | Total processed: 700,000
Chunk 8: 100,000 rows | Total processed: 800,000
Chunk 9: 100,000 rows | Total processed: 900,000
Chunk 10: 100,000 rows | Total processed: 1,000,000
Chunk 11: 100,000 rows | Total processed: 1,100,000
Chunk 12: 100,000 rows | Total processed: 1,200,000
Chunk 13: 100,000 rows | Total processed: 1,300,000
Chunk 14: 100,000 rows | Total processed: 1,400,000
Chunk 15: 100,000 rows | Total processed: 1,500,000
Chunk 16: 100,000 rows | Total processed: 1,600,000
Chunk 17: 100,000 rows | Total processed: 1,700,000
Chunk 18: 100,000 rows | Total processed: 1,800,000
Chunk 19: 100,000 rows | Total processed: 1,900,000
Chunk 20: 100,000 rows | Total processed: 2,000,000
Chunk 21: 100,000 rows | Total processed: 2,100,000
Chunk 22: 100,000 rows | Total processed: 2,200,000
Chunk 23: 6,821 rows | Total processed: 2,206,821
Completed: train_source1.tsv | Total rows: 2,206,821

Processing: train_source2.tsv
Chunk 1: 100,000 rows | Total processed: 100,000
Chunk 2: 100,000 rows | Total processed: 200,000
Chunk 3: 100,000 rows | Total processed: 300,000
Chunk 4: 100,000 rows | Total processed: 400,000
Chunk 5: 100,000 rows | Total processed: 500,000
Chunk 6: 100,000 rows | Total processed: 600,000
Chunk 7: 100,000 rows | Total processed: 700,000
Chunk 8: 100,000 rows | Total processed: 800,000
Chunk 9: 100,000 rows | Total processed: 900,000
Chunk 10: 100,000 rows | Total processed: 1,000,000
Chunk 11: 100,000 rows | Total processed: 1,100,000
Chunk 12: 100,000 rows | Total processed: 1,200,000
Chunk 13: 100,000 rows | Total processed: 1,300,000
Chunk 14: 100,000 rows | Total processed: 1,400,000
Chunk 15: 100,000 rows | Total processed: 1,500,000
Chunk 16: 100,000 rows | Total processed: 1,600,000
Chunk 17: 100,000 rows | Total processed: 1,700,000
Chunk 18: 100,000 rows | Total processed: 1,800,000
Chunk 19: 100,000 rows | Total processed: 1,900,000
Chunk 20: 100,000 rows | Total processed: 2,000,000
Chunk 21: 100,000 rows | Total processed: 2,100,000
Chunk 22: 100,000 rows | Total processed: 2,200,000
Chunk 23: 100,000 rows | Total processed: 2,300,000
Chunk 24: 100,000 rows | Total processed: 2,400,000
Chunk 25: 100,000 rows | Total processed: 2,500,000
Chunk 26: 100,000 rows | Total processed: 2,600,000
Chunk 27: 100,000 rows | Total processed: 2,700,000
Chunk 28: 100,000 rows | Total processed: 2,800,000
Chunk 29: 100,000 rows | Total processed: 2,900,000
Chunk 30: 100,000 rows | Total processed: 3,000,000
Chunk 31: 100,000 rows | Total processed: 3,100,000
Chunk 32: 100,000 rows | Total processed: 3,200,000
Chunk 33: 100,000 rows | Total processed: 3,300,000
Chunk 34: 100,000 rows | Total processed: 3,400,000
Chunk 35: 100,000 rows | Total processed: 3,500,000
Chunk 36: 100,000 rows | Total processed: 3,600,000
Chunk 37: 100,000 rows | Total processed: 3,700,000
Chunk 38: 100,000 rows | Total processed: 3,800,000
Chunk 39: 100,000 rows | Total processed: 3,900,000
Chunk 40: 100,000 rows | Total processed: 4,000,000
Chunk 41: 100,000 rows | Total processed: 4,100,000
Chunk 42: 100,000 rows | Total processed: 4,200,000
Chunk 43: 100,000 rows | Total processed: 4,300,000
Chunk 44: 100,000 rows | Total processed: 4,400,000
Chunk 45: 100,000 rows | Total processed: 4,500,000
Chunk 46: 100,000 rows | Total processed: 4,600,000
Chunk 47: 100,000 rows | Total processed: 4,700,000
Chunk 48: 100,000 rows | Total processed: 4,800,000
Chunk 49: 100,000 rows | Total processed: 4,900,000
Chunk 50: 100,000 rows | Total processed: 5,000,000
Chunk 51: 34,616 rows | Total processed: 5,034,616
Completed: train_source2.tsv | Total rows: 5,034,616

Processing: train_source3.tsv
Chunk 1: 100,000 rows | Total processed: 100,000
Chunk 2: 100,000 rows | Total processed: 200,000
Chunk 3: 100,000 rows | Total processed: 300,000
Chunk 4: 100,000 rows | Total processed: 400,000
Chunk 5: 100,000 rows | Total processed: 500,000
Chunk 6: 100,000 rows | Total processed: 600,000
Chunk 7: 100,000 rows | Total processed: 700,000
Chunk 8: 100,000 rows | Total processed: 800,000
Chunk 9: 100,000 rows | Total processed: 900,000
Chunk 10: 100,000 rows | Total processed: 1,000,000
Chunk 11: 100,000 rows | Total processed: 1,100,000
Chunk 12: 100,000 rows | Total processed: 1,200,000
Chunk 13: 100,000 rows | Total processed: 1,300,000
Chunk 14: 100,000 rows | Total processed: 1,400,000
Chunk 15: 100,000 rows | Total processed: 1,500,000
Chunk 16: 100,000 rows | Total processed: 1,600,000
Chunk 17: 100,000 rows | Total processed: 1,700,000
Chunk 18: 100,000 rows | Total processed: 1,800,000
Chunk 19: 100,000 rows | Total processed: 1,900,000
Chunk 20: 100,000 rows | Total processed: 2,000,000
Chunk 21: 100,000 rows | Total processed: 2,100,000
Chunk 22: 100,000 rows | Total processed: 2,200,000
Chunk 23: 100,000 rows | Total processed: 2,300,000
Chunk 24: 100,000 rows | Total processed: 2,400,000
Chunk 25: 100,000 rows | Total processed: 2,500,000
Chunk 26: 100,000 rows | Total processed: 2,600,000
Chunk 27: 100,000 rows | Total processed: 2,700,000
Chunk 28: 100,000 rows | Total processed: 2,800,000
Chunk 29: 100,000 rows | Total processed: 2,900,000
Chunk 30: 100,000 rows | Total processed: 3,000,000
Chunk 31: 100,000 rows | Total processed: 3,100,000
Chunk 32: 100,000 rows | Total processed: 3,200,000
Chunk 33: 100,000 rows | Total processed: 3,300,000
Chunk 34: 100,000 rows | Total processed: 3,400,000
Chunk 35: 100,000 rows | Total processed: 3,500,000
Chunk 36: 100,000 rows | Total processed: 3,600,000
Chunk 37: 100,000 rows | Total processed: 3,700,000
Chunk 38: 100,000 rows | Total processed: 3,800,000
Chunk 39: 100,000 rows | Total processed: 3,900,000
Chunk 40: 100,000 rows | Total processed: 4,000,000
Chunk 41: 100,000 rows | Total processed: 4,100,000
Chunk 42: 100,000 rows | Total processed: 4,200,000
Chunk 43: 100,000 rows | Total processed: 4,300,000
Chunk 44: 100,000 rows | Total processed: 4,400,000
Chunk 45: 100,000 rows | Total processed: 4,500,000
Chunk 46: 100,000 rows | Total processed: 4,600,000
Chunk 47: 100,000 rows | Total processed: 4,700,000
Chunk 48: 100,000 rows | Total processed: 4,800,000
Chunk 49: 100,000 rows | Total processed: 4,900,000
Chunk 50: 100,000 rows | Total processed: 5,000,000
Chunk 51: 100,000 rows | Total processed: 5,100,000
Chunk 52: 100,000 rows | Total processed: 5,200,000
Chunk 53: 85,603 rows | Total processed: 5,285,603
Completed: train_source3.tsv | Total rows: 5,285,603

Processing: train_ground_truth.tsv
Chunk 1: 100,000 rows | Total processed: 100,000
Chunk 2: 100,000 rows | Total processed: 200,000
Chunk 3: 100,000 rows | Total processed: 300,000
Chunk 4: 100,000 rows | Total processed: 400,000
Chunk 5: 100,000 rows | Total processed: 500,000
Chunk 6: 100,000 rows | Total processed: 600,000
Chunk 7: 100,000 rows | Total processed: 700,000
Chunk 8: 100,000 rows | Total processed: 800,000
Chunk 9: 100,000 rows | Total processed: 900,000
Chunk 10: 100,000 rows | Total processed: 1,000,000
Chunk 11: 100,000 rows | Total processed: 1,100,000
Chunk 12: 100,000 rows | Total processed: 1,200,000
Chunk 13: 100,000 rows | Total processed: 1,300,000
Chunk 14: 100,000 rows | Total processed: 1,400,000
Chunk 15: 100,000 rows | Total processed: 1,500,000
Chunk 16: 100,000 rows | Total processed: 1,600,000
Chunk 17: 100,000 rows | Total processed: 1,700,000
Chunk 18: 100,000 rows | Total processed: 1,800,000
Chunk 19: 100,000 rows | Total processed: 1,900,000
Chunk 20: 100,000 rows | Total processed: 2,000,000
Chunk 21: 100,000 rows | Total processed: 2,100,000
Chunk 22: 100,000 rows | Total processed: 2,200,000
Chunk 23: 6,821 rows | Total processed: 2,206,821
Completed: train_ground_truth.tsv | Total rows: 2,206,821

========== TEST DATA ==========

Processing: test_source1.tsv
Chunk 1: 100,000 rows | Total processed: 100,000
Chunk 2: 100,000 rows | Total processed: 200,000
Chunk 3: 100,000 rows | Total processed: 300,000
Chunk 4: 100,000 rows | Total processed: 400,000
Chunk 5: 100,000 rows | Total processed: 500,000
Chunk 6: 100,000 rows | Total processed: 600,000
Chunk 7: 100,000 rows | Total processed: 700,000
Chunk 8: 100,000 rows | Total processed: 800,000
Chunk 9: 100,000 rows | Total processed: 900,000
Chunk 10: 100,000 rows | Total processed: 1,000,000
Chunk 11: 100,000 rows | Total processed: 1,100,000
Chunk 12: 100,000 rows | Total processed: 1,200,000
Chunk 13: 100,000 rows | Total processed: 1,300,000
Chunk 14: 100,000 rows | Total processed: 1,400,000
Chunk 15: 100,000 rows | Total processed: 1,500,000
Chunk 16: 100,000 rows | Total processed: 1,600,000
Chunk 17: 100,000 rows | Total processed: 1,700,000
Chunk 18: 32,544 rows | Total processed: 1,732,544
Completed: test_source1.tsv | Total rows: 1,732,544

Processing: test_source2.tsv
Chunk 1: 100,000 rows | Total processed: 100,000
Chunk 2: 100,000 rows | Total processed: 200,000
Chunk 3: 100,000 rows | Total processed: 300,000
Chunk 4: 100,000 rows | Total processed: 400,000
Chunk 5: 100,000 rows | Total processed: 500,000
Chunk 6: 100,000 rows | Total processed: 600,000
Chunk 7: 100,000 rows | Total processed: 700,000
Chunk 8: 100,000 rows | Total processed: 800,000
Chunk 9: 100,000 rows | Total processed: 900,000
Chunk 10: 100,000 rows | Total processed: 1,000,000
Chunk 11: 100,000 rows | Total processed: 1,100,000
Chunk 12: 100,000 rows | Total processed: 1,200,000
Chunk 13: 100,000 rows | Total processed: 1,300,000
Chunk 14: 100,000 rows | Total processed: 1,400,000
Chunk 15: 100,000 rows | Total processed: 1,500,000
Chunk 16: 100,000 rows | Total processed: 1,600,000
Chunk 17: 100,000 rows | Total processed: 1,700,000
Chunk 18: 100,000 rows | Total processed: 1,800,000
Chunk 19: 100,000 rows | Total processed: 1,900,000
Chunk 20: 100,000 rows | Total processed: 2,000,000
Chunk 21: 100,000 rows | Total processed: 2,100,000
Chunk 22: 100,000 rows | Total processed: 2,200,000
Chunk 23: 100,000 rows | Total processed: 2,300,000
Chunk 24: 100,000 rows | Total processed: 2,400,000
Chunk 25: 100,000 rows | Total processed: 2,500,000
Chunk 26: 100,000 rows | Total processed: 2,600,000
Chunk 27: 100,000 rows | Total processed: 2,700,000
Chunk 28: 100,000 rows | Total processed: 2,800,000
Chunk 29: 100,000 rows | Total processed: 2,900,000
Chunk 30: 100,000 rows | Total processed: 3,000,000
Chunk 31: 100,000 rows | Total processed: 3,100,000
Chunk 32: 100,000 rows | Total processed: 3,200,000
Chunk 33: 100,000 rows | Total processed: 3,300,000
Chunk 34: 100,000 rows | Total processed: 3,400,000
Chunk 35: 100,000 rows | Total processed: 3,500,000
Chunk 36: 100,000 rows | Total processed: 3,600,000
Chunk 37: 100,000 rows | Total processed: 3,700,000
Chunk 38: 100,000 rows | Total processed: 3,800,000
Chunk 39: 100,000 rows | Total processed: 3,900,000
Chunk 40: 100,000 rows | Total processed: 4,000,000
Chunk 41: 100,000 rows | Total processed: 4,100,000
Chunk 42: 100,000 rows | Total processed: 4,200,000
Chunk 43: 100,000 rows | Total processed: 4,300,000
Chunk 44: 100,000 rows | Total processed: 4,400,000
Chunk 45: 100,000 rows | Total processed: 4,500,000
Chunk 46: 100,000 rows | Total processed: 4,600,000
Chunk 47: 100,000 rows | Total processed: 4,700,000
Chunk 48: 100,000 rows | Total processed: 4,800,000
Chunk 49: 87,273 rows | Total processed: 4,887,273
Completed: test_source2.tsv | Total rows: 4,887,273

Processing: test_source3.tsv
Chunk 1: 100,000 rows | Total processed: 100,000
Chunk 2: 100,000 rows | Total processed: 200,000
Chunk 3: 100,000 rows | Total processed: 300,000
Chunk 4: 100,000 rows | Total processed: 400,000
Chunk 5: 100,000 rows | Total processed: 500,000
Chunk 6: 100,000 rows | Total processed: 600,000
Chunk 7: 100,000 rows | Total processed: 700,000
Chunk 8: 100,000 rows | Total processed: 800,000
Chunk 9: 100,000 rows | Total processed: 900,000
Chunk 10: 100,000 rows | Total processed: 1,000,000
Chunk 11: 100,000 rows | Total processed: 1,100,000
Chunk 12: 100,000 rows | Total processed: 1,200,000
Chunk 13: 100,000 rows | Total processed: 1,300,000
Chunk 14: 100,000 rows | Total processed: 1,400,000
Chunk 15: 100,000 rows | Total processed: 1,500,000
Chunk 16: 100,000 rows | Total processed: 1,600,000
Chunk 17: 100,000 rows | Total processed: 1,700,000
Chunk 18: 100,000 rows | Total processed: 1,800,000
Chunk 19: 100,000 rows | Total processed: 1,900,000
Chunk 20: 100,000 rows | Total processed: 2,000,000
Chunk 21: 100,000 rows | Total processed: 2,100,000
Chunk 22: 100,000 rows | Total processed: 2,200,000
Chunk 23: 100,000 rows | Total processed: 2,300,000
Chunk 24: 100,000 rows | Total processed: 2,400,000
Chunk 25: 100,000 rows | Total processed: 2,500,000
Chunk 26: 100,000 rows | Total processed: 2,600,000
Chunk 27: 100,000 rows | Total processed: 2,700,000
Chunk 28: 100,000 rows | Total processed: 2,800,000
Chunk 29: 100,000 rows | Total processed: 2,900,000
Chunk 30: 100,000 rows | Total processed: 3,000,000
Chunk 31: 100,000 rows | Total processed: 3,100,000
Chunk 32: 100,000 rows | Total processed: 3,200,000
Chunk 33: 100,000 rows | Total processed: 3,300,000
Chunk 34: 100,000 rows | Total processed: 3,400,000
Chunk 35: 100,000 rows | Total processed: 3,500,000
Chunk 36: 100,000 rows | Total processed: 3,600,000
Chunk 37: 100,000 rows | Total processed: 3,700,000
Chunk 38: 100,000 rows | Total processed: 3,800,000
Chunk 39: 100,000 rows | Total processed: 3,900,000
Chunk 40: 100,000 rows | Total processed: 4,000,000
Chunk 41: 100,000 rows | Total processed: 4,100,000
Chunk 42: 100,000 rows | Total processed: 4,200,000
Chunk 43: 100,000 rows | Total processed: 4,300,000
Chunk 44: 100,000 rows | Total processed: 4,400,000
Chunk 45: 100,000 rows | Total processed: 4,500,000
Chunk 46: 100,000 rows | Total processed: 4,600,000
Chunk 47: 100,000 rows | Total processed: 4,700,000
Chunk 48: 100,000 rows | Total processed: 4,800,000
Chunk 49: 100,000 rows | Total processed: 4,900,000
Chunk 50: 100,000 rows | Total processed: 5,000,000
Chunk 51: 82,316 rows | Total processed: 5,082,316
Completed: test_source3.tsv | Total rows: 5,082,316


========== ROW COUNT SUMMARY ==========

TRAIN FILES:
train_source1.tsv: 2,206,821 rows
train_source2.tsv: 5,034,616 rows
train_source3.tsv: 5,285,603 rows
train_ground_truth.tsv: 2,206,821 rows

TEST FILES:
test_source1.tsv: 1,732,544 rows
test_source2.tsv: 4,887,273 rows
test_source3.tsv: 5,082,316 rows

In [ ]:
# ============================================
# CELL 6 - GROUND TRUTH INSPECTION
# ============================================

import pandas as pd
import os

ground_truth_path = os.path.join(
    TRAIN_PATH,
    "train_ground_truth.tsv"
)

# First 10 rows மட்டும்
ground_truth_sample = pd.read_csv(
    ground_truth_path,
    sep="\t",
    nrows=10
)

print("=" * 70)
print("TRAIN GROUND TRUTH STRUCTURE")
print("=" * 70)

print("\nColumns:")
print(ground_truth_sample.columns.tolist())

print("\nFirst 10 Rows:")
display(ground_truth_sample)

print("\nData Types:")
print(ground_truth_sample.dtypes)

print("\nMissing Values:")
print(ground_truth_sample.isnull().sum())

======================================================================
TRAIN GROUND TRUTH STRUCTURE
======================================================================

Columns:
['source1_entity_id', 'matched_entity_ids']

First 10 Rows:

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5       S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6      S1-318373630                          S2-660036492,S3-804600254
7       S1-86989137                          S3-274817120,S3-312496301
8       S1-29845983                          S2-648035184,S3-588502663
9      S1-789009573              S2-383871912,S3-74481402,S3-576451439

Data Types:
source1_entity_id     object
matched_entity_ids    object
dtype: object

Missing Values:
source1_entity_id     0
matched_entity_ids    0
dtype: int64

In [ ]:
# ============================================
# CELL 7 - DATA QUALITY INSPECTION
# ============================================

import pandas as pd
import os

CHUNK_SIZE = 100_000

source_files = [
    "train_source1.tsv",
    "train_source2.tsv",
    "train_source3.tsv"
]

def inspect_data_quality(folder, filename):

    file_path = os.path.join(folder, filename)

    print("\n" + "=" * 70)
    print("DATA QUALITY:", filename)
    print("=" * 70)

    total_rows = 0
    missing_counts = {}
    empty_counts = {}
    duplicate_rows = 0

    for chunk in pd.read_csv(
        file_path,
        sep="\t",
        chunksize=CHUNK_SIZE,
        dtype=str
    ):
        total_rows += len(chunk)

        # Missing values
        for column in chunk.columns:
            missing_counts[column] = (
                missing_counts.get(column, 0)
                + chunk[column].isna().sum()
            )

            # Empty / whitespace-only values
            empty_counts[column] = (
                empty_counts.get(column, 0)
                + chunk[column].fillna("").str.strip().eq("").sum()
            )

        # Duplicate rows
        duplicate_rows += chunk.duplicated().sum()

    print(f"\nTotal Rows: {total_rows:,}")

    print("\nMissing Values:")
    for column, count in missing_counts.items():
        print(f"{column}: {count:,}")

    print("\nEmpty / Blank Values:")
    for column, count in empty_counts.items():
        print(f"{column}: {count:,}")

    print(f"\nDuplicate Rows: {duplicate_rows:,}")


# ============================================
# RUN INSPECTION
# ============================================

for filename in source_files:
    inspect_data_quality(
        TRAIN_PATH,
        filename
    )

======================================================================
DATA QUALITY: train_source1.tsv
======================================================================

Total Rows: 2,206,821

Missing Values:
entity_id: 0
business_name: 0
business_address: 0
country: 0

Empty / Blank Values:
entity_id: 0
business_name: 0
business_address: 0
country: 0

Duplicate Rows: 0

======================================================================
DATA QUALITY: train_source2.tsv
======================================================================

Total Rows: 5,034,616

Missing Values:
entity_id: 0
business_name: 2
business_address: 168,967
country: 0

Empty / Blank Values:
entity_id: 0
business_name: 2
business_address: 168,967
country: 0

Duplicate Rows: 0

======================================================================
DATA QUALITY: train_source3.tsv
======================================================================

Total Rows: 5,285,603

Missing Values:
entity_id: 0
business_name: 13
business_address: 175,916
country: 0

Empty / Blank Values:
entity_id: 0
business_name: 13
business_address: 175,916
country: 0

Duplicate Rows: 0

In [ ]:
# ============================================
# CELL 8 - CLEANING + TEXT NORMALIZATION
# ============================================

import pandas as pd
import os
import re
import unicodedata

CHUNK_SIZE = 100_000

# Create processed data folder
PROCESSED_PATH = os.path.join(
    BASE_PATH,
    "processed_data"
)

os.makedirs(PROCESSED_PATH, exist_ok=True)


# --------------------------------------------
# TEXT NORMALIZATION FUNCTION
# --------------------------------------------

def normalize_text(value):

    if pd.isna(value):
        return ""

    value = str(value)

    # Unicode normalization
    value = unicodedata.normalize("NFKC", value)

    # Convert to lowercase
    value = value.lower()

    # Remove leading/trailing spaces
    value = value.strip()

    # Replace multiple spaces with one space
    value = re.sub(r"\s+", " ", value)

    return value


# --------------------------------------------
# PROCESS ONE TSV FILE
# --------------------------------------------

def clean_and_normalize_file(input_path, output_path):

    first_chunk = True
    total_rows = 0

    print("\nProcessing:", os.path.basename(input_path))

    for chunk in pd.read_csv(
        input_path,
        sep="\t",
        chunksize=CHUNK_SIZE,
        dtype=str
    ):

        # ------------------------------------
        # Handle missing values
        # ------------------------------------

        for column in [
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ]:

            if column in chunk.columns:
                chunk[column] = chunk[column].fillna("")


        # ------------------------------------
        # Normalize text columns
        # ------------------------------------

        for column in [
            "business_name",
            "business_address",
            "country"
        ]:

            if column in chunk.columns:
                chunk[column] = chunk[column].apply(
                    normalize_text
                )


        # ------------------------------------
        # Remove exact duplicate rows
        # ------------------------------------

        chunk = chunk.drop_duplicates()


        # ------------------------------------
        # Store processed chunk
        # ------------------------------------

        chunk.to_csv(
            output_path,
            sep="\t",
            index=False,
            mode="w" if first_chunk else "a",
            header=first_chunk
        )

        first_chunk = False

        total_rows += len(chunk)

        print(
            f"Processed: {total_rows:,} rows"
        )

        del chunk

    print(
        "Completed:",
        os.path.basename(output_path)
    )


# ============================================
# PROCESS TRAIN SOURCES
# ============================================

source_files = [
    "train_source1.tsv",
    "train_source2.tsv",
    "train_source3.tsv"
]

for filename in source_files:

    input_file = os.path.join(
        TRAIN_PATH,
        filename
    )

    output_file = os.path.join(
        PROCESSED_PATH,
        "cleaned_" + filename
    )

    clean_and_normalize_file(
        input_file,
        output_file
    )


print("\n================================")
print("CLEANING + NORMALIZATION DONE")
print("================================")

Processing: train_source1.tsv
Processed: 100,000 rows
Processed: 200,000 rows
Processed: 300,000 rows
Processed: 400,000 rows
Processed: 500,000 rows
Processed: 600,000 rows
Processed: 700,000 rows
Processed: 800,000 rows
Processed: 900,000 rows
Processed: 1,000,000 rows
Processed: 1,100,000 rows
Processed: 1,200,000 rows
Processed: 1,300,000 rows
Processed: 1,400,000 rows
Processed: 1,500,000 rows
Processed: 1,600,000 rows
Processed: 1,700,000 rows
Processed: 1,800,000 rows
Processed: 1,900,000 rows
Processed: 2,000,000 rows
Processed: 2,100,000 rows
Processed: 2,200,000 rows
Processed: 2,206,821 rows
Completed: cleaned_train_source1.tsv

Processing: train_source2.tsv
Processed: 100,000 rows
Processed: 200,000 rows
Processed: 300,000 rows
Processed: 400,000 rows
Processed: 500,000 rows
Processed: 600,000 rows
Processed: 700,000 rows
Processed: 800,000 rows
Processed: 900,000 rows
Processed: 1,000,000 rows
Processed: 1,100,000 rows
Processed: 1,200,000 rows
Processed: 1,300,000 rows
Processed: 1,400,000 rows
Processed: 1,500,000 rows
Processed: 1,600,000 rows
Processed: 1,700,000 rows
Processed: 1,800,000 rows
Processed: 1,900,000 rows
Processed: 2,000,000 rows
Processed: 2,100,000 rows
Processed: 2,200,000 rows
Processed: 2,300,000 rows
Processed: 2,400,000 rows
Processed: 2,500,000 rows
Processed: 2,600,000 rows
Processed: 2,700,000 rows
Processed: 2,800,000 rows
Processed: 2,900,000 rows
Processed: 3,000,000 rows
Processed: 3,100,000 rows
Processed: 3,200,000 rows
Processed: 3,300,000 rows
Processed: 3,400,000 rows
Processed: 3,500,000 rows
Processed: 3,600,000 rows
Processed: 3,700,000 rows
Processed: 3,800,000 rows
Processed: 3,900,000 rows
Processed: 4,000,000 rows
Processed: 4,100,000 rows
Processed: 4,200,000 rows
Processed: 4,300,000 rows
Processed: 4,400,000 rows
Processed: 4,500,000 rows
Processed: 4,600,000 rows
Processed: 4,700,000 rows
Processed: 4,800,000 rows
Processed: 4,900,000 rows
Processed: 5,000,000 rows
Processed: 5,034,616 rows
Completed: cleaned_train_source2.tsv

Processing: train_source3.tsv
Processed: 100,000 rows
Processed: 200,000 rows
Processed: 300,000 rows
Processed: 400,000 rows
Processed: 500,000 rows
Processed: 600,000 rows
Processed: 700,000 rows
Processed: 800,000 rows
Processed: 900,000 rows
Processed: 1,000,000 rows
Processed: 1,100,000 rows
Processed: 1,200,000 rows
Processed: 1,300,000 rows
Processed: 1,400,000 rows
Processed: 1,500,000 rows
Processed: 1,600,000 rows
Processed: 1,700,000 rows
Processed: 1,800,000 rows
Processed: 1,900,000 rows
Processed: 2,000,000 rows
Processed: 2,100,000 rows
Processed: 2,200,000 rows
Processed: 2,300,000 rows
Processed: 2,400,000 rows
Processed: 2,500,000 rows
Processed: 2,600,000 rows
Processed: 2,700,000 rows
Processed: 2,800,000 rows
Processed: 2,900,000 rows
Processed: 3,000,000 rows
Processed: 3,100,000 rows
Processed: 3,200,000 rows
Processed: 3,300,000 rows
Processed: 3,400,000 rows
Processed: 3,500,000 rows
Processed: 3,600,000 rows
Processed: 3,700,000 rows
Processed: 3,800,000 rows
Processed: 3,900,000 rows
Processed: 4,000,000 rows
Processed: 4,100,000 rows
Processed: 4,200,000 rows
Processed: 4,300,000 rows
Processed: 4,400,000 rows
Processed: 4,500,000 rows
Processed: 4,600,000 rows
Processed: 4,700,000 rows
Processed: 4,800,000 rows
Processed: 4,900,000 rows
Processed: 5,000,000 rows
Processed: 5,100,000 rows
Processed: 5,200,000 rows
Processed: 5,285,603 rows
Completed: cleaned_train_source3.tsv

================================
CLEANING + NORMALIZATION DONE
================================

In [ ]:
# ============================================
# CELL 9 - GROUND TRUTH PAIR ANALYSIS
# ============================================

import pandas as pd
import os

GROUND_TRUTH_PATH = os.path.join(
    TRAIN_PATH,
    "train_ground_truth.tsv"
)

print("Reading ground truth...")

ground_truth = pd.read_csv(
    GROUND_TRUTH_PATH,
    sep="\t",
    dtype=str
)

print("\nColumns:")
print(ground_truth.columns.tolist())

print("\nTotal Source-1 records:")
print(f"{len(ground_truth):,}")

print("\nMissing values:")
print(ground_truth.isna().sum())

# --------------------------------------------
# Convert missing matches to empty string
# --------------------------------------------

ground_truth["matched_entity_ids"] = (
    ground_truth["matched_entity_ids"]
    .fillna("")
    .str.strip()
)

# --------------------------------------------
# Count number of matched entities
# --------------------------------------------

ground_truth["match_count"] = (
    ground_truth["matched_entity_ids"]
    .apply(
        lambda x: 0 if x == "" else len(x.split(","))
    )
)

print("\nMatch Count Statistics:")
print(
    ground_truth["match_count"].describe()
)

print("\nNumber of records with NO match:")
print(
    (ground_truth["match_count"] == 0).sum()
)

print("\nNumber of records with at least ONE match:")
print(
    (ground_truth["match_count"] > 0).sum()
)

print("\nTotal positive matching pairs:")
print(
    ground_truth["match_count"].sum()
)

# --------------------------------------------
# Distribution
# --------------------------------------------

print("\nMatch Count Distribution:")
print(
    ground_truth["match_count"]
    .value_counts()
    .sort_index()
    .head(20)
)

Reading ground truth...

Columns:
['source1_entity_id', 'matched_entity_ids']

Total Source-1 records:
2,206,821

Missing values:
source1_entity_id          0
matched_entity_ids    123247
dtype: int64

Match Count Statistics:
count    2.206821e+06
mean     3.461253e+00
std      1.705323e+00
min      0.000000e+00
25%      2.000000e+00
50%      3.000000e+00
75%      5.000000e+00
max      1.100000e+01
Name: match_count, dtype: float64

Number of records with NO match:
123247

Number of records with at least ONE match:
2083574

Total positive matching pairs:
7638365

Match Count Distribution:
match_count
0     123247
1     119157
2     375212
3     530841
4     484115
5     321957
6     164868
7      63968
8      18680
9       4205
10       534
11        37
Name: count, dtype: int64

In [ ]:
# ============================================
# CELL 10 - BLOCKING KEY ANALYSIS
# ============================================

import pandas as pd
import os
import re

CHUNK_SIZE = 100_000

source_files = [
    "cleaned_train_source1.tsv",
    "cleaned_train_source2.tsv",
    "cleaned_train_source3.tsv"
]


def analyze_blocking_keys(file_path):

    print("\n" + "=" * 70)
    print("BLOCKING ANALYSIS:", os.path.basename(file_path))
    print("=" * 70)

    total_rows = 0

    country_counts = {}
    name_prefix_counts = {}
    name_token_counts = {}

    address_available = 0
    name_available = 0

    for chunk in pd.read_csv(
        file_path,
        sep="\t",
        chunksize=CHUNK_SIZE,
        dtype=str
    ):

        total_rows += len(chunk)

        # ------------------------------------
        # Country analysis
        # ------------------------------------

        countries = (
            chunk["country"]
            .fillna("")
            .str.strip()
        )

        for country, count in countries.value_counts().items():

            if country != "":
                country_counts[country] = (
                    country_counts.get(country, 0) + count
                )

        # ------------------------------------
        # Business name availability
        # ------------------------------------

        names = (
            chunk["business_name"]
            .fillna("")
            .str.strip()
        )

        name_available += (names != "").sum()

        # ------------------------------------
        # Address availability
        # ------------------------------------

        addresses = (
            chunk["business_address"]
            .fillna("")
            .str.strip()
        )

        address_available += (addresses != "").sum()

        # ------------------------------------
        # Name prefix
        # ------------------------------------

        prefixes = (
            names
            .str.replace(r"[^a-z0-9]", "", regex=True)
            .str[:3]
        )

        for prefix, count in prefixes.value_counts().items():

            if prefix != "":
                name_prefix_counts[prefix] = (
                    name_prefix_counts.get(prefix, 0) + count
                )

        # ------------------------------------
        # First token of business name
        # ------------------------------------

        first_tokens = (
            names
            .str.split()
            .str[0]
            .fillna("")
        )

        for token, count in first_tokens.value_counts().items():

            if token != "":
                name_token_counts[token] = (
                    name_token_counts.get(token, 0) + count
                )

    # ========================================
    # RESULTS
    # ========================================

    print(f"\nTotal Rows: {total_rows:,}")

    print(
        f"\nBusiness Name Available: "
        f"{name_available:,} "
        f"({name_available / total_rows * 100:.2f}%)"
    )

    print(
        f"Business Address Available: "
        f"{address_available:,} "
        f"({address_available / total_rows * 100:.2f}%)"
    )

    # ----------------------------------------
    # Country distribution
    # ----------------------------------------

    country_series = (
        pd.Series(country_counts)
        .sort_values(ascending=False)
    )

    print("\nTop 20 Countries:")

    display(
        country_series.head(20).to_frame(
            "count"
        )
    )

    # ----------------------------------------
    # Name prefix distribution
    # ----------------------------------------

    prefix_series = (
        pd.Series(name_prefix_counts)
        .sort_values(ascending=False)
    )

    print("\nTop 20 Name Prefixes:")

    display(
        prefix_series.head(20).to_frame(
            "count"
        )
    )

    # ----------------------------------------
    # First token distribution
    # ----------------------------------------

    token_series = (
        pd.Series(name_token_counts)
        .sort_values(ascending=False)
    )

    print("\nTop 20 Business Name First Tokens:")

    display(
        token_series.head(20).to_frame(
            "count"
        )
    )


# ============================================
# RUN FOR ALL 3 SOURCES
# ============================================

for filename in source_files:

    file_path = os.path.join(
        PROCESSED_PATH,
        filename
    )

    analyze_blocking_keys(file_path)

======================================================================
BLOCKING ANALYSIS: cleaned_train_source1.tsv
======================================================================

Total Rows: 2,206,821

Business Name Available: 2,206,821 (100.00%)
Business Address Available: 2,206,821 (100.00%)

Top 20 Countries:

         count
us     1323633
india   883188

Top 20 Name Prefixes:

     count
int  18717
uni  18155
ind  16929
gre  16294
ped  15261
pre  13391
pri  13327
sup  13102
shi  12878
car  12821
har  12700
gol  12623
mar  12336
bri  12154
all  12053
eas  11889
sou  11717
new  11270
con  11263
sur  11063

Top 20 Business Name First Tokens:

           count
pediatric  15058
new        10161
blue        9137
vision      8463
global      8399
golden      8181
silver      7790
bright      7590
green       7300
shree       7046
first       6893
united      6772
family      6685
great       6616
premier     6530
dynamic     6274
royal       6162
star        6123
apex        6093
smart       6087

======================================================================
BLOCKING ANALYSIS: cleaned_train_source2.tsv
======================================================================

Total Rows: 5,034,616

Business Name Available: 5,034,613 (100.00%)
Business Address Available: 4,865,649 (96.64%)

Top 20 Countries:

         count
us     3016817
india  2017799

Top 20 Name Prefixes:

     count
pri  64743
llc  46339
the  43820
shr  37596
int  33373
ped  31290
inc  30654
cor  28446
sri  27210
car  27206
ind  26045
smt  25536
mar  25449
gre  24246
uni  23927
con  23761
pre  23088
har  22008
bri  21050
all  20238

Top 20 Business Name First Tokens:

           count
the        41035
private    38651
llc        37322
pediatric  28171
dr         25715
shri       25696
m/s        25672
sri        25650
mr         25505
smt        25476
inc        19779
>>         14909
new        14903
***        14747
--         14689
...        14566
limited    14425
blue       12687
family     12302
services   11877

======================================================================
BLOCKING ANALYSIS: cleaned_train_source3.tsv
======================================================================

Total Rows: 5,285,603

Business Name Available: 5,285,590 (100.00%)
Business Address Available: 5,109,687 (96.67%)

Top 20 Countries:

         count
us     3170056
india  2115547

Top 20 Name Prefixes:

     count
pri  75131
the  55097
llc  46776
shr  43119
int  35964
ped  31708
sri  30970
inc  30535
ind  29730
smt  29343
uni  28917
cor  28787
car  27887
gre  27264
bri  27175
mar  25572
con  24849
pre  24773
del  23741
har  23655

Top 20 Business Name First Tokens:

           count
the        51992
private    45419
llc        37944
mr         29442
sri        29353
m/s        29303
smt        29269
dr         29250
shri       29192
pediatric  28626
inc        20259
limited    18285
new        16282
***        15480
...        15331
>>         15257
--         15146
blue       13986
vision     13202
global     12824

In [ ]:
# ============================================
# CELL 11 - MEANINGFUL NAME TOKEN ANALYSIS
# ============================================

import pandas as pd
import os
import re
from collections import Counter

CHUNK_SIZE = 100_000

# Common / generic business-name tokens
GENERIC_TOKENS = {
    "the", "private", "pvt", "llc", "inc", "incorporated",
    "limited", "ltd", "corp", "corporation",
    "company", "co", "services", "group",
    "mr", "mrs", "ms", "smt", "dr",
    "shri", "sri", "m/s", "m",
    "and", "of", "for"
}


def extract_meaningful_tokens(text):

    if pd.isna(text):
        return []

    text = str(text).lower()

    # Keep letters and numbers
    text = re.sub(r"[^a-z0-9\s]", " ", text)

    tokens = text.split()

    # Remove generic tokens and very short tokens
    tokens = [
        token
        for token in tokens
        if token not in GENERIC_TOKENS
        and len(token) >= 3
    ]

    return tokens


def analyze_meaningful_tokens(file_path):

    print("\n" + "=" * 70)
    print("MEANINGFUL TOKEN ANALYSIS:", os.path.basename(file_path))
    print("=" * 70)

    token_counter = Counter()
    total_rows = 0
    rows_with_token = 0

    for chunk in pd.read_csv(
        file_path,
        sep="\t",
        chunksize=CHUNK_SIZE,
        dtype=str
    ):

        names = chunk["business_name"].fillna("")

        for name in names:

            tokens = extract_meaningful_tokens(name)

            if tokens:
                rows_with_token += 1
                token_counter.update(set(tokens))

        total_rows += len(chunk)

    print(f"\nTotal Rows: {total_rows:,}")

    print(
        f"Rows with meaningful token: "
        f"{rows_with_token:,}"
    )

    print("\nTop 30 Meaningful Tokens:")

    token_df = pd.DataFrame(
        token_counter.most_common(30),
        columns=["token", "count"]
    )

    display(token_df)


# ============================================
# RUN FOR ALL 3 SOURCES
# ============================================

for filename in [
    "cleaned_train_source1.tsv",
    "cleaned_train_source2.tsv",
    "cleaned_train_source3.tsv"
]:

    file_path = os.path.join(
        PROCESSED_PATH,
        filename
    )

    analyze_meaningful_tokens(file_path)

======================================================================
MEANINGFUL TOKEN ANALYSIS: cleaned_train_source1.tsv
======================================================================

Total Rows: 2,206,821
Rows with meaningful token: 2,204,146

Top 30 Meaningful Tokens:

            token  count
0           india  59420
1            care  52891
2      associates  42804
3             llp  39726
4          center  35261
5        partners  34952
6          health  28264
7          clinic  27489
8       solutions  26337
9          global  25481
10        trading  22801
11  international  20751
12       brothers  20710
13   technologies  20581
14           pllc  20531
15     industries  18778
16    enterprises  17895
17       medicine  17769
18     foundation  17748
19       ventures  17189
20    consultants  15889
21      pediatric  15611
22     technology  14332
23          trust  14046
24     management  14031
25        systems  13779
26           tech  13669
27         dental  13410
28           blue  13314
29       products  13297

======================================================================
MEANINGFUL TOKEN ANALYSIS: cleaned_train_source2.tsv
======================================================================

Total Rows: 5,034,616
Rows with meaningful token: 4,564,415

Top 30 Meaningful Tokens:

            token   count
0             com  201471
1          center  193696
2        partners  152694
3           india  110685
4        holdings   97021
5            care   88790
6      associates   73222
7             llp   64608
8         service   55261
9          health   51338
10    enterprises   49341
11     industries   47928
12         clinic   46246
13       ventures   44341
14      solutions   41019
15         public   37009
16         global   35242
17       brothers   35234
18        trading   35100
19      pediatric   32974
20       medicine   31536
21   technologies   30232
22        exports   29693
23         dental   26003
24  international   25578
25          trust   24748
26     foundation   24592
27         family   24251
28         valley   23987
29       highland   23867

======================================================================
MEANINGFUL TOKEN ANALYSIS: cleaned_train_source3.tsv
======================================================================

Total Rows: 5,285,603
Rows with meaningful token: 5,016,018

Top 30 Meaningful Tokens:

            token   count
0          center  220809
1             com  211134
2        partners  161956
3           india  112963
4        holdings   99024
5            care   95828
6             llp   77190
7      associates   76680
8         service   63953
9     enterprises   56859
10         health   53452
11     industries   53419
12        trading   51791
13       ventures   49368
14         clinic   48100
15      solutions   46375
16         global   42268
17         public   37687
18       brothers   36259
19   technologies   35660
20      pediatric   35021
21        exports   33711
22       medicine   33121
23  international   32004
24            dba   31629
25       formerly   30057
26     foundation   28906
27         dental   27422
28           pllc   26549
29       business   25680

In [ ]:
# ============================================
# CELL 12 - BUILD BLOCKING INDEX
# ============================================

import pandas as pd
import os
import re
from collections import Counter

CHUNK_SIZE = 100_000

# --------------------------------------------
# Blocking configuration
# --------------------------------------------

MIN_TOKEN_LENGTH = 4

# Very common / generic tokens
GENERIC_TOKENS = {
    "the", "private", "pvt", "llc", "inc",
    "incorporated", "limited", "ltd",
    "corp", "corporation", "company", "co",
    "services", "service", "group",
    "mr", "mrs", "ms", "smt", "dr",
    "shri", "sri", "m/s", "and", "of", "for"
}


# --------------------------------------------
# Extract tokens
# --------------------------------------------

def get_tokens(text):

    if pd.isna(text):
        return []

    text = str(text).lower()

    text = re.sub(
        r"[^a-z0-9\s]",
        " ",
        text
    )

    tokens = text.split()

    tokens = [
        token
        for token in tokens
        if len(token) >= MIN_TOKEN_LENGTH
        and token not in GENERIC_TOKENS
    ]

    return list(set(tokens))


# ============================================
# STEP 1
# Count token frequency in Source 2 + Source 3
# ============================================

print("=" * 70)
print("STEP 1 - TOKEN FREQUENCY")
print("=" * 70)

token_frequency = Counter()

source_files = [
    "cleaned_train_source2.tsv",
    "cleaned_train_source3.tsv"
]

for filename in source_files:

    file_path = os.path.join(
        PROCESSED_PATH,
        filename
    )

    print("\nScanning:", filename)

    for chunk in pd.read_csv(
        file_path,
        sep="\t",
        chunksize=CHUNK_SIZE,
        dtype=str
    ):

        names = chunk["business_name"].fillna("")

        for name in names:

            tokens = get_tokens(name)

            token_frequency.update(tokens)

        del chunk

print("\nTotal unique tokens:")
print(f"{len(token_frequency):,}")


# ============================================
# STEP 2
# Keep only reasonably selective tokens
# ============================================

MAX_TOKEN_FREQUENCY = 50_000

useful_tokens = {
    token
    for token, count in token_frequency.items()
    if count <= MAX_TOKEN_FREQUENCY
}

print("\nUseful blocking tokens:")
print(f"{len(useful_tokens):,}")

print(
    f"\nRemoved frequent tokens: "
    f"{len(token_frequency) - len(useful_tokens):,}"
)


# ============================================
# STEP 3
# Save useful tokens
# ============================================

BLOCKING_PATH = os.path.join(
    BASE_PATH,
    "blocking"
)

os.makedirs(
    BLOCKING_PATH,
    exist_ok=True
)

useful_tokens_file = os.path.join(
    BLOCKING_PATH,
    "useful_tokens.txt"
)

with open(
    useful_tokens_file,
    "w",
    encoding="utf-8"
) as f:

    for token in sorted(useful_tokens):
        f.write(token + "\n")


print(
    "\nUseful token list saved to:"
)
print(useful_tokens_file)

======================================================================
STEP 1 - TOKEN FREQUENCY
======================================================================

Scanning: cleaned_train_source2.tsv

Scanning: cleaned_train_source3.tsv

Total unique tokens:
1,410,918

Useful blocking tokens:
1,410,894

Removed frequent tokens: 24

Useful token list saved to:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/useful_tokens.txt

In [ ]:
# ============================================
# CELL 13 - BUILD COUNTRY + TOKEN INDEX
# ============================================

import pandas as pd
import os
import re

CHUNK_SIZE = 100_000

# Load useful tokens
with open(
    useful_tokens_file,
    "r",
    encoding="utf-8"
) as f:
    useful_tokens = set(
        line.strip()
        for line in f
        if line.strip()
    )

print(
    f"Loaded useful tokens: "
    f"{len(useful_tokens):,}"
)


def get_tokens(text):

    if pd.isna(text):
        return []

    text = str(text).lower()

    text = re.sub(
        r"[^a-z0-9\s]",
        " ",
        text
    )

    tokens = text.split()

    tokens = [
        token
        for token in set(tokens)
        if len(token) >= 4
        and token in useful_tokens
    ]

    return tokens


# --------------------------------------------
# Output directory
# --------------------------------------------

INDEX_PATH = os.path.join(
    BLOCKING_PATH,
    "source_index"
)

os.makedirs(
    INDEX_PATH,
    exist_ok=True
)


# --------------------------------------------
# Process Source 2 and Source 3
# --------------------------------------------

for filename in [
    "cleaned_train_source2.tsv",
    "cleaned_train_source3.tsv"
]:

    input_path = os.path.join(
        PROCESSED_PATH,
        filename
    )

    source_name = (
        "source2"
        if "source2" in filename
        else "source3"
    )

    output_path = os.path.join(
        INDEX_PATH,
        f"{source_name}_blocking_index.tsv"
    )

    print("\n" + "=" * 70)
    print("BUILDING INDEX:", source_name)
    print("=" * 70)

    first_write = True
    total_index_rows = 0

    for chunk in pd.read_csv(
        input_path,
        sep="\t",
        chunksize=CHUNK_SIZE,
        dtype=str
    ):

        records = []

        for _, row in chunk.iterrows():

            country = str(
                row["country"]
            ).strip()

            entity_id = str(
                row["entity_id"]
            ).strip()

            tokens = get_tokens(
                row["business_name"]
            )

            for token in tokens:

                records.append({
                    "block_key": f"{country}|{token}",
                    "entity_id": entity_id
                })

        if records:

            index_chunk = pd.DataFrame(records)

            index_chunk = (
                index_chunk
                .drop_duplicates()
            )

            index_chunk.to_csv(
                output_path,
                sep="\t",
                index=False,
                mode="w" if first_write else "a",
                header=first_write
            )

            first_write = False

            total_index_rows += len(
                index_chunk
            )

        del chunk

    print(
        f"Index rows created: "
        f"{total_index_rows:,}"
    )

    print(
        "Saved:",
        output_path
    )

print("\n========================================")
print("BLOCKING INDEX BUILD COMPLETE")
print("========================================")

Loaded useful tokens: 1,410,894

======================================================================
BUILDING INDEX: source2
======================================================================
Index rows created: 9,053,371
Saved: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/source_index/source2_blocking_index.tsv

======================================================================
BUILDING INDEX: source3
======================================================================
Index rows created: 10,040,023
Saved: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/source_index/source3_blocking_index.tsv

========================================
BLOCKING INDEX BUILD COMPLETE
========================================

In [ ]:
# ============================================
# CELL 13.5 - FIND PROJECT FILES
# ============================================

import os

BASE_PATH = (
    "/content/drive/MyDrive/"
    "6ab10eb3b23ba_student_resource/"
    "student_resource"
)

print("=" * 70)
print("SEARCHING PROJECT FILES")
print("=" * 70)

for root, dirs, files in os.walk(BASE_PATH):

    for file in files:

        if (
            file.startswith("cleaned_train")
            and file.endswith(".tsv")
        ):
            print(
                os.path.join(root, file)
            )

======================================================================
SEARCHING PROJECT FILES
======================================================================
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/processed_data/cleaned_train_source1.tsv
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/processed_data/cleaned_train_source2.tsv
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/processed_data/cleaned_train_source3.tsv

In [ ]:
# ============================================
# CELL 14 - RAM-SAFE CANDIDATE TEST
# ============================================

import pandas as pd
import os
import re

BASE_PATH = (
    "/content/drive/MyDrive/"
    "6ab10eb3b23ba_student_resource/"
    "student_resource"
)

PROCESSED_PATH = os.path.join(
    BASE_PATH,
    "processed_data"
)

BLOCKING_PATH = os.path.join(
    BASE_PATH,
    "blocking"
)

SOURCE1_PATH = os.path.join(
    PROCESSED_PATH,
    "cleaned_train_source1.tsv"
)

SOURCE2_INDEX_PATH = os.path.join(
    BLOCKING_PATH,
    "source_index",
    "source2_blocking_index.tsv"
)

SOURCE3_INDEX_PATH = os.path.join(
    BLOCKING_PATH,
    "source_index",
    "source3_blocking_index.tsv"
)

USEFUL_TOKENS_PATH = os.path.join(
    BLOCKING_PATH,
    "useful_tokens.txt"
)

SAMPLE_ROWS = 100_000
INDEX_CHUNK_SIZE = 100_000


# ============================================
# Check files
# ============================================

print("=" * 70)
print("FILE CHECK")
print("=" * 70)

files_to_check = {
    "Source 1": SOURCE1_PATH,
    "Source 2 index": SOURCE2_INDEX_PATH,
    "Source 3 index": SOURCE3_INDEX_PATH,
    "Useful tokens": USEFUL_TOKENS_PATH
}

for name, path in files_to_check.items():

    print(f"\n{name}:")
    print(path)

    if os.path.exists(path):
        print("STATUS: OK")
    else:
        print("STATUS: NOT FOUND")
        raise FileNotFoundError(path)


# ============================================
# Load useful tokens
# ============================================

with open(
    USEFUL_TOKENS_PATH,
    "r",
    encoding="utf-8"
) as f:

    useful_tokens = set(
        line.strip()
        for line in f
        if line.strip()
    )

print(
    f"\nUseful tokens loaded: "
    f"{len(useful_tokens):,}"
)


# ============================================
# Token function
# ============================================

def get_tokens(text):

    if pd.isna(text):
        return []

    text = str(text).lower()

    text = re.sub(
        r"[^a-z0-9\s]",
        " ",
        text
    )

    tokens = text.split()

    return list(set(
        token
        for token in tokens
        if len(token) >= 4
        and token in useful_tokens
    ))


# ============================================
# Load ONLY 100K Source-1 rows
# ============================================

print("\n" + "=" * 70)
print("LOADING SOURCE-1 SAMPLE")
print("=" * 70)

source1_sample = pd.read_csv(
    SOURCE1_PATH,
    sep="\t",
    nrows=SAMPLE_ROWS,
    dtype=str
)

print(
    f"Source-1 sample rows: "
    f"{len(source1_sample):,}"
)


# ============================================
# Create blocking keys
# ============================================

print("\nCreating blocking keys...")

required_keys = set()

for row in source1_sample.itertuples(
    index=False
):

    country = str(
        row.country
    ).strip().lower()

    tokens = get_tokens(
        row.business_name
    )

    for token in tokens:

        required_keys.add(
            f"{country}|{token}"
        )

print(
    f"Unique blocking keys required: "
    f"{len(required_keys):,}"
)


# ============================================
# Candidate output folder
# ============================================

CANDIDATE_DIR = os.path.join(
    BLOCKING_PATH,
    "candidates"
)

os.makedirs(
    CANDIDATE_DIR,
    exist_ok=True
)

CANDIDATE_PATH = os.path.join(
    CANDIDATE_DIR,
    "candidate_test_100k.tsv"
)

if os.path.exists(CANDIDATE_PATH):
    os.remove(CANDIDATE_PATH)


# ============================================
# Scan index chunk-by-chunk
# ============================================

def scan_index(
    index_path,
    source_name
):

    total_rows = 0
    matched_rows = 0
    first_write = True

    print("\n" + "=" * 70)
    print(
        f"SCANNING {source_name.upper()} INDEX"
    )
    print("=" * 70)

    for chunk in pd.read_csv(
        index_path,
        sep="\t",
        chunksize=INDEX_CHUNK_SIZE,
        dtype=str
    ):

        total_rows += len(chunk)

        matched = chunk[
            chunk["block_key"].isin(
                required_keys
            )
        ]

        if not matched.empty:

            matched = matched.copy()

            matched["candidate_source"] = (
                source_name
            )

            matched.to_csv(
                CANDIDATE_PATH,
                sep="\t",
                index=False,
                mode="w" if first_write else "a",
                header=first_write
            )

            first_write = False

            matched_rows += len(matched)

        del matched
        del chunk

        if total_rows % 1_000_000 == 0:

            print(
                f"Scanned: "
                f"{total_rows:,} | "
                f"Matched: "
                f"{matched_rows:,}"
            )

    print(
        f"{source_name} completed."
    )

    print(
        f"Total scanned: "
        f"{total_rows:,}"
    )

    print(
        f"Total matched: "
        f"{matched_rows:,}"
    )

    return matched_rows


# ============================================
# Source 2
# ============================================

source2_matches = scan_index(
    SOURCE2_INDEX_PATH,
    "source2"
)


# ============================================
# Source 3
# ============================================

source3_matches = scan_index(
    SOURCE3_INDEX_PATH,
    "source3"
)


# ============================================
# Final result
# ============================================

total_candidates = (
    source2_matches +
    source3_matches
)

print("\n" + "=" * 70)
print("CANDIDATE TEST COMPLETE")
print("=" * 70)

print(
    f"\nSource-1 records tested: "
    f"{len(source1_sample):,}"
)

print(
    f"Source-2 candidates: "
    f"{source2_matches:,}"
)

print(
    f"Source-3 candidates: "
    f"{source3_matches:,}"
)

print(
    f"Total candidate rows: "
    f"{total_candidates:,}"
)

print(
    f"Average candidates per Source-1: "
    f"{total_candidates / len(source1_sample):.2f}"
)

print("\nCandidate file:")
print(CANDIDATE_PATH)

======================================================================
FILE CHECK
======================================================================

Source 1:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/processed_data/cleaned_train_source1.tsv
STATUS: OK

Source 2 index:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/source_index/source2_blocking_index.tsv
STATUS: OK

Source 3 index:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/source_index/source3_blocking_index.tsv
STATUS: OK

Useful tokens:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/useful_tokens.txt
STATUS: OK

Useful tokens loaded: 1,410,894

======================================================================
LOADING SOURCE-1 SAMPLE
======================================================================
Source-1 sample rows: 100,000

Creating blocking keys...
Unique blocking keys required: 29,700

======================================================================
SCANNING SOURCE2 INDEX
======================================================================
Scanned: 1,000,000 | Matched: 791,379
Scanned: 2,000,000 | Matched: 1,583,895
Scanned: 3,000,000 | Matched: 2,375,891
Scanned: 4,000,000 | Matched: 3,168,708
Scanned: 5,000,000 | Matched: 3,961,341
Scanned: 6,000,000 | Matched: 4,753,812
Scanned: 7,000,000 | Matched: 5,546,020
Scanned: 8,000,000 | Matched: 6,337,380
Scanned: 9,000,000 | Matched: 7,130,427
source2 completed.
Total scanned: 9,053,371
Total matched: 7,172,744

======================================================================
SCANNING SOURCE3 INDEX
======================================================================
Scanned: 1,000,000 | Matched: 780,497
Scanned: 2,000,000 | Matched: 1,560,291
Scanned: 3,000,000 | Matched: 2,341,109
Scanned: 4,000,000 | Matched: 3,121,660
Scanned: 5,000,000 | Matched: 3,902,097
Scanned: 6,000,000 | Matched: 4,682,414
Scanned: 7,000,000 | Matched: 5,462,829
Scanned: 8,000,000 | Matched: 6,243,807
Scanned: 9,000,000 | Matched: 7,023,995
Scanned: 10,000,000 | Matched: 7,804,549
source3 completed.
Total scanned: 10,040,023
Total matched: 7,835,867

======================================================================
CANDIDATE TEST COMPLETE
======================================================================

Source-1 records tested: 100,000
Source-2 candidates: 7,172,744
Source-3 candidates: 7,835,867
Total candidate rows: 15,008,611
Average candidates per Source-1: 150.09

Candidate file:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/candidate_test_100k.tsv

In [ ]:
# ============================================
# CELL 15 - VERIFY CANDIDATE / INDEX STRUCTURE
# ============================================

import pandas as pd

print("=" * 70)
print("CHECKING CANDIDATE STRUCTURE")
print("=" * 70)

# --------------------------------------------
# Candidate file
# --------------------------------------------

print("\nCandidate file sample:")

candidate_sample = pd.read_csv(
    CANDIDATE_PATH,
    sep="\t",
    nrows=10,
    dtype=str
)

print("\nCandidate columns:")
print(candidate_sample.columns.tolist())

display(candidate_sample)


# --------------------------------------------
# Source-2 index sample
# --------------------------------------------

print("\n" + "=" * 70)
print("SOURCE-2 INDEX SAMPLE")
print("=" * 70)

source2_index_sample = pd.read_csv(
    SOURCE2_INDEX_PATH,
    sep="\t",
    nrows=10,
    dtype=str
)

print("\nSource-2 index columns:")
print(source2_index_sample.columns.tolist())

display(source2_index_sample)


# --------------------------------------------
# Source-3 index sample
# --------------------------------------------

print("\n" + "=" * 70)
print("SOURCE-3 INDEX SAMPLE")
print("=" * 70)

source3_index_sample = pd.read_csv(
    SOURCE3_INDEX_PATH,
    sep="\t",
    nrows=10,
    dtype=str
)

print("\nSource-3 index columns:")
print(source3_index_sample.columns.tolist())

display(source3_index_sample)

======================================================================
CHECKING CANDIDATE STRUCTURE
======================================================================

Candidate file sample:

Candidate columns:
['block_key', 'entity_id', 'candidate_source']

           block_key     entity_id candidate_source
0  india|consultants  S3-859268022          source3
1        india|south  S3-859268022          source3
2          us|coffee  S3-671162755          source3
3        india|print  S3-960981775          source3
4        us|colonial  S3-578159284          source3
5       us|hernandez  S3-578159284          source3
6         us|redwood  S3-578159284          source3
7         us|classic  S3-121412624          source3
8          us|equity  S3-121412624          source3
9         us|madison  S3-249416830          source3

======================================================================
SOURCE-2 INDEX SAMPLE
======================================================================

Source-2 index columns:
['block_key', 'entity_id']

               block_key     entity_id
0             us|seafood  S2-764573417
1                us|peak  S2-764573417
2            us|holloway  S2-764573417
3              us|summit  S2-163963287
4  us|tetlecommunication   S2-49942811
5               us|delta   S2-49942811
6              us|lawson  S2-138046867
7       india|shivshakti  S2-584977605
8        india|vidyalaya  S2-584977605
9         india|overseas  S2-584977605

======================================================================
SOURCE-3 INDEX SAMPLE
======================================================================

Source-3 index columns:
['block_key', 'entity_id']

           block_key     entity_id
0  us|wilfordhancock  S3-202863386
1  india|consultants  S3-859268022
2        india|south  S3-859268022
3         us|moncada   S3-22467283
4          us|arning   S3-22467283
5           us|moyna  S3-671162755
6          us|coffee  S3-671162755
7        india|print  S3-960981775
8        us|colonial  S3-578159284
9       us|hernandez  S3-578159284

In [ ]:
# ============================================
# CELL 16 - BUILD DISK-SAFE BLOCK LOOKUP
# ============================================

import pandas as pd
import os
import sqlite3

BASE_PATH = (
    "/content/drive/MyDrive/"
    "6ab10eb3b23ba_student_resource/"
    "student_resource"
)

BLOCKING_PATH = os.path.join(
    BASE_PATH,
    "blocking"
)

INDEX_PATH = os.path.join(
    BLOCKING_PATH,
    "source_index"
)

DB_PATH = os.path.join(
    BLOCKING_PATH,
    "blocking_lookup.db"
)

SOURCE2_INDEX_PATH = os.path.join(
    INDEX_PATH,
    "source2_blocking_index.tsv"
)

SOURCE3_INDEX_PATH = os.path.join(
    INDEX_PATH,
    "source3_blocking_index.tsv"
)

# Remove old database if it exists
if os.path.exists(DB_PATH):
    os.remove(DB_PATH)

conn = sqlite3.connect(DB_PATH)

print("=" * 70)
print("BUILDING DISK-BASED BLOCK LOOKUP")
print("=" * 70)


def build_table(
    index_path,
    table_name
):

    print(
        f"\nBuilding table: {table_name}"
    )

    first_chunk = True
    total_rows = 0

    for chunk in pd.read_csv(
        index_path,
        sep="\t",
        chunksize=100_000,
        dtype=str
    ):

        chunk = chunk[
            ["block_key", "entity_id"]
        ]

        chunk = chunk.drop_duplicates()

        chunk.to_sql(
            table_name,
            conn,
            if_exists=(
                "replace"
                if first_chunk
                else "append"
            ),
            index=False
        )

        first_chunk = False
        total_rows += len(chunk)

        if total_rows % 1_000_000 == 0:
            print(
                f"Loaded: {total_rows:,}"
            )

        del chunk

    print(
        f"Completed: {total_rows:,} rows"
    )


# Source 2
build_table(
    SOURCE2_INDEX_PATH,
    "source2_blocks"
)

# Source 3
build_table(
    SOURCE3_INDEX_PATH,
    "source3_blocks"
)


# --------------------------------------------
# Create indexes
# --------------------------------------------

print("\nCreating database indexes...")

conn.execute("""
CREATE INDEX idx_source2_block
ON source2_blocks(block_key)
""")

conn.execute("""
CREATE INDEX idx_source3_block
ON source3_blocks(block_key)
""")

conn.commit()

conn.close()

print("\n" + "=" * 70)
print("DISK-BASED BLOCK LOOKUP COMPLETE")
print("=" * 70)

print("\nDatabase:")
print(DB_PATH)

print(
    f"\nDatabase size: "
    f"{os.path.getsize(DB_PATH) / (1024**3):.2f} GB"
)

======================================================================
BUILDING DISK-BASED BLOCK LOOKUP
======================================================================

Building table: source2_blocks
Loaded: 1,000,000
Loaded: 2,000,000
Loaded: 3,000,000
Loaded: 4,000,000
Loaded: 5,000,000
Loaded: 6,000,000
Loaded: 7,000,000
Loaded: 8,000,000
Loaded: 9,000,000
Completed: 9,053,371 rows

Building table: source3_blocks
Loaded: 1,000,000
Loaded: 2,000,000
Loaded: 3,000,000
Loaded: 4,000,000
Loaded: 5,000,000
Loaded: 6,000,000
Loaded: 7,000,000
Loaded: 8,000,000
Loaded: 9,000,000
Loaded: 10,000,000
Completed: 10,040,023 rows

Creating database indexes...

======================================================================
DISK-BASED BLOCK LOOKUP COMPLETE
======================================================================

Database:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/blocking_lookup.db

Database size: 0.94 GB

In [ ]:
# ============================================
# CELL 17 - CHECK SQLITE DATABASE
# ============================================

import sqlite3
import pandas as pd
import os

BASE_PATH = (
    "/content/drive/MyDrive/"
    "6ab10eb3b23ba_student_resource/"
    "student_resource"
)

DB_PATH = os.path.join(
    BASE_PATH,
    "blocking",
    "blocking_lookup.db"
)

print("=" * 70)
print("SQLITE DATABASE CHECK")
print("=" * 70)

print("\nDatabase path:")
print(DB_PATH)

# --------------------------------------------
# Check database file
# --------------------------------------------

if not os.path.exists(DB_PATH):
    raise FileNotFoundError(
        f"Database not found:\n{DB_PATH}"
    )

print("\nDatabase status: OK")

print(
    f"Database size: "
    f"{os.path.getsize(DB_PATH) / (1024**3):.2f} GB"
)

# --------------------------------------------
# Connect
# --------------------------------------------

conn = sqlite3.connect(DB_PATH)

# --------------------------------------------
# List tables
# --------------------------------------------

tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type = 'table'
    ORDER BY name
    """,
    conn
)

print("\nTables found:")
display(tables)

# --------------------------------------------
# Check expected tables
# --------------------------------------------

table_names = set(
    tables["name"].tolist()
)

print("\nExpected tables:")

for table in [
    "source2_blocks",
    "source3_blocks"
]:

    if table in table_names:
        print(f"✅ {table}")
    else:
        print(f"❌ {table} NOT FOUND")

# --------------------------------------------
# Check row counts
# --------------------------------------------

print("\n" + "=" * 70)
print("TABLE ROW COUNTS")
print("=" * 70)

for table in [
    "source2_blocks",
    "source3_blocks"
]:

    if table in table_names:

        count = pd.read_sql_query(
            f"""
            SELECT COUNT(*) AS total_rows
            FROM {table}
            """,
            conn
        ).iloc[0]["total_rows"]

        print(
            f"{table}: "
            f"{count:,} rows"
        )

# --------------------------------------------
# Close
# --------------------------------------------

conn.close()

print("\n" + "=" * 70)
print("DATABASE CHECK COMPLETE")
print("=" * 70)

======================================================================
SQLITE DATABASE CHECK
======================================================================

Database path:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/blocking_lookup.db

Database status: OK
Database size: 0.94 GB

Tables found:

             name
0  source2_blocks
1  source3_blocks

Expected tables:
✅ source2_blocks
✅ source3_blocks

======================================================================
TABLE ROW COUNTS
======================================================================
source2_blocks: 9,053,371 rows
source3_blocks: 10,040,023 rows

======================================================================
DATABASE CHECK COMPLETE
======================================================================

In [ ]:
# ============================================
# CELL 18 - REBUILD SQLITE LOCALLY
# ============================================

import pandas as pd
import sqlite3
import os
import shutil
import gc

print("=" * 70)
print("REBUILDING SQLITE DATABASE LOCALLY")
print("=" * 70)

# --------------------------------------------
# Paths
# --------------------------------------------

BASE_PATH = (
    "/content/drive/MyDrive/"
    "6ab10eb3b23ba_student_resource/"
    "student_resource"
)

INDEX_PATH = os.path.join(
    BASE_PATH,
    "blocking",
    "source_index"
)

SOURCE2_INDEX_PATH = os.path.join(
    INDEX_PATH,
    "source2_blocking_index.tsv"
)

SOURCE3_INDEX_PATH = os.path.join(
    INDEX_PATH,
    "source3_blocking_index.tsv"
)

# IMPORTANT:
# Build database on Colab local disk
LOCAL_DB_PATH = (
    "/content/blocking_lookup.db"
)

# Final backup on Google Drive
DRIVE_DB_PATH = os.path.join(
    BASE_PATH,
    "blocking",
    "blocking_lookup.db"
)

# --------------------------------------------
# Delete old local DB
# --------------------------------------------

if os.path.exists(LOCAL_DB_PATH):
    os.remove(LOCAL_DB_PATH)

print("\nLocal database:")
print(LOCAL_DB_PATH)

# --------------------------------------------
# Connect local SQLite
# --------------------------------------------

conn = sqlite3.connect(
    LOCAL_DB_PATH
)

# --------------------------------------------
# Create tables manually
# --------------------------------------------

conn.execute("""
CREATE TABLE source2_blocks (
    block_key TEXT,
    entity_id TEXT
)
""")

conn.execute("""
CREATE TABLE source3_blocks (
    block_key TEXT,
    entity_id TEXT
)
""")

conn.commit()

print("\nTables created successfully.")


# ============================================
# Function to load index
# ============================================

def load_index(
    index_path,
    table_name
):

    print("\n" + "=" * 70)
    print(
        f"LOADING {table_name}"
    )
    print("=" * 70)

    total_rows = 0

    for chunk in pd.read_csv(
        index_path,
        sep="\t",
        chunksize=100_000,
        dtype=str
    ):

        chunk = chunk[
            ["block_key", "entity_id"]
        ]

        # Remove duplicates inside chunk
        chunk = chunk.drop_duplicates()

        rows = list(
            chunk.itertuples(
                index=False,
                name=None
            )
        )

        conn.executemany(
            f"""
            INSERT INTO {table_name}
            (block_key, entity_id)
            VALUES (?, ?)
            """,
            rows
        )

        conn.commit()

        total_rows += len(chunk)

        if total_rows % 1_000_000 == 0:

            print(
                f"Loaded: "
                f"{total_rows:,}"
            )

        del chunk
        del rows

        gc.collect()

    print(
        f"Completed: "
        f"{total_rows:,} rows"
    )

    return total_rows


# ============================================
# Load Source 2
# ============================================

source2_count = load_index(
    SOURCE2_INDEX_PATH,
    "source2_blocks"
)


# ============================================
# Load Source 3
# ============================================

source3_count = load_index(
    SOURCE3_INDEX_PATH,
    "source3_blocks"
)


# ============================================
# Create indexes
# ============================================

print("\n" + "=" * 70)
print("CREATING SQLITE INDEXES")
print("=" * 70)

conn.execute("""
CREATE INDEX idx_source2_block
ON source2_blocks(block_key)
""")

print("Source-2 index created.")

conn.execute("""
CREATE INDEX idx_source3_block
ON source3_blocks(block_key)
""")

print("Source-3 index created.")

conn.commit()


# ============================================
# Verify tables
# ============================================

print("\n" + "=" * 70)
print("VERIFYING DATABASE")
print("=" * 70)

tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table'
    ORDER BY name
    """,
    conn
)

print("\nTables:")
print(tables)


# --------------------------------------------
# Verify row counts
# --------------------------------------------

count2 = conn.execute(
    "SELECT COUNT(*) FROM source2_blocks"
).fetchone()[0]

count3 = conn.execute(
    "SELECT COUNT(*) FROM source3_blocks"
).fetchone()[0]

print(
    f"\nSource-2 rows: "
    f"{count2:,}"
)

print(
    f"Source-3 rows: "
    f"{count3:,}"
)


# ============================================
# Close database
# ============================================

conn.close()

print("\nDatabase closed.")


# ============================================
# File size
# ============================================

local_size = (
    os.path.getsize(LOCAL_DB_PATH)
    / (1024 ** 3)
)

print(
    f"\nLocal database size: "
    f"{local_size:.2f} GB"
)


# ============================================
# Backup to Google Drive
# ============================================

print("\nCopying verified database to Drive...")

if os.path.exists(DRIVE_DB_PATH):
    os.remove(DRIVE_DB_PATH)

shutil.copy2(
    LOCAL_DB_PATH,
    DRIVE_DB_PATH
)

drive_size = (
    os.path.getsize(DRIVE_DB_PATH)
    / (1024 ** 3)
)

print(
    f"Drive database size: "
    f"{drive_size:.2f} GB"
)


print("\n" + "=" * 70)
print("SQLITE REBUILD COMPLETE")
print("=" * 70)

======================================================================
REBUILDING SQLITE DATABASE LOCALLY
======================================================================

Local database:
/content/blocking_lookup.db

Tables created successfully.

======================================================================
LOADING source2_blocks
======================================================================
Loaded: 1,000,000
Loaded: 2,000,000
Loaded: 3,000,000
Loaded: 4,000,000
Loaded: 5,000,000
Loaded: 6,000,000
Loaded: 7,000,000
Loaded: 8,000,000
Loaded: 9,000,000
Completed: 9,053,371 rows

======================================================================
LOADING source3_blocks
======================================================================
Loaded: 1,000,000
Loaded: 2,000,000
Loaded: 3,000,000
Loaded: 4,000,000
Loaded: 5,000,000
Loaded: 6,000,000
Loaded: 7,000,000
Loaded: 8,000,000
Loaded: 9,000,000
Loaded: 10,000,000
Completed: 10,040,023 rows

======================================================================
CREATING SQLITE INDEXES
======================================================================
Source-2 index created.
Source-3 index created.

======================================================================
VERIFYING DATABASE
======================================================================

Tables:
             name
0  source2_blocks
1  source3_blocks

Source-2 rows: 9,053,371
Source-3 rows: 10,040,023

Database closed.

Local database size: 0.94 GB

Copying verified database to Drive...
Drive database size: 0.94 GB

======================================================================
SQLITE REBUILD COMPLETE
======================================================================

In [ ]:
# ============================================
# SQLITE LOCK RECOVERY
# ============================================

import sqlite3
import gc
import time

DB_PATH = "/content/blocking_lookup.db"

print("Closing old Python objects...")

gc.collect()

print("Waiting for SQLite lock...")
time.sleep(3)

# Test connection
conn = sqlite3.connect(
    DB_PATH,
    timeout=60
)

print("SQLite connection opened successfully.")

# Check tables
cursor = conn.execute("""
SELECT name
FROM sqlite_master
WHERE type='table'
ORDER BY name
""")

print("\nTables:")
for row in cursor.fetchall():
    print(" -", row[0])

conn.close()

print("\nDatabase connection closed.")
print("Recovery check complete.")

Closing old Python objects...
Waiting for SQLite lock...
SQLite connection opened successfully.

Tables:
 - source2_blocks
 - source3_blocks

Database connection closed.
Recovery check complete.

In [ ]:
# ============================================
# CELL 20 - CREATE BLOCK FREQUENCY TABLES
# ============================================

import sqlite3
import pandas as pd
import time

DB_PATH = "/content/blocking_lookup.db"

print("=" * 70)
print("CREATING BLOCK FREQUENCY TABLES")
print("=" * 70)

conn = sqlite3.connect(DB_PATH, timeout=120)

# ------------------------------------------------
# SOURCE-2
# ------------------------------------------------

print("\nSource-2:")
print("Calculating block frequencies...")

conn.execute("""
DROP TABLE IF EXISTS source2_block_counts
""")

conn.commit()

start = time.time()

conn.execute("""
CREATE TABLE source2_block_counts AS
SELECT
    block_key,
    COUNT(*) AS candidate_count
FROM source2_blocks
GROUP BY block_key
""")

conn.commit()

print(
    f"Source-2 frequency table created "
    f"in {time.time() - start:.1f} seconds."
)

# ------------------------------------------------
# SOURCE-3
# ------------------------------------------------

print("\nSource-3:")
print("Calculating block frequencies...")

conn.execute("""
DROP TABLE IF EXISTS source3_block_counts
""")

conn.commit()

start = time.time()

conn.execute("""
CREATE TABLE source3_block_counts AS
SELECT
    block_key,
    COUNT(*) AS candidate_count
FROM source3_blocks
GROUP BY block_key
""")

conn.commit()

print(
    f"Source-3 frequency table created "
    f"in {time.time() - start:.1f} seconds."
)

# ------------------------------------------------
# CREATE INDEXES
# ------------------------------------------------

print("\nCreating indexes...")

conn.execute("""
CREATE INDEX idx_s2_block_count_key
ON source2_block_counts(block_key)
""")

conn.execute("""
CREATE INDEX idx_s3_block_count_key
ON source3_block_counts(block_key)
""")

conn.commit()

# ------------------------------------------------
# SUMMARY
# ------------------------------------------------

s2_count = conn.execute("""
SELECT COUNT(*)
FROM source2_block_counts
""").fetchone()[0]

s3_count = conn.execute("""
SELECT COUNT(*)
FROM source3_block_counts
""").fetchone()[0]

print("\n" + "=" * 70)
print("FREQUENCY TABLE SUMMARY")
print("=" * 70)

print(f"Source-2 unique blocks: {s2_count:,}")
print(f"Source-3 unique blocks: {s3_count:,}")

conn.close()

print("\n" + "=" * 70)
print("CELL 20 COMPLETE")
print("=" * 70)

======================================================================
CREATING BLOCK FREQUENCY TABLES
======================================================================

Source-2:
Calculating block frequencies...
Source-2 frequency table created in 2.5 seconds.

Source-3:
Calculating block frequencies...
Source-3 frequency table created in 1.5 seconds.

Creating indexes...

======================================================================
FREQUENCY TABLE SUMMARY
======================================================================
Source-2 unique blocks: 796,214
Source-3 unique blocks: 857,298

======================================================================
CELL 20 COMPLETE
======================================================================

In [ ]:
# ============================================
# CELL 21 - ANALYZE BLOCK SIZE THRESHOLDS
# ============================================

import sqlite3
import pandas as pd

DB_PATH = "/content/blocking_lookup.db"

conn = sqlite3.connect(DB_PATH, timeout=120)

print("=" * 70)
print("BLOCK SIZE THRESHOLD ANALYSIS")
print("=" * 70)

thresholds = [5, 10, 20, 50, 100, 250, 500, 1000]

for table, source in [
    ("source2_block_counts", "SOURCE-2"),
    ("source3_block_counts", "SOURCE-3")
]:

    print("\n" + "=" * 70)
    print(source)
    print("=" * 70)

    rows = []

    for threshold in thresholds:

        result = conn.execute(
            f"""
            SELECT
                COUNT(*) AS blocks,
                COALESCE(SUM(candidate_count), 0) AS rows
            FROM {table}
            WHERE candidate_count <= ?
            """,
            (threshold,)
        ).fetchone()

        blocks, candidate_rows = result

        rows.append({
            "max_block_size": threshold,
            "usable_blocks": blocks,
            "candidate_rows": candidate_rows
        })

    df = pd.DataFrame(rows)

    display(df)

conn.close()

print("\n" + "=" * 70)
print("CELL 21 COMPLETE")
print("=" * 70)

======================================================================
BLOCK SIZE THRESHOLD ANALYSIS
======================================================================

======================================================================
SOURCE-2
======================================================================

   max_block_size  usable_blocks  candidate_rows
0               5         723919          864200
1              10         746289         1036413
2              20         764115         1296671
3              50         779492         1794686
4             100         788976         2461265
5             250         792877         3042280
6             500         793980         3421355
7            1000         795246         4396663

======================================================================
SOURCE-3
======================================================================

   max_block_size  usable_blocks  candidate_rows
0               5         782030          936768
1              10         803251         1099509
2              20         820728         1356164
3              50         838674         1942470
4             100         849627         2702375
5             250         853821         3326118
6             500         855002         3731799
7            1000         856274         4731839

======================================================================
CELL 21 COMPLETE
======================================================================

In [ ]:
# ============================================
# CELL 22 - SAFE CANDIDATE GENERATION TEST
# 10,000 SOURCE-1 RECORDS ONLY
# ============================================

import sqlite3
import pandas as pd
import os
import re
import time

DB_PATH = "/content/blocking_lookup.db"

SOURCE1_PATH = os.path.join(
    PROCESSED_PATH,
    "cleaned_train_source1.tsv"
)

OUTPUT_DIR = os.path.join(
    BASE_PATH,
    "blocking",
    "candidates"
)

os.makedirs(OUTPUT_DIR, exist_ok=True)

OUTPUT_PATH = os.path.join(
    OUTPUT_DIR,
    "candidate_test_10k.tsv"
)

MAX_BLOCK_SIZE = 20
TEST_ROWS = 10_000

print("=" * 70)
print("SAFE CANDIDATE GENERATION TEST")
print("=" * 70)

print(f"\nSource-1 test rows : {TEST_ROWS:,}")
print(f"Maximum block size : {MAX_BLOCK_SIZE}")

# ------------------------------------------------
# Load Source-1 sample
# ------------------------------------------------

source1 = pd.read_csv(
    SOURCE1_PATH,
    sep="\t",
    nrows=TEST_ROWS,
    dtype=str
).fillna("")

print(
    f"\nLoaded Source-1 rows: "
    f"{len(source1):,}"
)

# ------------------------------------------------
# Create blocking keys
# ------------------------------------------------

def make_block_keys(name, address, country):

    text = f"{name} {address}".lower()

    text = re.sub(
        r"[^a-z0-9\s]",
        " ",
        text
    )

    tokens = set(
        token
        for token in text.split()
        if len(token) >= 3
    )

    keys = []

    country = str(country).strip().lower()

    for token in tokens:
        if country:
            keys.append(
                f"{country}|{token}"
            )

    return keys


# ------------------------------------------------
# Open database
# ------------------------------------------------

conn = sqlite3.connect(
    DB_PATH,
    timeout=120
)

print("\nSQLite database connected.")

# ------------------------------------------------
# Candidate generation
# ------------------------------------------------

candidate_rows = []

start_time = time.time()

for idx, row in source1.iterrows():

    keys = make_block_keys(
        row["business_name"],
        row["business_address"],
        row["country"]
    )

    # Remove duplicate keys
    keys = list(set(keys))

    for block_key in keys:

        # -------------------------------
        # Source-2
        # -------------------------------

        s2 = conn.execute(
            """
            SELECT entity_id
            FROM source2_blocks
            WHERE block_key = ?
            AND block_key IN (
                SELECT block_key
                FROM source2_block_counts
                WHERE block_key = ?
                AND candidate_count <= ?
            )
            """,
            (
                block_key,
                block_key,
                MAX_BLOCK_SIZE
            )
        ).fetchall()

        for (entity_id,) in s2:

            candidate_rows.append({
                "source1_entity_id":
                    row["entity_id"],
                "candidate_entity_id":
                    entity_id,
                "candidate_source":
                    "source2",
                "block_key":
                    block_key
            })

        # -------------------------------
        # Source-3
        # -------------------------------

        s3 = conn.execute(
            """
            SELECT entity_id
            FROM source3_blocks
            WHERE block_key = ?
            AND block_key IN (
                SELECT block_key
                FROM source3_block_counts
                WHERE block_key = ?
                AND candidate_count <= ?
            )
            """,
            (
                block_key,
                block_key,
                MAX_BLOCK_SIZE
            )
        ).fetchall()

        for (entity_id,) in s3:

            candidate_rows.append({
                "source1_entity_id":
                    row["entity_id"],
                "candidate_entity_id":
                    entity_id,
                "candidate_source":
                    "source3",
                "block_key":
                    block_key
            })

    # Progress
    if (idx + 1) % 1000 == 0:

        print(
            f"Processed: {idx + 1:,} | "
            f"Candidates: {len(candidate_rows):,}"
        )

conn.close()

# ------------------------------------------------
# Save candidates
# ------------------------------------------------

candidate_df = pd.DataFrame(
    candidate_rows
)

candidate_df.to_csv(
    OUTPUT_PATH,
    sep="\t",
    index=False
)

elapsed = time.time() - start_time

print("\n" + "=" * 70)
print("CANDIDATE TEST COMPLETE")
print("=" * 70)

print(
    f"\nSource-1 records: "
    f"{TEST_ROWS:,}"
)

print(
    f"Candidate rows: "
    f"{len(candidate_df):,}"
)

print(
    f"Average candidates per Source-1: "
    f"{len(candidate_df) / TEST_ROWS:.2f}"
)

print(
    f"\nTime taken: "
    f"{elapsed / 60:.2f} minutes"
)

print(
    f"\nCandidate file:\n"
    f"{OUTPUT_PATH}"
)

======================================================================
SAFE CANDIDATE GENERATION TEST
======================================================================

Source-1 test rows : 10,000
Maximum block size : 20

Loaded Source-1 rows: 10,000

SQLite database connected.
Processed: 1,000 | Candidates: 13,196
Processed: 2,000 | Candidates: 26,727
Processed: 3,000 | Candidates: 40,340
Processed: 4,000 | Candidates: 53,535
Processed: 5,000 | Candidates: 66,782
Processed: 6,000 | Candidates: 79,098
Processed: 7,000 | Candidates: 91,674
Processed: 8,000 | Candidates: 104,505
Processed: 9,000 | Candidates: 117,570
Processed: 10,000 | Candidates: 131,745

======================================================================
CANDIDATE TEST COMPLETE
======================================================================

Source-1 records: 10,000
Candidate rows: 131,745
Average candidates per Source-1: 13.17

Time taken: 1.26 minutes

Candidate file:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/candidate_test_10k.tsv

In [ ]:
# ============================================
# CELL 23 - VERIFY CANDIDATE + GROUND TRUTH
# ============================================

import os
import pandas as pd

BASE_PATH = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource"

CANDIDATE_PATH = os.path.join(
    BASE_PATH,
    "blocking",
    "candidates",
    "candidate_test_10k.tsv"
)

print("=" * 70)
print("CELL 23 - FILE AND STRUCTURE VERIFICATION")
print("=" * 70)

# ------------------------------------------------
# 1. Candidate file check
# ------------------------------------------------

print("\nCandidate file:")
print(CANDIDATE_PATH)

if not os.path.exists(CANDIDATE_PATH):
    raise FileNotFoundError(
        f"Candidate file not found:\n{CANDIDATE_PATH}"
    )

print("STATUS: OK")

# ------------------------------------------------
# 2. Candidate structure
# ------------------------------------------------

candidate_sample = pd.read_csv(
    CANDIDATE_PATH,
    sep="\t",
    nrows=10,
    dtype=str
)

print("\nCandidate columns:")
print(candidate_sample.columns.tolist())

print("\nCandidate sample:")
display(candidate_sample)

# ------------------------------------------------
# 3. Search for ground truth
# ------------------------------------------------

print("\n" + "=" * 70)
print("SEARCHING FOR GROUND TRUTH")
print("=" * 70)

ground_truth_files = []

for root, dirs, files in os.walk(BASE_PATH):

    for file in files:

        if (
            "ground_truth" in file.lower()
            or "groundtruth" in file.lower()
        ):

            full_path = os.path.join(root, file)

            ground_truth_files.append(full_path)

            print("\nFOUND:")
            print(full_path)

# ------------------------------------------------
# 4. Result
# ------------------------------------------------

print("\n" + "=" * 70)
print("CELL 23 COMPLETE")
print("=" * 70)

if len(ground_truth_files) == 0:

    print("\n❌ Ground-truth file was not found.")

else:

    print(
        f"\n✅ Ground-truth files found: "
        f"{len(ground_truth_files)}"
    )

print("\nIMPORTANT:")
print("Candidate file currently needs Source-1 ID")
print("for exact blocking-recall validation.")

======================================================================
CELL 23 - FILE AND STRUCTURE VERIFICATION
======================================================================

Candidate file:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/candidate_test_10k.tsv
STATUS: OK

Candidate columns:
['source1_entity_id', 'candidate_entity_id', 'candidate_source', 'block_key']

Candidate sample:

  source1_entity_id candidate_entity_id candidate_source       block_key
0      S1-925783039        S2-202974731          source2  us|westchester
1      S1-925783039        S2-393846896          source2  us|westchester
2      S1-925783039         S3-59852150          source3  us|westchester
3      S1-925783039         S3-20472883          source3  us|westchester
4      S1-925783039        S3-112073915          source3  us|westchester
5      S1-925783039        S2-621757655          source2         us|1795
6      S1-925783039        S2-412342728          source2         us|1795
7      S1-925783039        S2-807577508          source2         us|1795
8      S1-925783039        S2-137172441          source2         us|1795
9      S1-925783039        S3-880261982          source3         us|1795

======================================================================
SEARCHING FOR GROUND TRUTH
======================================================================

FOUND:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_ground_truth.tsv

FOUND:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ground_truth_aligned_10k.tsv

======================================================================
CELL 23 COMPLETE
======================================================================

✅ Ground-truth files found: 2

IMPORTANT:
Candidate file currently needs Source-1 ID
for exact blocking-recall validation.

In [ ]:
# ============================================
# CELL 24 - BLOCKING RECALL VALIDATION
# ============================================

import pandas as pd
import os

BASE_PATH = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource"

CANDIDATE_PATH = os.path.join(
    BASE_PATH,
    "blocking",
    "candidates",
    "candidate_test_10k.tsv"
)

GROUND_TRUTH_PATH = os.path.join(
    BASE_PATH,
    "dataset",
    "train",
    "train_ground_truth.tsv"
)

print("=" * 70)
print("BLOCKING RECALL VALIDATION")
print("=" * 70)

# ============================================================
# STEP 1 - LOAD CANDIDATES
# ============================================================

print("\nLoading candidate file...")

candidates = pd.read_csv(
    CANDIDATE_PATH,
    sep="\t",
    dtype=str
)

print(f"Candidate rows: {len(candidates):,}")

# Remove duplicate pairs
candidates = candidates.drop_duplicates(
    subset=[
        "source1_entity_id",
        "candidate_entity_id"
    ]
)

print(
    f"Unique candidate pairs: "
    f"{len(candidates):,}"
)

# ============================================================
# STEP 2 - LOAD GROUND TRUTH
# ============================================================

print("\nLoading ground truth...")

ground_truth = pd.read_csv(
    GROUND_TRUTH_PATH,
    sep="\t",
    nrows=10_000,
    dtype=str
)

print(
    f"Ground-truth rows: "
    f"{len(ground_truth):,}"
)

print("\nGround-truth columns:")
print(ground_truth.columns.tolist())

# ============================================================
# STEP 3 - CREATE CANDIDATE LOOKUP
# ============================================================

print("\nCreating candidate lookup...")

candidate_pairs = set(
    zip(
        candidates["source1_entity_id"],
        candidates["candidate_entity_id"]
    )
)

print(
    f"Candidate lookup pairs: "
    f"{len(candidate_pairs):,}"
)

# ============================================================
# STEP 4 - VALIDATE GROUND-TRUTH MATCHES
# ============================================================

print("\nChecking ground-truth matches...")

total_positive_pairs = 0
captured_positive_pairs = 0

records_with_match = 0
records_with_captured_match = 0

for _, row in ground_truth.iterrows():

    source1_id = str(
        row["source1_entity_id"]
    ).strip()

    matched_ids = row["matched_entity_ids"]

    # --------------------------------------------
    # No match
    # --------------------------------------------

    if pd.isna(matched_ids):
        continue

    matched_ids = str(
        matched_ids
    ).strip()

    if matched_ids == "":
        continue

    # --------------------------------------------
    # Convert matched IDs into list
    # --------------------------------------------

    matched_list = [
        x.strip()
        for x in matched_ids.split(",")
        if x.strip()
    ]

    if len(matched_list) == 0:
        continue

    records_with_match += 1

    record_captured = False

    # --------------------------------------------
    # Check every true match
    # --------------------------------------------

    for target_id in matched_list:

        total_positive_pairs += 1

        pair = (
            source1_id,
            target_id
        )

        if pair in candidate_pairs:

            captured_positive_pairs += 1
            record_captured = True

    if record_captured:

        records_with_captured_match += 1


# ============================================================
# STEP 5 - CALCULATE RECALL
# ============================================================

if total_positive_pairs > 0:

    pair_recall = (
        captured_positive_pairs /
        total_positive_pairs
    ) * 100

else:

    pair_recall = 0.0


if records_with_match > 0:

    record_recall = (
        records_with_captured_match /
        records_with_match
    ) * 100

else:

    record_recall = 0.0


# ============================================================
# STEP 6 - RESULTS
# ============================================================

print("\n" + "=" * 70)
print("BLOCKING RECALL RESULTS")
print("=" * 70)

print(
    f"\nGround-truth positive pairs : "
    f"{total_positive_pairs:,}"
)

print(
    f"Captured positive pairs     : "
    f"{captured_positive_pairs:,}"
)

print(
    f"Missed positive pairs       : "
    f"{total_positive_pairs - captured_positive_pairs:,}"
)

print(
    f"\nPair-level blocking recall  : "
    f"{pair_recall:.2f}%"
)

print(
    f"\nSource-1 records with match : "
    f"{records_with_match:,}"
)

print(
    f"Records with >=1 captured   : "
    f"{records_with_captured_match:,}"
)

print(
    f"Records with no candidate   : "
    f"{records_with_match - records_with_captured_match:,}"
)

print(
    f"\nRecord-level blocking recall: "
    f"{record_recall:.2f}%"
)

print("\n" + "=" * 70)
print("CELL 24 COMPLETE")
print("=" * 70)

======================================================================
BLOCKING RECALL VALIDATION
======================================================================

Loading candidate file...
Candidate rows: 131,745
Unique candidate pairs: 131,185

Loading ground truth...
Ground-truth rows: 10,000

Ground-truth columns:
['source1_entity_id', 'matched_entity_ids']

Creating candidate lookup...
Candidate lookup pairs: 131,185

Checking ground-truth matches...

======================================================================
BLOCKING RECALL RESULTS
======================================================================

Ground-truth positive pairs : 34,511
Captured positive pairs     : 9
Missed positive pairs       : 34,502

Pair-level blocking recall  : 0.03%

Source-1 records with match : 9,443
Records with >=1 captured   : 4
Records with no candidate   : 9,439

Record-level blocking recall: 0.04%

======================================================================
CELL 24 COMPLETE
======================================================================

In [ ]:
# ============================================
# CELL 25 - DIAGNOSE LOW BLOCKING RECALL
# ============================================

import pandas as pd
import os

BASE_PATH = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource"

CANDIDATE_PATH = os.path.join(
    BASE_PATH,
    "blocking",
    "candidates",
    "candidate_test_10k.tsv"
)

GROUND_TRUTH_PATH = os.path.join(
    BASE_PATH,
    "dataset",
    "train",
    "train_ground_truth.tsv"
)

print("=" * 70)
print("DIAGNOSING LOW BLOCKING RECALL")
print("=" * 70)

# ------------------------------------------------
# Load candidates
# ------------------------------------------------

candidates = pd.read_csv(
    CANDIDATE_PATH,
    sep="\t",
    dtype=str
)

print("\nCandidate columns:")
print(candidates.columns.tolist())

# ------------------------------------------------
# Load ground truth
# ------------------------------------------------

ground_truth = pd.read_csv(
    GROUND_TRUTH_PATH,
    sep="\t",
    nrows=10_000,
    dtype=str
)

print("\nGround-truth columns:")
print(ground_truth.columns.tolist())

# ------------------------------------------------
# Display raw ground-truth examples
# ------------------------------------------------

print("\n" + "=" * 70)
print("RAW GROUND-TRUTH EXAMPLES")
print("=" * 70)

display(
    ground_truth[
        [
            "source1_entity_id",
            "matched_entity_ids"
        ]
    ].head(10)
)

# ------------------------------------------------
# Display candidate examples
# ------------------------------------------------

print("\n" + "=" * 70)
print("RAW CANDIDATE EXAMPLES")
print("=" * 70)

display(
    candidates.head(20)
)

# ------------------------------------------------
# Check ID formats
# ------------------------------------------------

print("\n" + "=" * 70)
print("ID FORMAT CHECK")
print("=" * 70)

print("\nGround-truth Source-1 IDs:")

print(
    ground_truth["source1_entity_id"]
    .dropna()
    .head(20)
    .tolist()
)

print("\nCandidate Source-1 IDs:")

print(
    candidates["source1_entity_id"]
    .dropna()
    .head(20)
    .tolist()
)

print("\nCandidate entity IDs:")

print(
    candidates["candidate_entity_id"]
    .dropna()
    .head(20)
    .tolist()
)

# ------------------------------------------------
# Find one ground-truth record that has matches
# ------------------------------------------------

print("\n" + "=" * 70)
print("DETAILED SINGLE-RECORD CHECK")
print("=" * 70)

example_gt = None

for _, row in ground_truth.iterrows():

    if pd.isna(row["matched_entity_ids"]):
        continue

    value = str(
        row["matched_entity_ids"]
    ).strip()

    if value != "":
        example_gt = row
        break

if example_gt is not None:

    source1_id = str(
        example_gt["source1_entity_id"]
    ).strip()

    raw_matches = str(
        example_gt["matched_entity_ids"]
    ).strip()

    print("\nSource-1 ID:")
    print(source1_id)

    print("\nRaw matched_entity_ids:")
    print(raw_matches)

    print("\nFirst 500 characters:")
    print(raw_matches[:500])

    # Try comma split
    comma_ids = [
        x.strip()
        for x in raw_matches.split(",")
        if x.strip()
    ]

    print("\nComma-separated IDs:")
    print(comma_ids[:20])

    # Candidate rows for this Source-1
    candidate_rows = candidates[
        candidates["source1_entity_id"] == source1_id
    ]

    print(
        f"\nCandidates generated for this Source-1: "
        f"{len(candidate_rows):,}"
    )

    if len(candidate_rows) > 0:

        print("\nCandidate IDs:")
        print(
            candidate_rows[
                "candidate_entity_id"
            ].tolist()[:50]
        )

        # Check intersections
        candidate_id_set = set(
            candidate_rows[
                "candidate_entity_id"
            ]
        )

        intersection = [
            x for x in comma_ids
            if x in candidate_id_set
        ]

        print("\nTrue matches captured:")
        print(intersection)

        print(
            f"\nCaptured for this record: "
            f"{len(intersection)}"
        )

else:

    print("❌ No positive ground-truth record found.")

# ------------------------------------------------
# Candidate source distribution
# ------------------------------------------------

print("\n" + "=" * 70)
print("CANDIDATE SOURCE DISTRIBUTION")
print("=" * 70)

print(
    candidates["candidate_source"]
    .value_counts()
)

# ------------------------------------------------
# Final
# ------------------------------------------------

print("\n" + "=" * 70)
print("CELL 25 COMPLETE")
print("=" * 70)

print(
    "\nDO NOT change the threshold yet."
)

print(
    "We first need to identify the ID/blocking mismatch."
)

======================================================================
DIAGNOSING LOW BLOCKING RECALL
======================================================================

Candidate columns:
['source1_entity_id', 'candidate_entity_id', 'candidate_source', 'block_key']

Ground-truth columns:
['source1_entity_id', 'matched_entity_ids']

======================================================================
RAW GROUND-TRUTH EXAMPLES
======================================================================

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5       S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6      S1-318373630                          S2-660036492,S3-804600254
7       S1-86989137                          S3-274817120,S3-312496301
8       S1-29845983                          S2-648035184,S3-588502663
9      S1-789009573              S2-383871912,S3-74481402,S3-576451439

======================================================================
RAW CANDIDATE EXAMPLES
======================================================================

   source1_entity_id candidate_entity_id candidate_source       block_key
0       S1-925783039        S2-202974731          source2  us|westchester
1       S1-925783039        S2-393846896          source2  us|westchester
2       S1-925783039         S3-59852150          source3  us|westchester
3       S1-925783039         S3-20472883          source3  us|westchester
4       S1-925783039        S3-112073915          source3  us|westchester
5       S1-925783039        S2-621757655          source2         us|1795
6       S1-925783039        S2-412342728          source2         us|1795
7       S1-925783039        S2-807577508          source2         us|1795
8       S1-925783039        S2-137172441          source2         us|1795
9       S1-925783039        S3-880261982          source3         us|1795
10      S1-925783039        S3-128905334          source3         us|1795
11      S1-925783039        S3-646888144          source3         us|1795
12      S1-925783039        S3-143544733          source3         us|1795
13      S1-925783039        S3-793054764          source3         us|1795
14      S1-925783039        S3-753203621          source3         us|1795
15      S1-773889195        S2-738816767          source2    us|tahlequah
16      S1-773889195        S2-720004238          source2    us|tahlequah
17      S1-773889195        S2-390442623          source2    us|tahlequah
18      S1-773889195        S2-740666011          source2    us|tahlequah
19      S1-773889195        S2-148957721          source2    us|tahlequah

======================================================================
ID FORMAT CHECK
======================================================================

Ground-truth Source-1 IDs:
['S1-965667', 'S1-55344266', 'S1-343815751', 'S1-656753428', 'S1-102811957', 'S1-18727616', 'S1-318373630', 'S1-86989137', 'S1-29845983', 'S1-789009573', 'S1-730934468', 'S1-7293388', 'S1-546142636', 'S1-274126313', 'S1-145361722', 'S1-503957000', 'S1-692000596', 'S1-561341312', 'S1-777597828', 'S1-282467635']

Candidate Source-1 IDs:
['S1-925783039', 'S1-925783039', 'S1-925783039', 'S1-925783039', 'S1-925783039', 'S1-925783039', 'S1-925783039', 'S1-925783039', 'S1-925783039', 'S1-925783039', 'S1-925783039', 'S1-925783039', 'S1-925783039', 'S1-925783039', 'S1-925783039', 'S1-773889195', 'S1-773889195', 'S1-773889195', 'S1-773889195', 'S1-773889195']

Candidate entity IDs:
['S2-202974731', 'S2-393846896', 'S3-59852150', 'S3-20472883', 'S3-112073915', 'S2-621757655', 'S2-412342728', 'S2-807577508', 'S2-137172441', 'S3-880261982', 'S3-128905334', 'S3-646888144', 'S3-143544733', 'S3-793054764', 'S3-753203621', 'S2-738816767', 'S2-720004238', 'S2-390442623', 'S2-740666011', 'S2-148957721']

======================================================================
DETAILED SINGLE-RECORD CHECK
======================================================================

Source-1 ID:
S1-965667

Raw matched_entity_ids:
S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364

First 500 characters:
S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364

Comma-separated IDs:
['S2-681193310', 'S2-743505751', 'S3-775321672', 'S3-11291185', 'S3-860443364']

Candidates generated for this Source-1: 0

======================================================================
CANDIDATE SOURCE DISTRIBUTION
======================================================================
candidate_source
source2    70534
source3    61211
Name: count, dtype: int64

======================================================================
CELL 25 COMPLETE
======================================================================

DO NOT change the threshold yet.
We first need to identify the ID/blocking mismatch.

In [ ]:
import os
import pandas as pd

print("=" * 70)
print("CELL 26 - SOURCE-1 ID / ROW MAPPING CHECK")
print("=" * 70)

SOURCE1_PATH = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/processed_data/cleaned_train_source1.tsv"
GROUND_TRUTH_PATH = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_ground_truth.tsv"
CANDIDATE_PATH = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/candidate_test_10k.tsv"

# ------------------------------------------------------------
# 1. Load Source-1 test rows
# ------------------------------------------------------------

print("\nLoading Source-1 first 10,000 rows...")

source1 = pd.read_csv(
    SOURCE1_PATH,
    sep="\t",
    nrows=10000,
    dtype=str
)

print("Source-1 rows:", len(source1))
print("Source-1 columns:", list(source1.columns))

# ------------------------------------------------------------
# 2. Detect entity ID column
# ------------------------------------------------------------

if "entity_id" in source1.columns:
    source1_id_col = "entity_id"
elif "source1_entity_id" in source1.columns:
    source1_id_col = "source1_entity_id"
else:
    raise ValueError(
        f"Source-1 ID column not found. Columns: {list(source1.columns)}"
    )

source1_ids = source1[source1_id_col].astype(str)

print("\nSource-1 ID column:", source1_id_col)
print("First 20 Source-1 IDs:")
print(source1_ids.head(20).tolist())

# ------------------------------------------------------------
# 3. Load ground truth
# ------------------------------------------------------------

print("\nLoading ground truth...")

gt = pd.read_csv(
    GROUND_TRUTH_PATH,
    sep="\t",
    nrows=10000,
    dtype=str
)

print("Ground-truth rows:", len(gt))
print("Ground-truth columns:", list(gt.columns))

gt_ids = gt["source1_entity_id"].astype(str)

print("\nFirst 20 Ground-truth Source-1 IDs:")
print(gt_ids.head(20).tolist())

# ------------------------------------------------------------
# 4. Compare IDs
# ------------------------------------------------------------

source1_set = set(source1_ids)
gt_set = set(gt_ids)

common_ids = source1_set.intersection(gt_set)

print("\n" + "=" * 70)
print("ID OVERLAP")
print("=" * 70)

print("Source-1 unique IDs:", len(source1_set))
print("Ground-truth unique IDs:", len(gt_set))
print("Common IDs:", len(common_ids))

print(
    "Source-1 IDs missing from ground truth:",
    len(source1_set - gt_set)
)

print(
    "Ground-truth IDs missing from Source-1:",
    len(gt_set - source1_set)
)

# ------------------------------------------------------------
# 5. Check specific ID from Cell 25
# ------------------------------------------------------------

test_id = "S1-965667"

print("\n" + "=" * 70)
print("SPECIFIC ID CHECK")
print("=" * 70)

print("Checking:", test_id)

print("Exists in Source-1:",
      test_id in source1_set)

print("Exists in Ground Truth:",
      test_id in gt_set)

# ------------------------------------------------------------
# 6. Show first IDs side-by-side
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FIRST 20 IDs COMPARISON")
print("=" * 70)

comparison = pd.DataFrame({
    "source1_id": source1_ids.head(20).tolist(),
    "ground_truth_id": gt_ids.head(20).tolist()
})

print(comparison.to_string(index=False))

# ------------------------------------------------------------
# 7. Final diagnosis
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CELL 26 COMPLETE")
print("=" * 70)

if len(common_ids) == len(source1_set) == len(gt_set):
    print("RESULT: IDs match perfectly.")
elif len(common_ids) > 0:
    print("RESULT: Partial ID overlap detected.")
    print("Further row/order mapping check is required.")
else:
    print("RESULT: NO ID OVERLAP.")
    print("This confirms an ID/source mismatch.")

======================================================================
CELL 26 - SOURCE-1 ID / ROW MAPPING CHECK
======================================================================

Loading Source-1 first 10,000 rows...
Source-1 rows: 10000
Source-1 columns: ['entity_id', 'business_name', 'business_address', 'country']

Source-1 ID column: entity_id
First 20 Source-1 IDs:
['S1-925783039', 'S1-773889195', 'S1-377745466', 'S1-133037285', 'S1-755362802', 'S1-851869949', 'S1-785847572', 'S1-27541239', 'S1-629417405', 'S1-22305073', 'S1-504790211', 'S1-564729135', 'S1-236312382', 'S1-865131206', 'S1-626914593', 'S1-765734254', 'S1-82053739', 'S1-309349399', 'S1-221443075', 'S1-341506266']

Loading ground truth...
Ground-truth rows: 10000
Ground-truth columns: ['source1_entity_id', 'matched_entity_ids']

First 20 Ground-truth Source-1 IDs:
['S1-965667', 'S1-55344266', 'S1-343815751', 'S1-656753428', 'S1-102811957', 'S1-18727616', 'S1-318373630', 'S1-86989137', 'S1-29845983', 'S1-789009573', 'S1-730934468', 'S1-7293388', 'S1-546142636', 'S1-274126313', 'S1-145361722', 'S1-503957000', 'S1-692000596', 'S1-561341312', 'S1-777597828', 'S1-282467635']

======================================================================
ID OVERLAP
======================================================================
Source-1 unique IDs: 10000
Ground-truth unique IDs: 10000
Common IDs: 59
Source-1 IDs missing from ground truth: 9941
Ground-truth IDs missing from Source-1: 9941

======================================================================
SPECIFIC ID CHECK
======================================================================
Checking: S1-965667
Exists in Source-1: False
Exists in Ground Truth: True

======================================================================
FIRST 20 IDs COMPARISON
======================================================================
  source1_id ground_truth_id
S1-925783039       S1-965667
S1-773889195     S1-55344266
S1-377745466    S1-343815751
S1-133037285    S1-656753428
S1-755362802    S1-102811957
S1-851869949     S1-18727616
S1-785847572    S1-318373630
 S1-27541239     S1-86989137
S1-629417405     S1-29845983
 S1-22305073    S1-789009573
S1-504790211    S1-730934468
S1-564729135      S1-7293388
S1-236312382    S1-546142636
S1-865131206    S1-274126313
S1-626914593    S1-145361722
S1-765734254    S1-503957000
 S1-82053739    S1-692000596
S1-309349399    S1-561341312
S1-221443075    S1-777597828
S1-341506266    S1-282467635

======================================================================
CELL 26 COMPLETE
======================================================================
RESULT: Partial ID overlap detected.
Further row/order mapping check is required.

In [ ]:
# ============================================
# CELL 27 - ALIGN GROUND TRUTH BY SOURCE-1 ID
# ============================================

import pandas as pd
import os

BASE_PATH = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource"

SOURCE1_PATH = os.path.join(
    BASE_PATH,
    "processed_data",
    "cleaned_train_source1.tsv"
)

GROUND_TRUTH_PATH = os.path.join(
    BASE_PATH,
    "dataset",
    "train",
    "train_ground_truth.tsv"
)

CANDIDATE_PATH = os.path.join(
    BASE_PATH,
    "blocking",
    "candidates",
    "candidate_test_10k.tsv"
)

print("=" * 70)
print("CELL 27 - GROUND TRUTH ALIGNMENT")
print("=" * 70)

# ------------------------------------------------
# Load first 10K Source-1 records
# ------------------------------------------------

print("\nLoading Source-1...")

source1 = pd.read_csv(
    SOURCE1_PATH,
    sep="\t",
    nrows=10_000,
    dtype=str
)

source1_ids = set(
    source1["entity_id"].astype(str)
)

print(
    f"Source-1 test IDs: "
    f"{len(source1_ids):,}"
)

# ------------------------------------------------
# Load ground truth
# ------------------------------------------------

print("\nLoading ground truth...")

ground_truth = pd.read_csv(
    GROUND_TRUTH_PATH,
    sep="\t",
    dtype=str
)

print(
    f"Total ground-truth rows: "
    f"{len(ground_truth):,}"
)

# ------------------------------------------------
# Filter ground truth using Source-1 IDs
# ------------------------------------------------

aligned_gt = ground_truth[
    ground_truth["source1_entity_id"].isin(source1_ids)
].copy()

print(
    f"\nGround-truth rows matching "
    f"our Source-1 test set: "
    f"{len(aligned_gt):,}"
)

# ------------------------------------------------
# Check missing Source-1 IDs
# ------------------------------------------------

aligned_ids = set(
    aligned_gt["source1_entity_id"].astype(str)
)

missing_ids = source1_ids - aligned_ids

print(
    f"Source-1 IDs without ground truth: "
    f"{len(missing_ids):,}"
)

# ------------------------------------------------
# Show examples
# ------------------------------------------------

print("\n" + "=" * 70)
print("ALIGNED GROUND-TRUTH SAMPLE")
print("=" * 70)

display(
    aligned_gt.head(10)
)

# ------------------------------------------------
# Candidate IDs
# ------------------------------------------------

candidates = pd.read_csv(
    CANDIDATE_PATH,
    sep="\t",
    dtype=str
)

candidate_ids = set(
    candidates["source1_entity_id"].astype(str)
)

print("\n" + "=" * 70)
print("CANDIDATE / GROUND TRUTH ALIGNMENT")
print("=" * 70)

print(
    f"Source-1 IDs in candidates: "
    f"{len(candidate_ids):,}"
)

print(
    f"Source-1 IDs in aligned GT: "
    f"{len(aligned_ids):,}"
)

common_test_ids = candidate_ids.intersection(
    aligned_ids
)

print(
    f"Common Source-1 IDs: "
    f"{len(common_test_ids):,}"
)

# ------------------------------------------------
# Save aligned GT
# ------------------------------------------------

ALIGNED_GT_PATH = os.path.join(
    BASE_PATH,
    "blocking",
    "candidates",
    "ground_truth_aligned_10k.tsv"
)

aligned_gt.to_csv(
    ALIGNED_GT_PATH,
    sep="\t",
    index=False
)

print("\nAligned ground truth saved to:")

print(ALIGNED_GT_PATH)

# ------------------------------------------------
# Final
# ------------------------------------------------

print("\n" + "=" * 70)
print("CELL 27 COMPLETE")
print("=" * 70)

======================================================================
CELL 27 - GROUND TRUTH ALIGNMENT
======================================================================

Loading Source-1...
Source-1 test IDs: 10,000

Loading ground truth...
Total ground-truth rows: 2,206,821

Ground-truth rows matching our Source-1 test set: 10,000
Source-1 IDs without ground truth: 0

======================================================================
ALIGNED GROUND-TRUTH SAMPLE
======================================================================

     source1_entity_id                                 matched_entity_ids
128       S1-424976769              S2-18126063,S3-443109567,S3-296472077
382       S1-874660306                          S2-279857860,S3-289365741
748       S1-539879230  S2-83796020,S3-945547250,S3-127246506,S3-11765...
795       S1-840168502                                                NaN
827       S1-716830359  S2-795817041,S2-306163710,S3-762649005,S3-7375...
999       S1-610149670  S2-601177655,S2-809918482,S3-588852284,S3-3395...
1310      S1-210849781  S2-562117280,S2-845708664,S2-820221567,S3-6499...
1371      S1-844896591                           S2-362218588,S3-11966366
1514      S1-109593962             S2-199917158,S3-118565228,S3-523567654
1795      S1-117525650                                       S3-230664101

======================================================================
CANDIDATE / GROUND TRUTH ALIGNMENT
======================================================================
Source-1 IDs in candidates: 6,609
Source-1 IDs in aligned GT: 10,000
Common Source-1 IDs: 6,609

Aligned ground truth saved to:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ground_truth_aligned_10k.tsv

======================================================================
CELL 27 COMPLETE
======================================================================

In [ ]:
# ============================================
# CELL 28 - CORRECT BLOCKING RECALL
# ============================================

import pandas as pd
import os

BASE_PATH = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource"

CANDIDATE_PATH = os.path.join(
    BASE_PATH,
    "blocking",
    "candidates",
    "candidate_test_10k.tsv"
)

ALIGNED_GT_PATH = os.path.join(
    BASE_PATH,
    "blocking",
    "candidates",
    "ground_truth_aligned_10k.tsv"
)

print("=" * 70)
print("CORRECT BLOCKING RECALL VALIDATION")
print("=" * 70)

# ------------------------------------------------
# Load candidates
# ------------------------------------------------

print("\nLoading candidates...")

candidates = pd.read_csv(
    CANDIDATE_PATH,
    sep="\t",
    dtype=str
)

candidates = candidates.drop_duplicates(
    subset=[
        "source1_entity_id",
        "candidate_entity_id"
    ]
)

print(
    f"Unique candidate pairs: "
    f"{len(candidates):,}"
)

# ------------------------------------------------
# Load aligned ground truth
# ------------------------------------------------

print("\nLoading aligned ground truth...")

gt = pd.read_csv(
    ALIGNED_GT_PATH,
    sep="\t",
    dtype=str
)

print(
    f"Ground-truth records: "
    f"{len(gt):,}"
)

# ------------------------------------------------
# Build candidate lookup
# ------------------------------------------------

candidate_pairs = set(
    zip(
        candidates["source1_entity_id"],
        candidates["candidate_entity_id"]
    )
)

print(
    f"Candidate lookup pairs: "
    f"{len(candidate_pairs):,}"
)

# ------------------------------------------------
# Calculate recall
# ------------------------------------------------

total_positive_pairs = 0
captured_positive_pairs = 0

records_with_match = 0
records_with_captured_match = 0

records_with_no_candidates = 0

for _, row in gt.iterrows():

    source1_id = str(
        row["source1_entity_id"]
    ).strip()

    matched_ids = row["matched_entity_ids"]

    # --------------------------------------------
    # No ground-truth match
    # --------------------------------------------

    if pd.isna(matched_ids):

        continue

    matched_ids = str(
        matched_ids
    ).strip()

    if matched_ids == "":

        continue

    matched_list = [
        x.strip()
        for x in matched_ids.split(",")
        if x.strip()
    ]

    if len(matched_list) == 0:

        continue

    records_with_match += 1

    # --------------------------------------------
    # Check candidates for this Source-1
    # --------------------------------------------

    record_has_candidate = False
    record_captured = False

    for target_id in matched_list:

        total_positive_pairs += 1

        pair = (
            source1_id,
            target_id
        )

        if pair in candidate_pairs:

            captured_positive_pairs += 1
            record_captured = True

        # Candidate existence check
        if pair in candidate_pairs:

            record_has_candidate = True

    if record_captured:

        records_with_captured_match += 1

    # --------------------------------------------
    # Count records with zero candidates
    # --------------------------------------------

    source_candidates = candidates[
        candidates["source1_entity_id"] == source1_id
    ]

    if len(source_candidates) == 0:

        records_with_no_candidates += 1


# ------------------------------------------------
# Recall calculations
# ------------------------------------------------

if total_positive_pairs > 0:

    pair_recall = (
        captured_positive_pairs /
        total_positive_pairs
    ) * 100

else:

    pair_recall = 0.0


if records_with_match > 0:

    record_recall = (
        records_with_captured_match /
        records_with_match
    ) * 100

else:

    record_recall = 0.0


# ------------------------------------------------
# Results
# ------------------------------------------------

print("\n" + "=" * 70)
print("BLOCKING RECALL RESULTS")
print("=" * 70)

print(
    f"\nGround-truth positive pairs : "
    f"{total_positive_pairs:,}"
)

print(
    f"Captured positive pairs     : "
    f"{captured_positive_pairs:,}"
)

print(
    f"Missed positive pairs       : "
    f"{total_positive_pairs - captured_positive_pairs:,}"
)

print(
    f"\nPair-level blocking recall  : "
    f"{pair_recall:.2f}%"
)

print(
    f"\nRecords with >=1 true match : "
    f"{records_with_match:,}"
)

print(
    f"Records with >=1 captured   : "
    f"{records_with_captured_match:,}"
)

print(
    f"Records with no candidates  : "
    f"{records_with_no_candidates:,}"
)

print(
    f"\nRecord-level blocking recall: "
    f"{record_recall:.2f}%"
)

print("\n" + "=" * 70)
print("CELL 28 COMPLETE")
print("=" * 70)

======================================================================
CORRECT BLOCKING RECALL VALIDATION
======================================================================

Loading candidates...
Unique candidate pairs: 131,185

Loading aligned ground truth...
Ground-truth records: 10,000
Candidate lookup pairs: 131,185

======================================================================
BLOCKING RECALL RESULTS
======================================================================

Ground-truth positive pairs : 34,752
Captured positive pairs     : 2,860
Missed positive pairs       : 31,892

Pair-level blocking recall  : 8.23%

Records with >=1 true match : 9,440
Records with >=1 captured   : 978
Records with no candidates  : 3,189

Record-level blocking recall: 10.36%

======================================================================
CELL 28 COMPLETE
======================================================================

In [ ]:
import sqlite3
import os
import time

DB_PATH = "/content/blocking_lookup.db"

print("=" * 70)
print("CELL 29 - RESTORING BLOCK FREQUENCY TABLES")
print("=" * 70)

conn = sqlite3.connect(DB_PATH)
conn.execute("PRAGMA busy_timeout = 60000")

# ------------------------------------------------------------
# CHECK EXISTING TABLES
# ------------------------------------------------------------
tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table'
    ORDER BY name
    """,
    conn
)

print("\nExisting tables:")
print(tables)

# ------------------------------------------------------------
# SOURCE-2 FREQUENCY
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("SOURCE-2 BLOCK FREQUENCY")
print("=" * 70)

start = time.time()

conn.execute("""
DROP TABLE IF EXISTS source2_block_frequency
""")

conn.execute("""
CREATE TABLE source2_block_frequency AS
SELECT
    block_key,
    COUNT(*) AS block_size
FROM source2_blocks
GROUP BY block_key
""")

conn.commit()

print(
    f"Source-2 frequency table created in "
    f"{time.time() - start:.2f} seconds."
)

# ------------------------------------------------------------
# SOURCE-3 FREQUENCY
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("SOURCE-3 BLOCK FREQUENCY")
print("=" * 70)

start = time.time()

conn.execute("""
DROP TABLE IF EXISTS source3_block_frequency
""")

conn.execute("""
CREATE TABLE source3_block_frequency AS
SELECT
    block_key,
    COUNT(*) AS block_size
FROM source3_blocks
GROUP BY block_key
""")

conn.commit()

print(
    f"Source-3 frequency table created in "
    f"{time.time() - start:.2f} seconds."
)

# ------------------------------------------------------------
# CREATE INDEXES
# ------------------------------------------------------------
print("\nCreating frequency indexes...")

conn.execute("""
CREATE INDEX IF NOT EXISTS idx_source2_freq_block
ON source2_block_frequency(block_key)
""")

conn.execute("""
CREATE INDEX IF NOT EXISTS idx_source3_freq_block
ON source3_block_frequency(block_key)
""")

conn.commit()

# ------------------------------------------------------------
# VERIFY
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("VERIFYING FREQUENCY TABLES")
print("=" * 70)

for table in [
    "source2_block_frequency",
    "source3_block_frequency"
]:
    exists = conn.execute(
        """
        SELECT COUNT(*)
        FROM sqlite_master
        WHERE type='table' AND name=?
        """,
        (table,)
    ).fetchone()[0]

    count = conn.execute(
        f"SELECT COUNT(*) FROM {table}"
    ).fetchone()[0]

    print(f"\n{table}")
    print("Exists:", "YES" if exists else "NO")
    print("Rows:", f"{count:,}")

conn.close()

print("\n" + "=" * 70)
print("CELL 29 COMPLETE")
print("=" * 70)

======================================================================
CELL 29 - RESTORING BLOCK FREQUENCY TABLES
======================================================================

Existing tables:
                   name
0  source2_block_counts
1        source2_blocks
2  source3_block_counts
3        source3_blocks

======================================================================
SOURCE-2 BLOCK FREQUENCY
======================================================================
Source-2 frequency table created in 1.26 seconds.

======================================================================
SOURCE-3 BLOCK FREQUENCY
======================================================================
Source-3 frequency table created in 1.42 seconds.

Creating frequency indexes...

======================================================================
VERIFYING FREQUENCY TABLES
======================================================================

source2_block_frequency
Exists: YES
Rows: 796,214

source3_block_frequency
Exists: YES
Rows: 857,298

======================================================================
CELL 29 COMPLETE
======================================================================

In [ ]:
import os
import re
import sqlite3
import pandas as pd
import time

print("=" * 70)
print("CELL 30 - SAFE CANDIDATE GENERATION")
print("=" * 70)

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------
BASE_PATH = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource"

SOURCE1_PATH = os.path.join(
    BASE_PATH,
    "processed_data",
    "cleaned_train_source1.tsv"
)

TOKENS_PATH = os.path.join(
    BASE_PATH,
    "blocking",
    "useful_tokens.txt"
)

DB_PATH = "/content/blocking_lookup.db"

CANDIDATE_PATH = os.path.join(
    BASE_PATH,
    "blocking",
    "candidates",
    "candidate_test_10k_v2.tsv"
)

# ------------------------------------------------------------
# SETTINGS
# ------------------------------------------------------------
TEST_ROWS = 10_000
MAX_BLOCK_SIZE = 20

print("\nSource-1:")
print(SOURCE1_PATH)

print("\nSQLite:")
print(DB_PATH)

print("\nMaximum block size:", MAX_BLOCK_SIZE)

# ------------------------------------------------------------
# CHECK FILES
# ------------------------------------------------------------
for path in [SOURCE1_PATH, TOKENS_PATH, DB_PATH]:

    if not os.path.exists(path):
        raise FileNotFoundError(
            f"\nRequired file not found:\n{path}"
        )

print("\nAll required files found.")

# ------------------------------------------------------------
# LOAD USEFUL TOKENS
# ------------------------------------------------------------
with open(TOKENS_PATH, "r", encoding="utf-8") as f:
    useful_tokens = set(
        line.strip()
        for line in f
        if line.strip()
    )

print("\nUseful tokens loaded:", f"{len(useful_tokens):,}")

# ------------------------------------------------------------
# LOAD SOURCE-1 TEST DATA
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("LOADING SOURCE-1 TEST DATA")
print("=" * 70)

source1 = pd.read_csv(
    SOURCE1_PATH,
    sep="\t",
    nrows=TEST_ROWS,
    dtype=str,
    keep_default_na=False
)

print("Source-1 rows:", f"{len(source1):,}")
print("Columns:", list(source1.columns))

# ------------------------------------------------------------
# TOKENIZER
# ------------------------------------------------------------
def get_tokens(text):
    if not text:
        return []

    text = str(text).lower()

    tokens = re.findall(
        r"[a-z0-9]+",
        text
    )

    return [
        token
        for token in tokens
        if token in useful_tokens
    ]


def get_block_keys(row):
    country = str(row["country"]).strip().lower()

    if not country:
        return set()

    keys = set()

    # Business name
    for token in get_tokens(row["business_name"]):
        keys.add(f"{country}|{token}")

    # Business address
    for token in get_tokens(row["business_address"]):
        keys.add(f"{country}|{token}")

    return keys


# ------------------------------------------------------------
# CONNECT SQLITE
# ------------------------------------------------------------
print("\nConnecting SQLite...")

conn = sqlite3.connect(
    DB_PATH,
    timeout=60
)

conn.execute("PRAGMA busy_timeout = 60000")

# ------------------------------------------------------------
# VERIFY FREQUENCY TABLES
# ------------------------------------------------------------
required_tables = [
    "source2_blocks",
    "source3_blocks",
    "source2_block_frequency",
    "source3_block_frequency"
]

print("\nChecking database tables...")

for table in required_tables:

    result = conn.execute(
        """
        SELECT COUNT(*)
        FROM sqlite_master
        WHERE type='table'
        AND name=?
        """,
        (table,)
    ).fetchone()[0]

    if result == 0:
        conn.close()
        raise RuntimeError(
            f"Missing SQLite table: {table}"
        )

    print("OK:", table)

# ------------------------------------------------------------
# PREPARE OUTPUT
# ------------------------------------------------------------
os.makedirs(
    os.path.dirname(CANDIDATE_PATH),
    exist_ok=True
)

if os.path.exists(CANDIDATE_PATH):
    os.remove(CANDIDATE_PATH)

# ------------------------------------------------------------
# CANDIDATE GENERATION
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("GENERATING CANDIDATES")
print("=" * 70)

start_time = time.time()

total_candidates = 0
processed = 0

with open(
    CANDIDATE_PATH,
    "w",
    encoding="utf-8"
) as out:

    out.write(
        "source1_entity_id\t"
        "candidate_entity_id\t"
        "candidate_source\t"
        "block_key\n"
    )

    for _, row in source1.iterrows():

        source1_id = row["entity_id"]

        block_keys = get_block_keys(row)

        # ----------------------------------------------------
        # SOURCE 2
        # ----------------------------------------------------
        for block_key in block_keys:

            block_size = conn.execute(
                """
                SELECT block_size
                FROM source2_block_frequency
                WHERE block_key = ?
                """,
                (block_key,)
            ).fetchone()

            if block_size is None:
                continue

            if block_size[0] > MAX_BLOCK_SIZE:
                continue

            candidates = conn.execute(
                """
                SELECT entity_id
                FROM source2_blocks
                WHERE block_key = ?
                """,
                (block_key,)
            )

            for (candidate_id,) in candidates:

                out.write(
                    f"{source1_id}\t"
                    f"{candidate_id}\t"
                    f"source2\t"
                    f"{block_key}\n"
                )

                total_candidates += 1

        # ----------------------------------------------------
        # SOURCE 3
        # ----------------------------------------------------
        for block_key in block_keys:

            block_size = conn.execute(
                """
                SELECT block_size
                FROM source3_block_frequency
                WHERE block_key = ?
                """,
                (block_key,)
            ).fetchone()

            if block_size is None:
                continue

            if block_size[0] > MAX_BLOCK_SIZE:
                continue

            candidates = conn.execute(
                """
                SELECT entity_id
                FROM source3_blocks
                WHERE block_key = ?
                """,
                (block_key,)
            )

            for (candidate_id,) in candidates:

                out.write(
                    f"{source1_id}\t"
                    f"{candidate_id}\t"
                    f"source3\t"
                    f"{block_key}\n"
                )

                total_candidates += 1

        processed += 1

        if processed % 1000 == 0:
            elapsed = time.time() - start_time

            print(
                f"Processed: {processed:,} | "
                f"Candidates: {total_candidates:,} | "
                f"Time: {elapsed/60:.2f} min"
            )

conn.close()

# ------------------------------------------------------------
# RESULT
# ------------------------------------------------------------
elapsed = time.time() - start_time

print("\n" + "=" * 70)
print("CANDIDATE GENERATION COMPLETE")
print("=" * 70)

print(
    "\nSource-1 records:",
    f"{processed:,}"
)

print(
    "Candidate rows:",
    f"{total_candidates:,}"
)

print(
    "Average candidates per Source-1:",
    f"{total_candidates / processed:.2f}"
)

print(
    "Time taken:",
    f"{elapsed/60:.2f} minutes"
)

print("\nCandidate file:")
print(CANDIDATE_PATH)

print("\n" + "=" * 70)
print("CELL 30 COMPLETE")
print("=" * 70)

======================================================================
CELL 30 - SAFE CANDIDATE GENERATION
======================================================================

Source-1:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/processed_data/cleaned_train_source1.tsv

SQLite:
/content/blocking_lookup.db

Maximum block size: 20

All required files found.

Useful tokens loaded: 1,410,894

======================================================================
LOADING SOURCE-1 TEST DATA
======================================================================
Source-1 rows: 10,000
Columns: ['entity_id', 'business_name', 'business_address', 'country']

Connecting SQLite...

Checking database tables...
OK: source2_blocks
OK: source3_blocks
OK: source2_block_frequency
OK: source3_block_frequency

======================================================================
GENERATING CANDIDATES
======================================================================
Processed: 1,000 | Candidates: 13,196 | Time: 0.01 min
Processed: 2,000 | Candidates: 26,727 | Time: 0.02 min
Processed: 3,000 | Candidates: 40,340 | Time: 0.02 min
Processed: 4,000 | Candidates: 53,535 | Time: 0.03 min
Processed: 5,000 | Candidates: 66,782 | Time: 0.04 min
Processed: 6,000 | Candidates: 79,098 | Time: 0.05 min
Processed: 7,000 | Candidates: 91,674 | Time: 0.06 min
Processed: 8,000 | Candidates: 104,505 | Time: 0.07 min
Processed: 9,000 | Candidates: 117,570 | Time: 0.09 min
Processed: 10,000 | Candidates: 131,745 | Time: 0.10 min

======================================================================
CANDIDATE GENERATION COMPLETE
======================================================================

Source-1 records: 10,000
Candidate rows: 131,745
Average candidates per Source-1: 13.17
Time taken: 0.10 minutes

Candidate file:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/candidate_test_10k_v2.tsv

======================================================================
CELL 30 COMPLETE
======================================================================

In [ ]:
import os
import pandas as pd

print("=" * 70)
print("CELL 31 - CANDIDATE STRUCTURE VERIFICATION")
print("=" * 70)

CANDIDATE_PATH = (
    "/content/drive/MyDrive/"
    "6ab10eb3b23ba_student_resource/"
    "student_resource/blocking/candidates/"
    "candidate_test_10k_v2.tsv"
)

print("\nCandidate file:")
print(CANDIDATE_PATH)

if not os.path.exists(CANDIDATE_PATH):
    raise FileNotFoundError(
        f"Candidate file not found:\n{CANDIDATE_PATH}"
    )

print("\nSTATUS: OK")

# Read only sample
candidate_sample = pd.read_csv(
    CANDIDATE_PATH,
    sep="\t",
    nrows=20,
    dtype=str
)

print("\nCandidate columns:")
print(list(candidate_sample.columns))

print("\nCandidate sample:")
print(candidate_sample.to_string(index=False))

# Full row count without loading entire file
row_count = 0

with open(CANDIDATE_PATH, "r", encoding="utf-8") as f:
    next(f)  # skip header

    for _ in f:
        row_count += 1

print("\nTotal candidate rows:", f"{row_count:,}")

print("\n" + "=" * 70)
print("CELL 31 COMPLETE")
print("=" * 70)

======================================================================
CELL 31 - CANDIDATE STRUCTURE VERIFICATION
======================================================================

Candidate file:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/candidate_test_10k_v2.tsv

STATUS: OK

Candidate columns:
['source1_entity_id', 'candidate_entity_id', 'candidate_source', 'block_key']

Candidate sample:
source1_entity_id candidate_entity_id candidate_source      block_key
     S1-925783039        S2-202974731          source2 us|westchester
     S1-925783039        S2-393846896          source2 us|westchester
     S1-925783039        S2-621757655          source2        us|1795
     S1-925783039        S2-412342728          source2        us|1795
     S1-925783039        S2-807577508          source2        us|1795
     S1-925783039        S2-137172441          source2        us|1795
     S1-925783039         S3-59852150          source3 us|westchester
     S1-925783039         S3-20472883          source3 us|westchester
     S1-925783039        S3-112073915          source3 us|westchester
     S1-925783039        S3-880261982          source3        us|1795
     S1-925783039        S3-128905334          source3        us|1795
     S1-925783039        S3-646888144          source3        us|1795
     S1-925783039        S3-143544733          source3        us|1795
     S1-925783039        S3-793054764          source3        us|1795
     S1-925783039        S3-753203621          source3        us|1795
     S1-773889195        S2-738816767          source2   us|tahlequah
     S1-773889195        S2-720004238          source2   us|tahlequah
     S1-773889195        S2-390442623          source2   us|tahlequah
     S1-773889195        S2-740666011          source2   us|tahlequah
     S1-773889195        S2-148957721          source2   us|tahlequah

Total candidate rows: 131,745

======================================================================
CELL 31 COMPLETE
======================================================================

In [ ]:
import os
import pandas as pd

print("=" * 70)
print("CELL 32 - BLOCKING RECALL VALIDATION")
print("=" * 70)

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------
CANDIDATE_PATH = (
    "/content/drive/MyDrive/"
    "6ab10eb3b23ba_student_resource/"
    "student_resource/blocking/candidates/"
    "candidate_test_10k_v2.tsv"
)

GROUND_TRUTH_PATH = (
    "/content/drive/MyDrive/"
    "6ab10eb3b23ba_student_resource/"
    "student_resource/blocking/candidates/"
    "ground_truth_aligned_10k.tsv"
)

# ------------------------------------------------------------
# CHECK FILES
# ------------------------------------------------------------
print("\nChecking files...")

if not os.path.exists(CANDIDATE_PATH):
    raise FileNotFoundError(
        f"Candidate file not found:\n{CANDIDATE_PATH}"
    )

if not os.path.exists(GROUND_TRUTH_PATH):
    raise FileNotFoundError(
        f"Aligned ground truth not found:\n{GROUND_TRUTH_PATH}"
    )

print("Candidate file: OK")
print("Ground truth: OK")

# ------------------------------------------------------------
# LOAD CANDIDATES
# ------------------------------------------------------------
print("\nLoading candidate file...")

candidates = pd.read_csv(
    CANDIDATE_PATH,
    sep="\t",
    dtype=str
)

print(
    "Candidate rows:",
    f"{len(candidates):,}"
)

# Remove duplicate candidate pairs
candidate_pairs = set(
    zip(
        candidates["source1_entity_id"],
        candidates["candidate_entity_id"]
    )
)

print(
    "Unique candidate pairs:",
    f"{len(candidate_pairs):,}"
)

# ------------------------------------------------------------
# LOAD ALIGNED GROUND TRUTH
# ------------------------------------------------------------
print("\nLoading aligned ground truth...")

gt = pd.read_csv(
    GROUND_TRUTH_PATH,
    sep="\t",
    dtype=str
)

print(
    "Ground-truth records:",
    f"{len(gt):,}"
)

print(
    "Ground-truth columns:",
    list(gt.columns)
)

# ------------------------------------------------------------
# BUILD TRUE POSITIVE PAIRS
# ------------------------------------------------------------
print("\nBuilding ground-truth positive pairs...")

true_pairs = set()

for _, row in gt.iterrows():

    source1_id = row["source1_entity_id"]
    matched = row["matched_entity_ids"]

    if pd.isna(matched):
        continue

    matched = str(matched).strip()

    if not matched:
        continue

    for candidate_id in matched.split(","):

        candidate_id = candidate_id.strip()

        if candidate_id:
            true_pairs.add(
                (source1_id, candidate_id)
            )

print(
    "Ground-truth positive pairs:",
    f"{len(true_pairs):,}"
)

# ------------------------------------------------------------
# CALCULATE CAPTURE
# ------------------------------------------------------------
captured_pairs = true_pairs.intersection(
    candidate_pairs
)

missed_pairs = true_pairs - candidate_pairs

# ------------------------------------------------------------
# PAIR-LEVEL RECALL
# ------------------------------------------------------------
pair_recall = (
    len(captured_pairs) / len(true_pairs) * 100
    if true_pairs
    else 0
)

print("\n" + "=" * 70)
print("PAIR-LEVEL RECALL")
print("=" * 70)

print(
    "True positive pairs :",
    f"{len(true_pairs):,}"
)

print(
    "Captured pairs      :",
    f"{len(captured_pairs):,}"
)

print(
    "Missed pairs        :",
    f"{len(missed_pairs):,}"
)

print(
    "Blocking recall     :",
    f"{pair_recall:.2f}%"
)

# ------------------------------------------------------------
# RECORD-LEVEL RECALL
# ------------------------------------------------------------
gt_source_ids = set(
    gt["source1_entity_id"].dropna()
)

matched_source_ids = set(
    source1_id
    for source1_id, _ in true_pairs
)

captured_source_ids = set(
    source1_id
    for source1_id, _ in captured_pairs
)

records_with_match = len(matched_source_ids)

records_captured = len(
    captured_source_ids.intersection(
        matched_source_ids
    )
)

records_no_candidate = len(
    matched_source_ids - captured_source_ids
)

record_recall = (
    records_captured / records_with_match * 100
    if records_with_match
    else 0
)

print("\n" + "=" * 70)
print("RECORD-LEVEL RECALL")
print("=" * 70)

print(
    "Records with >=1 true match :",
    f"{records_with_match:,}"
)

print(
    "Records with >=1 captured   :",
    f"{records_captured:,}"
)

print(
    "Records with no capture     :",
    f"{records_no_candidate:,}"
)

print(
    "Record-level recall         :",
    f"{record_recall:.2f}%"
)

# ------------------------------------------------------------
# SOURCE DISTRIBUTION
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("CAPTURED TRUE MATCH SOURCE")
print("=" * 70)

captured_ids = [
    candidate_id
    for _, candidate_id in captured_pairs
]

source2_count = sum(
    x.startswith("S2-")
    for x in captured_ids
)

source3_count = sum(
    x.startswith("S3-")
    for x in captured_ids
)

print("Captured Source-2 matches:", f"{source2_count:,}")
print("Captured Source-3 matches:", f"{source3_count:,}")

print("\n" + "=" * 70)
print("CELL 32 COMPLETE")
print("=" * 70)

======================================================================
CELL 32 - BLOCKING RECALL VALIDATION
======================================================================

Checking files...
Candidate file: OK
Ground truth: OK

Loading candidate file...
Candidate rows: 131,745
Unique candidate pairs: 131,185

Loading aligned ground truth...
Ground-truth records: 10,000
Ground-truth columns: ['source1_entity_id', 'matched_entity_ids']

Building ground-truth positive pairs...
Ground-truth positive pairs: 34,752

======================================================================
PAIR-LEVEL RECALL
======================================================================
True positive pairs : 34,752
Captured pairs      : 2,860
Missed pairs        : 31,892
Blocking recall     : 8.23%

======================================================================
RECORD-LEVEL RECALL
======================================================================
Records with >=1 true match : 9,440
Records with >=1 captured   : 978
Records with no capture     : 8,462
Record-level recall         : 10.36%

======================================================================
CAPTURED TRUE MATCH SOURCE
======================================================================
Captured Source-2 matches: 1,423
Captured Source-3 matches: 1,437

======================================================================
CELL 32 COMPLETE
======================================================================

In [ ]:
import os
import sqlite3
import pandas as pd
import re

print("=" * 70)
print("CELL 33 - MISSED MATCH DIAGNOSIS")
print("=" * 70)

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------
BASE_PATH = (
    "/content/drive/MyDrive/"
    "6ab10eb3b23ba_student_resource/"
    "student_resource"
)

SOURCE1_PATH = os.path.join(
    BASE_PATH,
    "processed_data",
    "cleaned_train_source1.tsv"
)

SOURCE2_PATH = os.path.join(
    BASE_PATH,
    "processed_data",
    "cleaned_train_source2.tsv"
)

SOURCE3_PATH = os.path.join(
    BASE_PATH,
    "processed_data",
    "cleaned_train_source3.tsv"
)

GT_PATH = os.path.join(
    BASE_PATH,
    "blocking",
    "candidates",
    "ground_truth_aligned_10k.tsv"
)

CANDIDATE_PATH = os.path.join(
    BASE_PATH,
    "blocking",
    "candidates",
    "candidate_test_10k_v2.tsv"
)

DB_PATH = "/content/blocking_lookup.db"

# ------------------------------------------------------------
# LOAD SOURCE-1 TEST DATA
# ------------------------------------------------------------
print("\nLoading Source-1 test data...")

source1 = pd.read_csv(
    SOURCE1_PATH,
    sep="\t",
    nrows=10_000,
    dtype=str,
    keep_default_na=False
)

source1_map = source1.set_index("entity_id").to_dict("index")

print("Source-1 records:", f"{len(source1):,}")

# ------------------------------------------------------------
# LOAD GROUND TRUTH
# ------------------------------------------------------------
print("\nLoading aligned ground truth...")

gt = pd.read_csv(
    GT_PATH,
    sep="\t",
    dtype=str
)

# ------------------------------------------------------------
# LOAD CANDIDATES
# ------------------------------------------------------------
print("Loading candidates...")

candidates = pd.read_csv(
    CANDIDATE_PATH,
    sep="\t",
    dtype=str
)

candidate_pairs = set(
    zip(
        candidates["source1_entity_id"],
        candidates["candidate_entity_id"]
    )
)

# ------------------------------------------------------------
# FIND MISSED TRUE PAIRS
# ------------------------------------------------------------
print("\nFinding missed true matches...")

missed_pairs = []

for _, row in gt.iterrows():

    s1_id = row["source1_entity_id"]
    matched = row["matched_entity_ids"]

    if pd.isna(matched):
        continue

    matched = str(matched).strip()

    if not matched:
        continue

    for target_id in matched.split(","):

        target_id = target_id.strip()

        if not target_id:
            continue

        pair = (s1_id, target_id)

        if pair not in candidate_pairs:
            missed_pairs.append(pair)

print(
    "Missed true pairs:",
    f"{len(missed_pairs):,}"
)

# ------------------------------------------------------------
# TAKE SMALL SAMPLE FOR DIAGNOSIS
# ------------------------------------------------------------
sample_pairs = missed_pairs[:100]

print(
    "Diagnosing first:",
    len(sample_pairs),
    "missed pairs"
)

# ------------------------------------------------------------
# SQLITE CONNECTION
# ------------------------------------------------------------
print("\nConnecting SQLite...")

conn = sqlite3.connect(
    DB_PATH,
    timeout=60
)

conn.execute("PRAGMA busy_timeout = 60000")

# ------------------------------------------------------------
# TOKEN FUNCTION
# ------------------------------------------------------------
def tokenize(text):

    if text is None:
        return set()

    text = str(text).lower()

    return set(
        re.findall(
            r"[a-z0-9]+",
            text
        )
    )

# ------------------------------------------------------------
# DIAGNOSE
# ------------------------------------------------------------
results = []

for s1_id, target_id in sample_pairs:

    # --------------------------------------------------------
    # SOURCE-1 DATA
    # --------------------------------------------------------
    s1 = source1_map.get(s1_id)

    if s1 is None:
        results.append({
            "source1_id": s1_id,
            "target_id": target_id,
            "target_source": (
                "source2"
                if target_id.startswith("S2-")
                else "source3"
            ),
            "status": "SOURCE1_NOT_FOUND",
            "common_tokens": "",
            "common_count": 0,
            "block_sizes": ""
        })
        continue

    # --------------------------------------------------------
    # TARGET SOURCE
    # --------------------------------------------------------
    if target_id.startswith("S2-"):
        table = "source2_blocks"
        freq_table = "source2_block_frequency"
        target_source = "source2"

    elif target_id.startswith("S3-"):
        table = "source3_blocks"
        freq_table = "source3_block_frequency"
        target_source = "source3"

    else:
        results.append({
            "source1_id": s1_id,
            "target_id": target_id,
            "target_source": "unknown",
            "status": "INVALID_TARGET_ID",
            "common_tokens": "",
            "common_count": 0,
            "block_sizes": ""
        })
        continue

    # --------------------------------------------------------
    # GET TARGET BLOCK KEYS
    # --------------------------------------------------------
    target_rows = conn.execute(
        f"""
        SELECT block_key
        FROM {table}
        WHERE entity_id = ?
        """,
        (target_id,)
    ).fetchall()

    target_keys = set(
        row[0]
        for row in target_rows
    )

    # --------------------------------------------------------
    # SOURCE-1 RAW TOKENS
    # --------------------------------------------------------
    s1_tokens = (
        tokenize(s1["business_name"])
        |
        tokenize(s1["business_address"])
    )

    country = str(
        s1["country"]
    ).strip().lower()

    # Expected blocking keys from Source-1
    s1_keys = set()

    for token in s1_tokens:
        s1_keys.add(
            f"{country}|{token}"
        )

    # --------------------------------------------------------
    # COMMON BLOCK KEYS
    # --------------------------------------------------------
    common_keys = s1_keys.intersection(
        target_keys
    )

    # --------------------------------------------------------
    # BLOCK SIZES
    # --------------------------------------------------------
    block_sizes = []

    for key in common_keys:

        row = conn.execute(
            f"""
            SELECT block_size
            FROM {freq_table}
            WHERE block_key = ?
            """,
            (key,)
        ).fetchone()

        if row:
            block_sizes.append(
                f"{key}:{row[0]}"
            )

    # --------------------------------------------------------
    # STATUS
    # --------------------------------------------------------
    if len(common_keys) == 0:

        status = "NO_COMMON_BLOCK"

    elif any(
        int(x.split(":")[-1]) <= 20
        for x in block_sizes
    ):

        status = "SHOULD_BE_CAPTURED"

    else:

        status = "BLOCK_TOO_LARGE"

    results.append({
        "source1_id": s1_id,
        "target_id": target_id,
        "target_source": target_source,
        "status": status,
        "common_tokens": "|".join(
            sorted(common_keys)
        ),
        "common_count": len(common_keys),
        "block_sizes": "|".join(
            block_sizes
        )
    })

conn.close()

# ------------------------------------------------------------
# RESULTS
# ------------------------------------------------------------
diagnosis = pd.DataFrame(results)

print("\n" + "=" * 70)
print("DIAGNOSIS SUMMARY")
print("=" * 70)

print(
    diagnosis["status"].value_counts(
        dropna=False
    )
)

print("\n" + "=" * 70)
print("SAMPLE DIAGNOSIS")
print("=" * 70)

print(
    diagnosis.head(30).to_string(
        index=False
    )
)

# ------------------------------------------------------------
# SAVE
# ------------------------------------------------------------
OUTPUT_PATH = os.path.join(
    BASE_PATH,
    "blocking",
    "candidates",
    "missed_match_diagnosis_100.tsv"
)

diagnosis.to_csv(
    OUTPUT_PATH,
    sep="\t",
    index=False
)

print("\nDiagnosis saved to:")
print(OUTPUT_PATH)

print("\n" + "=" * 70)
print("CELL 33 COMPLETE")
print("=" * 70)

======================================================================
CELL 33 - MISSED MATCH DIAGNOSIS
======================================================================

Loading Source-1 test data...
Source-1 records: 10,000

Loading aligned ground truth...
Loading candidates...

Finding missed true matches...
Missed true pairs: 31,892
Diagnosing first: 100 missed pairs

Connecting SQLite...

======================================================================
DIAGNOSIS SUMMARY
======================================================================
status
BLOCK_TOO_LARGE    71
NO_COMMON_BLOCK    29
Name: count, dtype: int64

======================================================================
SAMPLE DIAGNOSIS
======================================================================
  source1_id    target_id target_source          status                      common_tokens  common_count                                       block_sizes
S1-424976769  S2-18126063       source2 BLOCK_TOO_LARGE                     india|projects             1                               india|projects:9535
S1-424976769 S3-443109567       source3 BLOCK_TOO_LARGE                     india|projects             1                              india|projects:13069
S1-424976769 S3-296472077       source3 NO_COMMON_BLOCK                                                0
S1-874660306 S2-279857860       source2 BLOCK_TOO_LARGE             us|physical|us|therapy             2                us|physical:13672|us|therapy:14895
S1-874660306 S3-289365741       source3 BLOCK_TOO_LARGE             us|physical|us|therapy             2                us|physical:14265|us|therapy:15439
S1-539879230  S2-83796020       source2 BLOCK_TOO_LARGE                          us|novent             1                                     us|novent:119
S1-539879230 S3-945547250       source3 BLOCK_TOO_LARGE                  us|novent|us|pllc             2                       us|novent:126|us|pllc:26549
S1-539879230 S3-127246506       source3 BLOCK_TOO_LARGE                  us|novent|us|pllc             2                       us|novent:126|us|pllc:26549
S1-539879230 S3-117651018       source3 BLOCK_TOO_LARGE                  us|novent|us|pllc             2                       us|novent:126|us|pllc:26549
S1-716830359 S2-795817041       source2 BLOCK_TOO_LARGE us|environmental|us|spicer|us|star             3 us|star:11869|us|spicer:143|us|environmental:8485
S1-716830359 S2-306163710       source2 BLOCK_TOO_LARGE us|environmental|us|spicer|us|star             3 us|star:11869|us|spicer:143|us|environmental:8485
S1-716830359 S3-762649005       source3 BLOCK_TOO_LARGE us|environmental|us|spicer|us|star             3 us|star:12445|us|spicer:139|us|environmental:8777
S1-716830359 S3-737589534       source3 BLOCK_TOO_LARGE us|environmental|us|spicer|us|star             3 us|star:12445|us|spicer:139|us|environmental:8777
S1-610149670 S2-601177655       source2 NO_COMMON_BLOCK                                                0
S1-610149670 S2-809918482       source2 NO_COMMON_BLOCK                                                0
S1-610149670 S3-588852284       source3 NO_COMMON_BLOCK                                                0
S1-610149670 S3-339503285       source3 NO_COMMON_BLOCK                                                0
S1-610149670 S3-744911212       source3 NO_COMMON_BLOCK                                                0
S1-210849781 S2-562117280       source2 BLOCK_TOO_LARGE                         us|urology             1                                  us|urology:10140
S1-210849781 S2-845708664       source2 BLOCK_TOO_LARGE                         us|urology             1                                  us|urology:10140
S1-210849781 S2-820221567       source2 BLOCK_TOO_LARGE                         us|urology             1                                  us|urology:10140
S1-210849781 S3-649907207       source3 BLOCK_TOO_LARGE                         us|urology             1                                  us|urology:10671
S1-210849781 S3-895784814       source3 BLOCK_TOO_LARGE                         us|urology             1                                  us|urology:10671
S1-210849781 S3-210870050       source3 BLOCK_TOO_LARGE                         us|urology             1                                  us|urology:10671
S1-210849781 S3-240268161       source3 BLOCK_TOO_LARGE                         us|urology             1                                  us|urology:10671
S1-844896591 S2-362218588       source2 BLOCK_TOO_LARGE             us|modern|us|packaging             2                 us|packaging:2968|us|modern:10864
S1-844896591  S3-11966366       source3 BLOCK_TOO_LARGE             us|modern|us|packaging             2                 us|packaging:3168|us|modern:11505
S1-109593962 S2-199917158       source2 NO_COMMON_BLOCK                                                0
S1-109593962 S3-118565228       source3 NO_COMMON_BLOCK                                                0
S1-109593962 S3-523567654       source3 BLOCK_TOO_LARGE            india|great|india|impex             2                india|impex:10430|india|great:5320

Diagnosis saved to:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/missed_match_diagnosis_100.tsv

======================================================================
CELL 33 COMPLETE
======================================================================

In [ ]:
# ============================================================
# CELL 34 - CONTROLLED BLOCK SIZE THRESHOLD EXPERIMENT
# ============================================================

import os
import sqlite3
import pandas as pd
import re
import time

print("=" * 70)
print("CELL 34 - BLOCK SIZE THRESHOLD EXPERIMENT")
print("=" * 70)

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------
BASE_PATH = (
    "/content/drive/MyDrive/"
    "6ab10eb3b23ba_student_resource/"
    "student_resource"
)

SOURCE1_PATH = os.path.join(
    BASE_PATH,
    "processed_data",
    "cleaned_train_source1.tsv"
)

GT_PATH = os.path.join(
    BASE_PATH,
    "blocking",
    "candidates",
    "ground_truth_aligned_10k.tsv"
)

DB_PATH = "/content/blocking_lookup.db"

# ------------------------------------------------------------
# SETTINGS
# ------------------------------------------------------------
TEST_ROWS = 10_000

THRESHOLDS = [
    20,
    100,
    500,
    1000
]

# ------------------------------------------------------------
# LOAD SOURCE-1
# ------------------------------------------------------------
print("\nLoading Source-1...")

source1 = pd.read_csv(
    SOURCE1_PATH,
    sep="\t",
    nrows=TEST_ROWS,
    dtype=str,
    keep_default_na=False
)

print(
    "Source-1 records:",
    f"{len(source1):,}"
)

# ------------------------------------------------------------
# LOAD GROUND TRUTH
# ------------------------------------------------------------
print("\nLoading aligned ground truth...")

gt = pd.read_csv(
    GT_PATH,
    sep="\t",
    dtype=str
)

true_pairs = set()

for _, row in gt.iterrows():

    s1_id = row["source1_entity_id"]
    matched = row["matched_entity_ids"]

    if pd.isna(matched):
        continue

    matched = str(matched).strip()

    if not matched:
        continue

    for target_id in matched.split(","):

        target_id = target_id.strip()

        if target_id:
            true_pairs.add(
                (s1_id, target_id)
            )

print(
    "Ground-truth positive pairs:",
    f"{len(true_pairs):,}"
)

# ------------------------------------------------------------
# LOAD SQLITE
# ------------------------------------------------------------
print("\nConnecting SQLite...")

conn = sqlite3.connect(
    DB_PATH,
    timeout=60
)

conn.execute(
    "PRAGMA busy_timeout = 60000"
)

# ------------------------------------------------------------
# TOKEN FUNCTION
# ------------------------------------------------------------
def get_tokens(text):

    if not text:
        return set()

    return set(
        re.findall(
            r"[a-z0-9]+",
            str(text).lower()
        )
    )

# ------------------------------------------------------------
# SOURCE-1 BLOCK KEYS
# ------------------------------------------------------------
print("\nCreating Source-1 blocking keys...")

source1_blocks = {}

for _, row in source1.iterrows():

    s1_id = row["entity_id"]

    country = str(
        row["country"]
    ).strip().lower()

    tokens = (
        get_tokens(row["business_name"])
        |
        get_tokens(row["business_address"])
    )

    keys = set()

    for token in tokens:

        if country:
            keys.add(
                f"{country}|{token}"
            )

    source1_blocks[s1_id] = keys

print(
    "Source-1 blocking keys created:",
    f"{len(source1_blocks):,}"
)

# ------------------------------------------------------------
# EXPERIMENT
# ------------------------------------------------------------
results = []

for threshold in THRESHOLDS:

    print("\n" + "=" * 70)
    print(
        f"TESTING MAX_BLOCK_SIZE = {threshold}"
    )
    print("=" * 70)

    start = time.time()

    candidate_pairs = set()

    processed = 0

    for s1_id, block_keys in source1_blocks.items():

        # ----------------------------------------------------
        # SOURCE 2
        # ----------------------------------------------------
        for block_key in block_keys:

            row = conn.execute(
                """
                SELECT block_size
                FROM source2_block_frequency
                WHERE block_key = ?
                """,
                (block_key,)
            ).fetchone()

            if row is None:
                continue

            if row[0] > threshold:
                continue

            rows = conn.execute(
                """
                SELECT entity_id
                FROM source2_blocks
                WHERE block_key = ?
                """,
                (block_key,)
            )

            for (entity_id,) in rows:

                candidate_pairs.add(
                    (s1_id, entity_id)
                )

        # ----------------------------------------------------
        # SOURCE 3
        # ----------------------------------------------------
        for block_key in block_keys:

            row = conn.execute(
                """
                SELECT block_size
                FROM source3_block_frequency
                WHERE block_key = ?
                """,
                (block_key,)
            ).fetchone()

            if row is None:
                continue

            if row[0] > threshold:
                continue

            rows = conn.execute(
                """
                SELECT entity_id
                FROM source3_blocks
                WHERE block_key = ?
                """,
                (block_key,)
            )

            for (entity_id,) in rows:

                candidate_pairs.add(
                    (s1_id, entity_id)
                )

        processed += 1

        if processed % 2000 == 0:

            print(
                f"Processed: {processed:,} | "
                f"Candidates: {len(candidate_pairs):,}"
            )

    # --------------------------------------------------------
    # RECALL
    # --------------------------------------------------------
    captured = true_pairs.intersection(
        candidate_pairs
    )

    pair_recall = (
        len(captured)
        / len(true_pairs)
        * 100
    )

    true_source1_ids = {
        s1_id
        for s1_id, _ in true_pairs
    }

    captured_source1_ids = {
        s1_id
        for s1_id, _ in captured
    }

    record_recall = (
        len(
            captured_source1_ids.intersection(
                true_source1_ids
            )
        )
        / len(true_source1_ids)
        * 100
    )

    elapsed = time.time() - start

    avg_candidates = (
        len(candidate_pairs)
        / TEST_ROWS
    )

    # --------------------------------------------------------
    # SAVE RESULT
    # --------------------------------------------------------
    results.append({
        "max_block_size": threshold,
        "candidate_pairs": len(candidate_pairs),
        "avg_candidates_per_record": round(
            avg_candidates, 2
        ),
        "true_pairs": len(true_pairs),
        "captured_pairs": len(captured),
        "pair_recall_percent": round(
            pair_recall, 2
        ),
        "record_recall_percent": round(
            record_recall, 2
        ),
        "time_minutes": round(
            elapsed / 60,
            2
        )
    })

    print("\nRESULT:")
    print(
        "Candidate pairs:",
        f"{len(candidate_pairs):,}"
    )
    print(
        "Average candidates/record:",
        f"{avg_candidates:.2f}"
    )
    print(
        "Captured true pairs:",
        f"{len(captured):,}"
    )
    print(
        "Pair recall:",
        f"{pair_recall:.2f}%"
    )
    print(
        "Record recall:",
        f"{record_recall:.2f}%"
    )
    print(
        "Time:",
        f"{elapsed/60:.2f} minutes"
    )

# ------------------------------------------------------------
# CLOSE DATABASE
# ------------------------------------------------------------
conn.close()

# ------------------------------------------------------------
# FINAL COMPARISON TABLE
# ------------------------------------------------------------
results_df = pd.DataFrame(results)

print("\n" + "=" * 70)
print("THRESHOLD EXPERIMENT RESULTS")
print("=" * 70)

print(
    results_df.to_string(
        index=False
    )
)

# ------------------------------------------------------------
# SAVE RESULTS
# ------------------------------------------------------------
OUTPUT_PATH = os.path.join(
    BASE_PATH,
    "blocking",
    "candidates",
    "threshold_experiment_10k.tsv"
)

results_df.to_csv(
    OUTPUT_PATH,
    sep="\t",
    index=False
)

print("\nResults saved to:")
print(OUTPUT_PATH)

print("\n" + "=" * 70)
print("CELL 34 COMPLETE")
print("=" * 70)

======================================================================
CELL 34 - BLOCK SIZE THRESHOLD EXPERIMENT
======================================================================

Loading Source-1...
Source-1 records: 10,000

Loading aligned ground truth...
Ground-truth positive pairs: 34,752

Connecting SQLite...

Creating Source-1 blocking keys...
Source-1 blocking keys created: 10,000

======================================================================
TESTING MAX_BLOCK_SIZE = 20
======================================================================
Processed: 2,000 | Candidates: 26,549
Processed: 4,000 | Candidates: 53,271
Processed: 6,000 | Candidates: 78,745
Processed: 8,000 | Candidates: 104,048
Processed: 10,000 | Candidates: 131,185

RESULT:
Candidate pairs: 131,185
Average candidates/record: 13.12
Captured true pairs: 2,860
Pair recall: 8.23%
Record recall: 10.36%
Time: 0.09 minutes

======================================================================
TESTING MAX_BLOCK_SIZE = 100
======================================================================
Processed: 2,000 | Candidates: 249,501
Processed: 4,000 | Candidates: 491,828
Processed: 6,000 | Candidates: 733,691
Processed: 8,000 | Candidates: 978,237
Processed: 10,000 | Candidates: 1,223,175

RESULT:
Candidate pairs: 1,223,175
Average candidates/record: 122.32
Captured true pairs: 9,288
Pair recall: 26.73%
Record recall: 30.93%
Time: 0.19 minutes

======================================================================
TESTING MAX_BLOCK_SIZE = 500
======================================================================
Processed: 2,000 | Candidates: 1,727,715
Processed: 4,000 | Candidates: 3,445,459
Processed: 6,000 | Candidates: 5,157,002
Processed: 8,000 | Candidates: 6,854,070
Processed: 10,000 | Candidates: 8,548,220

RESULT:
Candidate pairs: 8,548,220
Average candidates/record: 854.82
Captured true pairs: 13,284
Pair recall: 38.23%
Record recall: 43.34%
Time: 0.97 minutes

======================================================================
TESTING MAX_BLOCK_SIZE = 1000
======================================================================
Processed: 2,000 | Candidates: 3,267,145
Processed: 4,000 | Candidates: 6,624,909
Processed: 6,000 | Candidates: 9,941,201
Processed: 8,000 | Candidates: 13,284,479
Processed: 10,000 | Candidates: 16,537,939

RESULT:
Candidate pairs: 16,537,939
Average candidates/record: 1653.79
Captured true pairs: 16,742
Pair recall: 48.18%
Record recall: 56.00%
Time: 1.84 minutes

======================================================================
THRESHOLD EXPERIMENT RESULTS
======================================================================
 max_block_size  candidate_pairs  avg_candidates_per_record  true_pairs  captured_pairs  pair_recall_percent  record_recall_percent  time_minutes
             20           131185                      13.12       34752            2860                 8.23                  10.36          0.09
            100          1223175                     122.32       34752            9288                26.73                  30.93          0.19
            500          8548220                     854.82       34752           13284                38.23                  43.34          0.97
           1000         16537939                    1653.79       34752           16742                48.18                  56.00          1.84

Results saved to:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/threshold_experiment_10k.tsv

======================================================================
CELL 34 COMPLETE
======================================================================

In [ ]:
# ================================================================
# CELL 35 - ALTERNATIVE BLOCKING KEY EXPERIMENT
# ================================================================

import os
import re
import sqlite3
import time
import pandas as pd

print("=" * 70)
print("CELL 35 - ALTERNATIVE BLOCKING KEY EXPERIMENT")
print("=" * 70)

# ------------------------------------------------
# PATHS
# ------------------------------------------------
BASE_PATH = (
    "/content/drive/MyDrive/"
    "6ab10eb3b23ba_student_resource/"
    "student_resource"
)

SOURCE1_PATH = os.path.join(
    BASE_PATH,
    "processed_data",
    "cleaned_train_source1.tsv"
)

GT_PATH = os.path.join(
    BASE_PATH,
    "blocking",
    "candidates",
    "ground_truth_aligned_10k.tsv"
)

DB_PATH = "/content/blocking_lookup.db"

TEST_ROWS = 10_000

# IMPORTANT:
# We do NOT use 500/1000 here.
MAX_BLOCK_SIZE = 500


# ================================================================
# LOAD SOURCE-1
# ================================================================

print("\nLoading Source-1...")

source1 = pd.read_csv(
    SOURCE1_PATH,
    sep="\t",
    nrows=TEST_ROWS,
    dtype=str,
    keep_default_na=False
)

print(
    "Source-1 records:",
    f"{len(source1):,}"
)


# ================================================================
# LOAD GROUND TRUTH
# ================================================================

print("\nLoading aligned ground truth...")

gt = pd.read_csv(
    GT_PATH,
    sep="\t",
    dtype=str
)

true_pairs = set()

for _, row in gt.iterrows():

    s1_id = row["source1_entity_id"]
    matched = row["matched_entity_ids"]

    if pd.isna(matched):
        continue

    matched = str(matched).strip()

    if not matched:
        continue

    for target_id in matched.split(","):

        target_id = target_id.strip()

        if target_id:
            true_pairs.add(
                (s1_id, target_id)
            )

print(
    "Ground-truth positive pairs:",
    f"{len(true_pairs):,}"
)


# ================================================================
# TOKENIZATION
# ================================================================

def tokens(text):

    if not text:
        return []

    return re.findall(
        r"[a-z0-9]+",
        str(text).lower()
    )


def first_token(text):

    t = tokens(text)

    if len(t) == 0:
        return ""

    return t[0]


def last_token(text):

    t = tokens(text)

    if len(t) == 0:
        return ""

    return t[-1]


# ================================================================
# CREATE ALTERNATIVE BLOCKING KEYS
# ================================================================

print("\nCreating alternative blocking keys...")

records = []

for _, row in source1.iterrows():

    s1_id = row["entity_id"]

    country = str(
        row["country"]
    ).strip().lower()

    name_tokens = tokens(
        row["business_name"]
    )

    address_tokens = tokens(
        row["business_address"]
    )

    all_tokens = list(
        dict.fromkeys(
            name_tokens + address_tokens
        )
    )

    keys = set()

    # ------------------------------------------------------------
    # STRATEGY A
    # country + first name token
    # ------------------------------------------------------------
    if country and name_tokens:

        keys.add(
            (
                "A",
                f"{country}|name_first|{name_tokens[0]}"
            )
        )

    # ------------------------------------------------------------
    # STRATEGY B
    # country + last name token
    # ------------------------------------------------------------
    if country and name_tokens:

        keys.add(
            (
                "B",
                f"{country}|name_last|{name_tokens[-1]}"
            )
        )

    # ------------------------------------------------------------
    # STRATEGY C
    # country + first 2 name tokens
    # ------------------------------------------------------------
    if country and len(name_tokens) >= 2:

        keys.add(
            (
                "C",
                f"{country}|name2|"
                f"{name_tokens[0]}|"
                f"{name_tokens[1]}"
            )
        )

    records.append(
        (
            s1_id,
            keys
        )
    )

print(
    "Source-1 records prepared:",
    f"{len(records):,}"
)


# ================================================================
# SQLITE CONNECTION
# ================================================================

print("\nConnecting SQLite...")

conn = sqlite3.connect(
    DB_PATH,
    timeout=60
)

conn.execute(
    "PRAGMA busy_timeout = 60000"
)


# ================================================================
# HELPER
# ================================================================

def generate_candidates(strategy):

    candidate_pairs = set()

    for s1_id, keys in records:

        for key_type, block_key in keys:

            if key_type != strategy:
                continue

            # ----------------------------------------------------
            # IMPORTANT:
            # Existing SQLite index uses normal block_key values
            # such as:
            # country|token
            #
            # For this experiment we cannot directly query
            # name2/name_first/name_last keys from that index.
            #
            # Therefore this strategy is evaluated against the
            # source rows themselves using a temporary in-memory
            # Source-1 grouping, not the production index.
            # ----------------------------------------------------

            pass

    return candidate_pairs


# ================================================================
# IMPORTANT NOTICE
# ================================================================

print("\n" + "=" * 70)
print("CELL 35 PRE-CHECK")
print("=" * 70)

print("""
The existing SQLite blocking index contains keys of the form:

    country|token

Alternative keys such as:

    country|name_first|token
    country|name_last|token
    country|name2|token1|token2

are NOT present in the current database.

Therefore we will NOT run a fake comparison against the
wrong index.

Instead, this cell will only prepare and inspect the
alternative blocking keys safely.
""")

# ------------------------------------------------
# KEY DISTRIBUTION
# ------------------------------------------------

strategy_counts = {
    "A_country_name_first": 0,
    "B_country_name_last": 0,
    "C_country_name2": 0
}

for _, keys in records:

    for key_type, key in keys:

        if key_type == "A":
            strategy_counts[
                "A_country_name_first"
            ] += 1

        elif key_type == "B":
            strategy_counts[
                "B_country_name_last"
            ] += 1

        elif key_type == "C":
            strategy_counts[
                "C_country_name2"
            ] += 1


print("\nAlternative key counts:")

for k, v in strategy_counts.items():

    print(
        f"{k:30s}: {v:,}"
    )


# ================================================================
# SAMPLE KEYS
# ================================================================

print("\n" + "=" * 70)
print("SAMPLE ALTERNATIVE KEYS")
print("=" * 70)

shown = 0

for s1_id, keys in records:

    if not keys:
        continue

    print(
        f"\n{s1_id}"
    )

    for key_type, key in sorted(keys):

        print(
            f"  {key_type}: {key}"
        )

    shown += 1

    if shown >= 10:
        break


# ================================================================
# CLOSE SQLITE
# ================================================================

conn.close()

print("\n" + "=" * 70)
print("CELL 35 COMPLETE")
print("=" * 70)

print("""
No database changes were made.
No large candidate file was generated.
No full dataset was processed.

Next step:
Build these alternative keys into a SMALL TEST INDEX,
then measure recall + candidate count.
""")

======================================================================
CELL 35 - ALTERNATIVE BLOCKING KEY EXPERIMENT
======================================================================

Loading Source-1...
Source-1 records: 10,000

Loading aligned ground truth...
Ground-truth positive pairs: 34,752

Creating alternative blocking keys...
Source-1 records prepared: 10,000

Connecting SQLite...

======================================================================
CELL 35 PRE-CHECK
======================================================================

The existing SQLite blocking index contains keys of the form:

    country|token

Alternative keys such as:

    country|name_first|token
    country|name_last|token
    country|name2|token1|token2

are NOT present in the current database.

Therefore we will NOT run a fake comparison against the
wrong index.

Instead, this cell will only prepare and inspect the
alternative blocking keys safely.


Alternative key counts:
A_country_name_first          : 10,000
B_country_name_last           : 10,000
C_country_name2               : 9,943

======================================================================
SAMPLE ALTERNATIVE KEYS
======================================================================

S1-925783039
  A: us|name_first|orelee
  B: us|name_last|barbershop
  C: us|name2|orelee|s

S1-773889195
  A: us|name_first|prime
  B: us|name_last|money
  C: us|name2|prime|money

S1-377745466
  A: us|name_first|b
  B: us|name_last|inc
  C: us|name2|b|retail

S1-133037285
  A: us|name_first|christ
  B: us|name_last|chapel
  C: us|name2|christ|chapel

S1-755362802
  A: india|name_first|prabhav
  B: india|name_last|center
  C: india|name2|prabhav|business

S1-851869949
  A: us|name_first|custom
  B: us|name_last|llc
  C: us|name2|custom|wealth

S1-785847572
  A: india|name_first|consulting
  B: india|name_last|limited
  C: india|name2|consulting|nyasa

S1-27541239
  A: us|name_first|nexus
  B: us|name_last|rain
  C: us|name2|nexus|anchor

S1-629417405
  A: us|name_first|moore
  B: us|name_last|inc
  C: us|name2|moore|bitwise

S1-22305073
  A: us|name_first|dermatology
  B: us|name_last|medicine
  C: us|name2|dermatology|green

======================================================================
CELL 35 COMPLETE
======================================================================

No database changes were made.
No large candidate file was generated.
No full dataset was processed.

Next step:
Build these alternative keys into a SMALL TEST INDEX,
then measure recall + candidate count.

In [ ]:
# ================================================================
# CELL 36 - ALTERNATIVE BLOCKING KEY FEASIBILITY TEST
# ================================================================

import os
import re
import sqlite3
import pandas as pd
from collections import defaultdict

print("=" * 70)
print("CELL 36 - ALTERNATIVE BLOCKING KEY FEASIBILITY TEST")
print("=" * 70)

# ------------------------------------------------
# PATHS
# ------------------------------------------------

BASE_PATH = (
    "/content/drive/MyDrive/"
    "6ab10eb3b23ba_student_resource/"
    "student_resource"
)

SOURCE1_PATH = os.path.join(
    BASE_PATH,
    "processed_data",
    "cleaned_train_source1.tsv"
)

GT_PATH = os.path.join(
    BASE_PATH,
    "blocking",
    "candidates",
    "ground_truth_aligned_10k.tsv"
)

DB_PATH = "/content/blocking_lookup.db"

TEST_ROWS = 10_000

# ================================================================
# LOAD SOURCE-1
# ================================================================

print("\nLoading Source-1...")

source1 = pd.read_csv(
    SOURCE1_PATH,
    sep="\t",
    nrows=TEST_ROWS,
    dtype=str,
    keep_default_na=False
)

print(
    "Source-1 records:",
    f"{len(source1):,}"
)

# ================================================================
# LOAD GROUND TRUTH
# ================================================================

print("\nLoading aligned ground truth...")

gt = pd.read_csv(
    GT_PATH,
    sep="\t",
    dtype=str
)

true_pairs = set()

for _, row in gt.iterrows():

    s1_id = row["source1_entity_id"]
    matched = row["matched_entity_ids"]

    if pd.isna(matched):
        continue

    matched = str(matched).strip()

    if not matched:
        continue

    for target_id in matched.split(","):

        target_id = target_id.strip()

        if target_id:
            true_pairs.add(
                (s1_id, target_id)
            )

print(
    "Ground-truth positive pairs:",
    f"{len(true_pairs):,}"
)

# ================================================================
# SQLITE CHECK
# ================================================================

print("\nConnecting SQLite...")

conn = sqlite3.connect(
    DB_PATH,
    timeout=60
)

conn.execute(
    "PRAGMA busy_timeout = 60000"
)

tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table'
    ORDER BY name
    """,
    conn
)

print("\nExisting tables:")

print(tables.to_string(index=False))

required = {
    "source2_blocks",
    "source3_blocks"
}

existing = set(
    tables["name"].tolist()
)

if not required.issubset(existing):

    conn.close()

    raise RuntimeError(
        "Required SQLite block tables are missing."
    )

print("\nRequired tables: OK")

# ================================================================
# IMPORTANT:
# EXISTING BLOCK TABLE STRUCTURE
# ================================================================

print("\nChecking block table columns...")

for table in [
    "source2_blocks",
    "source3_blocks"
]:

    info = pd.read_sql_query(
        f"PRAGMA table_info({table})",
        conn
    )

    print(f"\n{table}:")
    print(
        info[
            ["name", "type"]
        ].to_string(index=False)
    )

# ================================================================
# CURRENT BLOCKING KEY LIMITATION
# ================================================================

print("\n" + "=" * 70)
print("KEY STRUCTURE CHECK")
print("=" * 70)

print("""
Current SQLite index stores:

    block_key
    entity_id

The existing block_key is:

    country|token

It does NOT contain:

    business_name
    business_address

Therefore name_first/name_last/name2 cannot be reconstructed
from this index alone.

We will NOT guess or create false mappings.
""")

# ================================================================
# ANALYZE GROUND-TRUTH TARGET IDs
# ================================================================

print("=" * 70)
print("GROUND-TRUTH TARGET ANALYSIS")
print("=" * 70)

target_ids = set()

for _, row in gt.iterrows():

    matched = row["matched_entity_ids"]

    if pd.isna(matched):
        continue

    matched = str(matched).strip()

    if not matched:
        continue

    for target_id in matched.split(","):

        target_id = target_id.strip()

        if target_id:
            target_ids.add(target_id)

print(
    "Unique target entity IDs in ground truth:",
    f"{len(target_ids):,}"
)

source2_targets = {
    x for x in target_ids
    if x.startswith("S2-")
}

source3_targets = {
    x for x in target_ids
    if x.startswith("S3-")
}

print(
    "Source-2 target IDs:",
    f"{len(source2_targets):,}"
)

print(
    "Source-3 target IDs:",
    f"{len(source3_targets):,}"
)

# ================================================================
# CHECK TARGET IDS IN CURRENT INDEX
# ================================================================

print("\nChecking target IDs against current indexes...")

def count_existing_targets(table, target_set):

    if not target_set:
        return 0

    found = 0

    # Process in chunks to avoid huge SQL IN clauses
    target_list = list(target_set)

    chunk_size = 500

    for start in range(
        0,
        len(target_list),
        chunk_size
    ):

        chunk = target_list[
            start:start + chunk_size
        ]

        placeholders = ",".join(
            ["?"] * len(chunk)
        )

        query = f"""
        SELECT COUNT(DISTINCT entity_id)
        FROM {table}
        WHERE entity_id IN ({placeholders})
        """

        result = conn.execute(
            query,
            chunk
        ).fetchone()[0]

        found += int(result)

    return found


s2_found = count_existing_targets(
    "source2_blocks",
    source2_targets
)

s3_found = count_existing_targets(
    "source3_blocks",
    source3_targets
)

print(
    "Ground-truth S2 IDs present in index:",
    f"{s2_found:,}"
)

print(
    "Ground-truth S3 IDs present in index:",
    f"{s3_found:,}"
)

# ================================================================
# EXISTING BLOCK COVERAGE
# ================================================================

print("\n" + "=" * 70)
print("CURRENT INDEX COVERAGE")
print("=" * 70)

print("""
The current index can tell us:

    Source-1 blocking key
            ↓
    country|token
            ↓
    S2/S3 entity IDs

But it cannot tell us:

    entity_id
        ↓
    original business_name
        ↓
    first/last/2-token name key

So a real alternative-key test requires the original
Source-2 and Source-3 cleaned TSV files.
""")

# ================================================================
# CLOSE
# ================================================================

conn.close()

print("\n" + "=" * 70)
print("CELL 36 COMPLETE")
print("=" * 70)

print("""
SAFE RESULT:

Existing SQLite index verified.
Ground-truth target coverage checked.
No database changes made.
No candidate explosion.
No large RAM operation.

NEXT:
We need the cleaned Source-2 and Source-3 files to build
a genuine alternative-key index.
""")

======================================================================
CELL 36 - ALTERNATIVE BLOCKING KEY FEASIBILITY TEST
======================================================================

Loading Source-1...
Source-1 records: 10,000

Loading aligned ground truth...
Ground-truth positive pairs: 34,752

Connecting SQLite...

Existing tables:
                   name
   source2_block_counts
source2_block_frequency
         source2_blocks
   source3_block_counts
source3_block_frequency
         source3_blocks

Required tables: OK

Checking block table columns...

source2_blocks:
     name type
block_key TEXT
entity_id TEXT

source3_blocks:
     name type
block_key TEXT
entity_id TEXT

======================================================================
KEY STRUCTURE CHECK
======================================================================

Current SQLite index stores:

    block_key
    entity_id

The existing block_key is:

    country|token

It does NOT contain:

    business_name
    business_address

Therefore name_first/name_last/name2 cannot be reconstructed
from this index alone.

We will NOT guess or create false mappings.

======================================================================
GROUND-TRUTH TARGET ANALYSIS
======================================================================
Unique target entity IDs in ground truth: 34,752
Source-2 target IDs: 16,765
Source-3 target IDs: 17,987

Checking target IDs against current indexes...
Ground-truth S2 IDs present in index: 14,787
Ground-truth S3 IDs present in index: 16,567

======================================================================
CURRENT INDEX COVERAGE
======================================================================

The current index can tell us:

    Source-1 blocking key
            ↓
    country|token
            ↓
    S2/S3 entity IDs

But it cannot tell us:

    entity_id
        ↓
    original business_name
        ↓
    first/last/2-token name key

So a real alternative-key test requires the original
Source-2 and Source-3 cleaned TSV files.


======================================================================
CELL 36 COMPLETE
======================================================================

SAFE RESULT:

Existing SQLite index verified.
Ground-truth target coverage checked.
No database changes made.
No candidate explosion.
No large RAM operation.

NEXT:
We need the cleaned Source-2 and Source-3 files to build
a genuine alternative-key index.

In [ ]:
# ================================================================
# CELL 37 - VERIFY SOURCE-2 / SOURCE-3 CLEANED FILES
# ================================================================

import os

print("=" * 70)
print("CELL 37 - VERIFYING SOURCE-2 / SOURCE-3 CLEANED FILES")
print("=" * 70)

BASE_PATH = (
    "/content/drive/MyDrive/"
    "6ab10eb3b23ba_student_resource/"
    "student_resource"
)

SOURCE2_PATH = os.path.join(
    BASE_PATH,
    "processed_data",
    "cleaned_train_source2.tsv"
)

SOURCE3_PATH = os.path.join(
    BASE_PATH,
    "processed_data",
    "cleaned_train_source3.tsv"
)

print("\nSource-2:")
print(SOURCE2_PATH)

if os.path.exists(SOURCE2_PATH):
    size_gb = os.path.getsize(SOURCE2_PATH) / (1024**3)
    print("STATUS: OK")
    print(f"Size: {size_gb:.2f} GB")
else:
    print("STATUS: NOT FOUND")

print("\nSource-3:")
print(SOURCE3_PATH)

if os.path.exists(SOURCE3_PATH):
    size_gb = os.path.getsize(SOURCE3_PATH) / (1024**3)
    print("STATUS: OK")
    print(f"Size: {size_gb:.2f} GB")
else:
    print("STATUS: NOT FOUND")

print("\n" + "=" * 70)
print("CELL 37 COMPLETE")
print("=" * 70)

if os.path.exists(SOURCE2_PATH) and os.path.exists(SOURCE3_PATH):
    print("\n✅ Both Source-2 and Source-3 files are available.")
    print("NEXT: Build a small alternative-key test index.")
else:
    print("\n⚠️ One or more required files are missing.")
    print("DO NOT continue until the file paths are fixed.")

======================================================================
CELL 37 - VERIFYING SOURCE-2 / SOURCE-3 CLEANED FILES
======================================================================

Source-2:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/processed_data/cleaned_train_source2.tsv
STATUS: OK
Size: 0.46 GB

Source-3:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/processed_data/cleaned_train_source3.tsv
STATUS: OK
Size: 0.47 GB

======================================================================
CELL 37 COMPLETE
======================================================================

✅ Both Source-2 and Source-3 files are available.
NEXT: Build a small alternative-key test index.

In [ ]:
# ================================================================
# CELL 38 - BUILD ALTERNATIVE KEY TEST INDEX
# ================================================================

import os
import re
import sqlite3
import pandas as pd

print("=" * 70)
print("CELL 38 - BUILDING ALTERNATIVE KEY TEST INDEX")
print("=" * 70)

BASE_PATH = (
    "/content/drive/MyDrive/"
    "6ab10eb3b23ba_student_resource/"
    "student_resource"
)

SOURCE2_PATH = os.path.join(
    BASE_PATH,
    "processed_data",
    "cleaned_train_source2.tsv"
)

SOURCE3_PATH = os.path.join(
    BASE_PATH,
    "processed_data",
    "cleaned_train_source3.tsv"
)

ALT_DB = "/content/alternative_blocking_test.db"

# ------------------------------------------------
# REMOVE OLD TEST DATABASE
# ------------------------------------------------

if os.path.exists(ALT_DB):
    os.remove(ALT_DB)

print("\nCreating local SQLite database:")
print(ALT_DB)

conn = sqlite3.connect(
    ALT_DB,
    timeout=120
)

conn.execute("PRAGMA journal_mode=WAL")
conn.execute("PRAGMA synchronous=OFF")
conn.execute("PRAGMA temp_store=FILE")

# ------------------------------------------------
# CREATE TABLE
# ------------------------------------------------

conn.execute("""
CREATE TABLE alternative_blocks (
    block_type TEXT,
    block_key TEXT,
    entity_id TEXT,
    source TEXT
)
""")

print("Table created.")

# ------------------------------------------------
# TOKEN FUNCTION
# ------------------------------------------------

def clean_tokens(text):
    text = str(text).lower()
    text = re.sub(r"[^a-z0-9]+", " ", text)
    return [
        x for x in text.split()
        if x
    ]

# ------------------------------------------------
# PROCESS ONE SOURCE
# ------------------------------------------------

def process_source(path, source_name):

    print("\n" + "=" * 60)
    print(f"PROCESSING {source_name}")
    print("=" * 60)

    total = 0
    inserted = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        dtype=str,
        keep_default_na=False,
        chunksize=50_000
    ):

        # ------------------------------------------------
        # Detect columns
        # ------------------------------------------------

        entity_col = "entity_id"
        name_col = "business_name"

        if entity_col not in chunk.columns:
            raise ValueError(
                f"{entity_col} not found in {source_name}"
            )

        if name_col not in chunk.columns:
            raise ValueError(
                f"{name_col} not found in {source_name}"
            )

        rows = []

        for _, row in chunk.iterrows():

            entity_id = row[entity_col]
            name = row[name_col]

            tokens = clean_tokens(name)

            if not tokens:
                continue

            # --------------------------------------------
            # Alternative A:
            # first name token
            # --------------------------------------------

            first_key = (
                f"name_first|{tokens[0]}"
            )

            rows.append((
                "A",
                first_key,
                entity_id,
                source_name
            ))

            # --------------------------------------------
            # Alternative B:
            # last name token
            # --------------------------------------------

            last_key = (
                f"name_last|{tokens[-1]}"
            )

            rows.append((
                "B",
                last_key,
                entity_id,
                source_name
            ))

            # --------------------------------------------
            # Alternative C:
            # first two tokens
            # --------------------------------------------

            if len(tokens) >= 2:

                two_key = (
                    f"name2|{tokens[0]}|{tokens[1]}"
                )

                rows.append((
                    "C",
                    two_key,
                    entity_id,
                    source_name
                ))

        if rows:

            conn.executemany(
                """
                INSERT INTO alternative_blocks
                (
                    block_type,
                    block_key,
                    entity_id,
                    source
                )
                VALUES (?, ?, ?, ?)
                """,
                rows
            )

            inserted += len(rows)

        total += len(chunk)

        if total % 500_000 == 0:

            conn.commit()

            print(
                f"Processed: {total:,} | "
                f"Index rows: {inserted:,}"
            )

    conn.commit()

    print(
        f"{source_name} complete."
    )

    print(
        f"Records processed: {total:,}"
    )

    print(
        f"Index rows created: {inserted:,}"
    )


# ------------------------------------------------
# BUILD SOURCE-2
# ------------------------------------------------

process_source(
    SOURCE2_PATH,
    "source2"
)

# ------------------------------------------------
# BUILD SOURCE-3
# ------------------------------------------------

process_source(
    SOURCE3_PATH,
    "source3"
)

# ------------------------------------------------
# CREATE INDEX
# ------------------------------------------------

print("\n" + "=" * 70)
print("CREATING SQLITE INDEX")
print("=" * 70)

conn.execute("""
CREATE INDEX idx_alt_block
ON alternative_blocks
(
    block_type,
    block_key
)
""")

conn.execute("""
CREATE INDEX idx_alt_entity
ON alternative_blocks
(
    entity_id
)
""")

conn.commit()

# ------------------------------------------------
# VERIFY
# ------------------------------------------------

print("\n" + "=" * 70)
print("VERIFYING ALTERNATIVE INDEX")
print("=" * 70)

count = conn.execute(
    "SELECT COUNT(*) FROM alternative_blocks"
).fetchone()[0]

print(
    f"Total alternative index rows: {count:,}"
)

summary = pd.read_sql_query(
    """
    SELECT
        source,
        block_type,
        COUNT(*) AS rows
    FROM alternative_blocks
    GROUP BY source, block_type
    ORDER BY source, block_type
    """,
    conn
)

print("\nIndex summary:")
print(summary.to_string(index=False))

conn.close()

size_gb = (
    os.path.getsize(ALT_DB)
    / (1024 ** 3)
)

print("\nDatabase size:")
print(f"{size_gb:.2f} GB")

print("\n" + "=" * 70)
print("CELL 38 COMPLETE")
print("=" * 70)

print("""
Alternative-key index created successfully.

No Source-1 candidate generation was performed.
No full matching was performed.

NEXT:
Test these keys against the 10K Source-1 sample.
""")

======================================================================
CELL 38 - BUILDING ALTERNATIVE KEY TEST INDEX
======================================================================

Creating local SQLite database:
/content/alternative_blocking_test.db
Table created.

============================================================
PROCESSING source2
============================================================
Processed: 500,000 | Index rows: 1,354,185
Processed: 1,000,000 | Index rows: 2,708,320
Processed: 1,500,000 | Index rows: 4,061,080
Processed: 2,000,000 | Index rows: 5,413,213
Processed: 2,500,000 | Index rows: 6,765,120
Processed: 3,000,000 | Index rows: 8,118,051
Processed: 3,500,000 | Index rows: 9,471,319
Processed: 4,000,000 | Index rows: 10,823,411
Processed: 4,500,000 | Index rows: 12,176,213
Processed: 5,000,000 | Index rows: 13,529,307
source2 complete.
Records processed: 5,034,616
Index rows created: 13,622,923

============================================================
PROCESSING source3
============================================================
Processed: 500,000 | Index rows: 1,412,637
Processed: 1,000,000 | Index rows: 2,825,361
Processed: 1,500,000 | Index rows: 4,237,867
Processed: 2,000,000 | Index rows: 5,649,854
Processed: 2,500,000 | Index rows: 7,062,731
Processed: 3,000,000 | Index rows: 8,475,459
Processed: 3,500,000 | Index rows: 9,887,982
Processed: 4,000,000 | Index rows: 11,301,175
Processed: 4,500,000 | Index rows: 12,714,004
Processed: 5,000,000 | Index rows: 14,127,302
source3 complete.
Records processed: 5,285,603
Index rows created: 14,934,282

======================================================================
CREATING SQLITE INDEX
======================================================================

======================================================================
VERIFYING ALTERNATIVE INDEX
======================================================================
Total alternative index rows: 28,557,205

Index summary:
 source block_type    rows
source2          A 4578854
source2          B 4578854
source2          C 4465215
source3          A 5041960
source3          B 5041960
source3          C 4850362

Database size:
2.68 GB

======================================================================
CELL 38 COMPLETE
======================================================================

Alternative-key index created successfully.

No Source-1 candidate generation was performed.
No full matching was performed.

NEXT:
Test these keys against the 10K Source-1 sample.

In [ ]:
# ================================================================
# CELL 40 - COUNTRY-AWARE ALTERNATIVE BLOCKING TEST
# ================================================================

import os
import sqlite3
import pandas as pd
import time

print("=" * 70)
print("CELL 40 - COUNTRY-AWARE ALTERNATIVE BLOCKING TEST")
print("=" * 70)

# ------------------------------------------------
# PATHS
# ------------------------------------------------

SOURCE1_PATH = (
    "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/"
    "student_resource/processed_data/cleaned_train_source1.tsv"
)

GT_PATH = (
    "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/"
    "student_resource/blocking/candidates/"
    "ground_truth_aligned_10k.tsv"
)

ALT_DB = "/content/alternative_blocking_test.db"

TEST_ROWS = 10_000
MAX_BLOCK_SIZE = 500

# ------------------------------------------------
# CHECK FILES
# ------------------------------------------------

print("\nChecking files...")

for path in [SOURCE1_PATH, GT_PATH, ALT_DB]:
    if not os.path.exists(path):
        raise FileNotFoundError(path)

print("All required files: OK")

# ------------------------------------------------
# LOAD SOURCE-1
# ------------------------------------------------

print("\nLoading Source-1...")

s1 = pd.read_csv(
    SOURCE1_PATH,
    sep="\t",
    nrows=TEST_ROWS,
    dtype=str
).fillna("")

print("Source-1 records:", len(s1))

# ------------------------------------------------
# LOAD GROUND TRUTH
# ------------------------------------------------

print("\nLoading aligned ground truth...")

gt = pd.read_csv(
    GT_PATH,
    sep="\t",
    dtype=str
).fillna("")

# Build true pairs
true_pairs = set()

for _, row in gt.iterrows():

    s1_id = row["source1_entity_id"]
    matched = row["matched_entity_ids"]

    if not matched:
        continue

    for target_id in str(matched).split(","):

        target_id = target_id.strip()

        if target_id:
            true_pairs.add((s1_id, target_id))

print("Ground-truth positive pairs:", len(true_pairs))

# ------------------------------------------------
# HELPER: TOKENIZE
# ------------------------------------------------

def normalize_tokens(text):

    text = str(text).lower()

    cleaned = []

    current = ""

    for ch in text:

        if ch.isalnum():
            current += ch
        else:
            if current:
                cleaned.append(current)
                current = ""

    if current:
        cleaned.append(current)

    return cleaned


# ------------------------------------------------
# CREATE COUNTRY + FIRST NAME KEY
# ------------------------------------------------

print("\nCreating country-aware name_first keys...")

source1_keys = []

for _, row in s1.iterrows():

    country = str(row["country"]).strip().lower()

    tokens = normalize_tokens(row["business_name"])

    if tokens:
        first_token = tokens[0]

        block_key = f"{country}|name_first|{first_token}"

        source1_keys.append(
            (
                row["entity_id"],
                block_key
            )
        )

print("Keys created:", len(source1_keys))

# ------------------------------------------------
# CONNECT SQLITE
# ------------------------------------------------

print("\nConnecting alternative SQLite index...")

conn = sqlite3.connect(
    ALT_DB,
    timeout=60
)

print("SQLite connected.")

# ------------------------------------------------
# CHECK TABLE STRUCTURE
# ------------------------------------------------

tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table'
    """,
    conn
)

print("\nTables:")
print(tables)

# Find likely alternative index table
table_names = tables["name"].tolist()

candidate_tables = [
    t for t in table_names
    if "alternative" in t.lower()
    or "block" in t.lower()
]

print("\nCandidate index tables:", candidate_tables)

# ------------------------------------------------
# SELECT INDEX TABLE
# ------------------------------------------------

if not candidate_tables:
    raise RuntimeError(
        "No alternative blocking table found in SQLite database."
    )

ALT_TABLE = candidate_tables[0]

print("\nUsing table:", ALT_TABLE)

# ------------------------------------------------
# SHOW COLUMNS
# ------------------------------------------------

schema = pd.read_sql_query(
    f"PRAGMA table_info({ALT_TABLE})",
    conn
)

print("\nIndex columns:")
print(schema[["name", "type"]])

columns = schema["name"].tolist()

required = ["block_key", "entity_id"]

for col in required:

    if col not in columns:
        raise RuntimeError(
            f"Required column '{col}' not found."
        )

# Detect optional source/block_type columns
has_source = "source" in columns
has_block_type = "block_type" in columns

print("\nSource column:", has_source)
print("Block type column:", has_block_type)

# ------------------------------------------------
# TEST
# ------------------------------------------------

print("\n" + "=" * 70)
print("TESTING COUNTRY-AWARE STRATEGY A")
print("=" * 70)

captured_pairs = set()

candidate_count = 0
records_with_candidates = 0
records_with_capture = 0

start_time = time.time()

for i, (s1_id, block_key) in enumerate(source1_keys, start=1):

    # Query based on available schema
    if has_source and has_block_type:

        sql = f"""
            SELECT entity_id
            FROM {ALT_TABLE}
            WHERE source IN ('source2', 'source3')
              AND block_type = 'A'
              AND block_key = ?
            LIMIT ?
        """

        rows = conn.execute(
            sql,
            (block_key, MAX_BLOCK_SIZE)
        ).fetchall()

    elif has_block_type:

        sql = f"""
            SELECT entity_id
            FROM {ALT_TABLE}
            WHERE block_type = 'A'
              AND block_key = ?
            LIMIT ?
        """

        rows = conn.execute(
            sql,
            (block_key, MAX_BLOCK_SIZE)
        ).fetchall()

    else:

        sql = f"""
            SELECT entity_id
            FROM {ALT_TABLE}
            WHERE block_key = ?
            LIMIT ?
        """

        rows = conn.execute(
            sql,
            (block_key, MAX_BLOCK_SIZE)
        ).fetchall()

    if rows:

        records_with_candidates += 1

        for (candidate_id,) in rows:

            candidate_count += 1

            pair = (
                s1_id,
                candidate_id
            )

            if pair in true_pairs:
                captured_pairs.add(pair)

    if i % 1000 == 0:

        elapsed = (time.time() - start_time) / 60

        print(
            f"Processed: {i:,} | "
            f"Candidates: {candidate_count:,} | "
            f"Captured: {len(captured_pairs):,} | "
            f"Time: {elapsed:.2f} min"
        )

conn.close()

# ------------------------------------------------
# CALCULATE RECALL
# ------------------------------------------------

missed_pairs = len(true_pairs) - len(captured_pairs)

pair_recall = (
    len(captured_pairs) / len(true_pairs) * 100
    if true_pairs
    else 0
)

true_match_records = set(
    s1_id
    for s1_id, _ in true_pairs
)

captured_records = set(
    s1_id
    for s1_id, _ in captured_pairs
)

record_recall = (
    len(captured_records)
    / len(true_match_records)
    * 100
    if true_match_records
    else 0
)

elapsed = (time.time() - start_time) / 60

# ------------------------------------------------
# RESULT
# ------------------------------------------------

print("\n" + "=" * 70)
print("COUNTRY-AWARE STRATEGY A RESULTS")
print("=" * 70)

print(f"Ground-truth positive pairs : {len(true_pairs):,}")
print(f"Captured true pairs         : {len(captured_pairs):,}")
print(f"Missed true pairs           : {missed_pairs:,}")

print(f"\nPair-level recall           : {pair_recall:.2f}%")

print(
    f"\nRecords with >=1 true match : "
    f"{len(true_match_records):,}"
)

print(
    f"Records with >=1 capture    : "
    f"{len(captured_records):,}"
)

print(
    f"Record-level recall         : "
    f"{record_recall:.2f}%"
)

print(f"\nCandidate rows              : {candidate_count:,}")

print(
    f"Average candidates/record   : "
    f"{candidate_count / len(s1):.2f}"
)

print(f"Time taken                  : {elapsed:.2f} minutes")

print("\n" + "=" * 70)
print("CELL 40 COMPLETE")
print("=" * 70)

======================================================================
CELL 40 - COUNTRY-AWARE ALTERNATIVE BLOCKING TEST
======================================================================

Checking files...
All required files: OK

Loading Source-1...
Source-1 records: 10000

Loading aligned ground truth...
Ground-truth positive pairs: 34752

Creating country-aware name_first keys...
Keys created: 10000

Connecting alternative SQLite index...
SQLite connected.

Tables:
                 name
0  alternative_blocks

Candidate index tables: ['alternative_blocks']

Using table: alternative_blocks

Index columns:
         name  type
0  block_type  TEXT
1   block_key  TEXT
2   entity_id  TEXT
3      source  TEXT

Source column: True
Block type column: True

======================================================================
TESTING COUNTRY-AWARE STRATEGY A
======================================================================
Processed: 1,000 | Candidates: 0 | Captured: 0 | Time: 0.00 min
Processed: 2,000 | Candidates: 0 | Captured: 0 | Time: 0.00 min
Processed: 3,000 | Candidates: 0 | Captured: 0 | Time: 0.00 min
Processed: 4,000 | Candidates: 0 | Captured: 0 | Time: 0.00 min
Processed: 5,000 | Candidates: 0 | Captured: 0 | Time: 0.00 min
Processed: 6,000 | Candidates: 0 | Captured: 0 | Time: 0.00 min
Processed: 7,000 | Candidates: 0 | Captured: 0 | Time: 0.00 min
Processed: 8,000 | Candidates: 0 | Captured: 0 | Time: 0.00 min
Processed: 9,000 | Candidates: 0 | Captured: 0 | Time: 0.00 min
Processed: 10,000 | Candidates: 0 | Captured: 0 | Time: 0.00 min

======================================================================
COUNTRY-AWARE STRATEGY A RESULTS
======================================================================
Ground-truth positive pairs : 34,752
Captured true pairs         : 0
Missed true pairs           : 34,752

Pair-level recall           : 0.00%

Records with >=1 true match : 9,440
Records with >=1 capture    : 0
Record-level recall         : 0.00%

Candidate rows              : 0
Average candidates/record   : 0.00
Time taken                  : 0.00 minutes

======================================================================
CELL 40 COMPLETE
======================================================================

In [ ]:
# ================================================================
# CELL 41 - ALTERNATIVE INDEX KEY FORMAT CHECK
# ================================================================

import sqlite3
import pandas as pd

ALT_DB = "/content/alternative_blocking_test.db"

print("=" * 70)
print("CELL 41 - ALTERNATIVE INDEX KEY FORMAT CHECK")
print("=" * 70)

conn = sqlite3.connect(ALT_DB)

print("\nSQLite table: alternative_blocks")

# ------------------------------------------------
# SHOW SAMPLE ROWS
# ------------------------------------------------

print("\n" + "=" * 70)
print("FIRST 20 INDEX ROWS")
print("=" * 70)

sample = pd.read_sql_query(
    """
    SELECT block_type, block_key, entity_id, source
    FROM alternative_blocks
    LIMIT 20
    """,
    conn
)

print(sample.to_string(index=False))

# ------------------------------------------------
# SHOW ONE SAMPLE FOR EACH BLOCK TYPE
# ------------------------------------------------

print("\n" + "=" * 70)
print("SAMPLE KEY BY BLOCK TYPE")
print("=" * 70)

for block_type in ["A", "B", "C"]:

    result = pd.read_sql_query(
        """
        SELECT block_type, block_key, entity_id, source
        FROM alternative_blocks
        WHERE block_type = ?
        LIMIT 5
        """,
        conn,
        params=(block_type,)
    )

    print(f"\nBLOCK TYPE: {block_type}")
    print(result.to_string(index=False))

# ------------------------------------------------
# LOAD SOURCE-1 FIRST 10 ROWS
# ------------------------------------------------

SOURCE1_PATH = (
    "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/"
    "student_resource/processed_data/cleaned_train_source1.tsv"
)

s1 = pd.read_csv(
    SOURCE1_PATH,
    sep="\t",
    nrows=10,
    dtype=str
).fillna("")

print("\n" + "=" * 70)
print("SOURCE-1 EXPECTED KEYS")
print("=" * 70)

def normalize_tokens(text):

    text = str(text).lower()

    tokens = []
    current = ""

    for ch in text:

        if ch.isalnum():
            current += ch
        else:
            if current:
                tokens.append(current)
                current = ""

    if current:
        tokens.append(current)

    return tokens


for _, row in s1.iterrows():

    country = str(row["country"]).strip().lower()
    tokens = normalize_tokens(row["business_name"])

    if tokens:

        first_token = tokens[0]

        key = f"{country}|name_first|{first_token}"

        print(
            row["entity_id"],
            "=>",
            key
        )

conn.close()

print("\n" + "=" * 70)
print("CELL 41 COMPLETE")
print("=" * 70)

print("""
IMPORTANT:
This cell only inspects the key format.
No candidate generation.
No large processing.
No database modification.
""")

======================================================================
CELL 41 - ALTERNATIVE INDEX KEY FORMAT CHECK
======================================================================

SQLite table: alternative_blocks

======================================================================
FIRST 20 INDEX ROWS
======================================================================
block_type                      block_key    entity_id  source
         A            name_first|holloway S2-764573417 source2
         B              name_last|seafood S2-764573417 source2
         C            name2|holloway|peak S2-764573417 source2
         A              name_first|summit S2-163963287 source2
         B                  name_last|inc S2-163963287 source2
         C               name2|summit|inc S2-163963287 source2
         A               name_first|delta  S2-49942811 source2
         B                  name_last|inc  S2-49942811 source2
         C name2|delta|tetlecommunication  S2-49942811 source2
         A                 name_first|lee S2-138046867 source2
         B               name_last|lawson S2-138046867 source2
         C                  name2|lee|and S2-138046867 source2
         A          name_first|shivshakti S2-584977605 source2
         B                  name_last|com S2-584977605 source2
         C     name2|shivshakti|vidyalaya S2-584977605 source2
         A               name_first|shree S2-277444929 source2
         B                  name_last|ltd S2-277444929 source2
         C           name2|shree|infracon S2-277444929 source2
         A             name_first|chavira S2-721031885 source2
         B                  name_last|llc S2-721031885 source2

======================================================================
SAMPLE KEY BY BLOCK TYPE
======================================================================

BLOCK TYPE: A
block_type    block_key    entity_id  source
         A name_first|0 S2-515804728 source2
         A name_first|0 S2-949187240 source2
         A name_first|0  S2-28376536 source2
         A name_first|0 S2-929118467 source2
         A name_first|0 S2-611688914 source2

BLOCK TYPE: B
block_type   block_key    entity_id  source
         B name_last|0 S2-539094993 source2
         B name_last|0  S2-47650894 source2
         B name_last|0 S2-621995108 source2
         B name_last|0  S2-40932579 source2
         B name_last|0 S2-921063412 source2

BLOCK TYPE: C
block_type            block_key    entity_id  source
         C  name2|007alussa|com S2-483155324 source2
         C name2|007brewing|com  S2-94630396 source2
         C  name2|007credit|com S2-372406164 source2
         C    name2|007deli|com S3-179173477 source3
         C    name2|007hawk|com S3-181181150 source3

======================================================================
SOURCE-1 EXPECTED KEYS
======================================================================
S1-925783039 => us|name_first|orelee
S1-773889195 => us|name_first|prime
S1-377745466 => us|name_first|b
S1-133037285 => us|name_first|christ
S1-755362802 => india|name_first|prabhav
S1-851869949 => us|name_first|custom
S1-785847572 => india|name_first|consulting
S1-27541239 => us|name_first|nexus
S1-629417405 => us|name_first|moore
S1-22305073 => us|name_first|dermatology

======================================================================
CELL 41 COMPLETE
======================================================================

IMPORTANT:
This cell only inspects the key format.
No candidate generation.
No large processing.
No database modification.

In [ ]:
# ================================================================
# CELL 42 - CORRECT ALTERNATIVE KEY RECALL TEST
# ================================================================

import sqlite3
import pandas as pd
import time

print("=" * 70)
print("CELL 42 - CORRECT ALTERNATIVE KEY RECALL TEST")
print("=" * 70)

SOURCE1_PATH = (
    "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/"
    "student_resource/processed_data/cleaned_train_source1.tsv"
)

GT_PATH = (
    "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/"
    "student_resource/blocking/candidates/"
    "ground_truth_aligned_10k.tsv"
)

ALT_DB = "/content/alternative_blocking_test.db"

TEST_ROWS = 10_000
MAX_BLOCK_SIZE = 500

# ------------------------------------------------
# LOAD SOURCE-1
# ------------------------------------------------

print("\nLoading Source-1...")

s1 = pd.read_csv(
    SOURCE1_PATH,
    sep="\t",
    dtype=str,
    nrows=TEST_ROWS
).fillna("")

print("Source-1 records:", len(s1))

# ------------------------------------------------
# LOAD GROUND TRUTH
# ------------------------------------------------

print("\nLoading ground truth...")

gt = pd.read_csv(
    GT_PATH,
    sep="\t",
    dtype=str
).fillna("")

true_pairs = set()

for _, row in gt.iterrows():

    s1_id = row["source1_entity_id"]
    matched = row["matched_entity_ids"]

    if not matched:
        continue

    for target_id in str(matched).split(","):

        target_id = target_id.strip()

        if target_id:
            true_pairs.add(
                (s1_id, target_id)
            )

print(
    "Ground-truth positive pairs:",
    f"{len(true_pairs):,}"
)

# ------------------------------------------------
# TOKENIZER
# ------------------------------------------------

def normalize_tokens(text):

    text = str(text).lower()

    tokens = []
    current = ""

    for ch in text:

        if ch.isalnum():
            current += ch

        else:

            if current:
                tokens.append(current)
                current = ""

    if current:
        tokens.append(current)

    return tokens


# ------------------------------------------------
# CONNECT DATABASE
# ------------------------------------------------

print("\nConnecting SQLite...")

conn = sqlite3.connect(
    ALT_DB,
    timeout=60
)

conn.execute(
    "PRAGMA busy_timeout=60000"
)

print("SQLite connected.")

# ------------------------------------------------
# TEST STRATEGY A
# ------------------------------------------------

print("\n" + "=" * 70)
print("TESTING A: name_first")
print("=" * 70)

candidate_pairs = set()

candidate_rows = 0
records_with_candidates = 0

start = time.time()

for i, (_, row) in enumerate(
    s1.iterrows(),
    start=1
):

    s1_id = row["entity_id"]

    tokens = normalize_tokens(
        row["business_name"]
    )

    if not tokens:
        continue

    # IMPORTANT:
    # Database actually stores:
    # name_first|TOKEN

    block_key = (
        "name_first|" +
        tokens[0]
    )

    rows = conn.execute(
        """
        SELECT entity_id
        FROM alternative_blocks
        WHERE block_type = 'A'
          AND block_key = ?
        LIMIT ?
        """,
        (
            block_key,
            MAX_BLOCK_SIZE
        )
    ).fetchall()

    if rows:

        records_with_candidates += 1

        for (candidate_id,) in rows:

            candidate_rows += 1

            candidate_pairs.add(
                (
                    s1_id,
                    candidate_id
                )
            )

    if i % 1000 == 0:

        elapsed = (
            time.time() - start
        ) / 60

        print(
            f"Processed: {i:,} | "
            f"Candidates: {candidate_rows:,} | "
            f"Time: {elapsed:.2f} min"
        )

conn.close()

# ------------------------------------------------
# RECALL
# ------------------------------------------------

captured = (
    candidate_pairs &
    true_pairs
)

true_records = {
    x[0]
    for x in true_pairs
}

captured_records = {
    x[0]
    for x in captured
}

pair_recall = (
    len(captured) /
    len(true_pairs) *
    100
)

record_recall = (
    len(captured_records) /
    len(true_records) *
    100
)

avg_candidates = (
    candidate_rows /
    len(s1)
)

elapsed = (
    time.time() - start
) / 60

# ------------------------------------------------
# RESULTS
# ------------------------------------------------

print("\n" + "=" * 70)
print("STRATEGY A RESULTS")
print("=" * 70)

print(
    "Candidate rows:",
    f"{candidate_rows:,}"
)

print(
    "Average candidates/record:",
    f"{avg_candidates:.2f}"
)

print(
    "Captured true pairs:",
    f"{len(captured):,}"
)

print(
    "Missed true pairs:",
    f"{len(true_pairs) - len(captured):,}"
)

print(
    "\nPair-level recall:",
    f"{pair_recall:.2f}%"
)

print(
    "Records with >=1 true match:",
    f"{len(true_records):,}"
)

print(
    "Records with >=1 capture:",
    f"{len(captured_records):,}"
)

print(
    "Record-level recall:",
    f"{record_recall:.2f}%"
)

print(
    "\nTime taken:",
    f"{elapsed:.2f} minutes"
)

print("\n" + "=" * 70)
print("CELL 42 COMPLETE")
print("=" * 70)

print("""
BASELINE:
Pair recall   = 8.23%
Record recall = 10.36%

Compare Strategy A against this baseline.

No database changes were made.
""")

======================================================================
CELL 42 - CORRECT ALTERNATIVE KEY RECALL TEST
======================================================================

Loading Source-1...
Source-1 records: 10000

Loading ground truth...
Ground-truth positive pairs: 34,752

Connecting SQLite...
SQLite connected.

======================================================================
TESTING A: name_first
======================================================================
Processed: 1,000 | Candidates: 348,558 | Time: 0.06 min
Processed: 2,000 | Candidates: 684,498 | Time: 0.10 min
Processed: 3,000 | Candidates: 1,023,624 | Time: 0.14 min
Processed: 4,000 | Candidates: 1,376,895 | Time: 0.19 min
Processed: 5,000 | Candidates: 1,722,019 | Time: 0.24 min
Processed: 6,000 | Candidates: 2,064,677 | Time: 0.28 min
Processed: 7,000 | Candidates: 2,412,053 | Time: 0.31 min
Processed: 8,000 | Candidates: 2,762,541 | Time: 0.36 min
Processed: 9,000 | Candidates: 3,110,226 | Time: 0.40 min
Processed: 10,000 | Candidates: 3,449,744 | Time: 0.44 min

======================================================================
STRATEGY A RESULTS
======================================================================
Candidate rows: 3,449,744
Average candidates/record: 344.97
Captured true pairs: 13,396
Missed true pairs: 21,356

Pair-level recall: 38.55%
Records with >=1 true match: 9,440
Records with >=1 capture: 5,132
Record-level recall: 54.36%

Time taken: 0.44 minutes

======================================================================
CELL 42 COMPLETE
======================================================================

BASELINE:
Pair recall   = 8.23%
Record recall = 10.36%

Compare Strategy A against this baseline.

No database changes were made.

In [ ]:
# ================================================================
# CELL 44 - NAME2 SMALL FEASIBILITY TEST
# ================================================================

import os
import sqlite3
import pandas as pd
import time

print("=" * 70)
print("CELL 44 - NAME2 SMALL FEASIBILITY TEST")
print("=" * 70)

SOURCE1_PATH = (
    "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/"
    "student_resource/processed_data/cleaned_train_source1.tsv"
)

GT_PATH = (
    "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/"
    "student_resource/blocking/candidates/ground_truth_aligned_10k.tsv"
)

ALT_DB = "/content/alternative_blocking_test.db"

# ---------------------------------------------------------------
# CHECK FILES
# ---------------------------------------------------------------
for path in [SOURCE1_PATH, GT_PATH, ALT_DB]:
    if os.path.exists(path):
        print("OK:", path)
    else:
        raise FileNotFoundError(path)

# ---------------------------------------------------------------
# LOAD ONLY 1,000 SOURCE-1 RECORDS
# ---------------------------------------------------------------
print("\nLoading Source-1 test sample...")

s1 = pd.read_csv(
    SOURCE1_PATH,
    sep="\t",
    nrows=1000,
    dtype=str
).fillna("")

print("Source-1 test records:", len(s1))

# ---------------------------------------------------------------
# LOAD ALIGNED GROUND TRUTH
# ---------------------------------------------------------------
print("\nLoading ground truth...")

gt = pd.read_csv(
    GT_PATH,
    sep="\t",
    dtype=str
).fillna("")

test_ids = set(s1["entity_id"])

gt = gt[gt["source1_entity_id"].isin(test_ids)]

true_pairs = set()

for _, row in gt.iterrows():

    s1_id = row["source1_entity_id"]
    matched = row["matched_entity_ids"]

    if not matched:
        continue

    for target_id in matched.split(","):
        target_id = target_id.strip()

        if target_id:
            true_pairs.add((s1_id, target_id))

print("Ground-truth positive pairs:", len(true_pairs))

# ---------------------------------------------------------------
# CONNECT SQLITE
# ---------------------------------------------------------------
print("\nConnecting alternative SQLite index...")

conn = sqlite3.connect(ALT_DB)

# ---------------------------------------------------------------
# TEST NAME2
# ---------------------------------------------------------------
print("\n" + "=" * 70)
print("TESTING C: name2")
print("=" * 70)

candidate_count = 0
captured_pairs = set()

start_time = time.time()

for i, row in s1.iterrows():

    s1_id = row["entity_id"]

    name = str(row["business_name"]).strip().lower()

    tokens = [
        t.strip()
        for t in name.replace("|", " ").split()
        if t.strip()
    ]

    if len(tokens) < 2:
        continue

    # First two name tokens
    token1 = tokens[0]
    token2 = tokens[1]

    block_key = f"name2|{token1}|{token2}"

    rows = conn.execute(
        """
        SELECT entity_id
        FROM alternative_blocks
        WHERE block_type = ?
          AND block_key = ?
        """,
        ("C", block_key)
    ).fetchall()

    candidate_count += len(rows)

    for (candidate_id,) in rows:

        if (s1_id, candidate_id) in true_pairs:
            captured_pairs.add((s1_id, candidate_id))

    if (i + 1) % 100 == 0:

        elapsed = (time.time() - start_time) / 60

        print(
            f"Processed: {i+1:,} | "
            f"Candidates: {candidate_count:,} | "
            f"Time: {elapsed:.2f} min"
        )

# ---------------------------------------------------------------
# RESULTS
# ---------------------------------------------------------------
captured = len(captured_pairs)
total_true = len(true_pairs)
missed = total_true - captured

pair_recall = (
    captured / total_true * 100
    if total_true else 0
)

true_records = {
    x[0] for x in true_pairs
}

captured_records = {
    x[0] for x in captured_pairs
}

record_recall = (
    len(captured_records) / len(true_records) * 100
    if true_records else 0
)

elapsed = (time.time() - start_time) / 60

print("\n" + "=" * 70)
print("NAME2 FEASIBILITY RESULTS")
print("=" * 70)

print("Test records:", len(s1))
print(f"Candidate rows: {candidate_count:,}")
print(
    f"Average candidates/record: "
    f"{candidate_count / len(s1):.2f}"
)

print(f"Ground-truth pairs: {total_true:,}")
print(f"Captured true pairs: {captured:,}")
print(f"Missed true pairs: {missed:,}")

print(f"\nPair-level recall: {pair_recall:.2f}%")

print(
    f"Records with >=1 true match: "
    f"{len(true_records):,}"
)

print(
    f"Records with >=1 capture: "
    f"{len(captured_records):,}"
)

print(f"Record-level recall: {record_recall:.2f}%")

print(f"\nTime taken: {elapsed:.2f} minutes")

print("\n" + "=" * 70)
print("CELL 44 COMPLETE")
print("=" * 70)

conn.close()

======================================================================
CELL 44 - NAME2 SMALL FEASIBILITY TEST
======================================================================
OK: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/processed_data/cleaned_train_source1.tsv
OK: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ground_truth_aligned_10k.tsv
OK: /content/alternative_blocking_test.db

Loading Source-1 test sample...
Source-1 test records: 1000

Loading ground truth...
Ground-truth positive pairs: 3517

Connecting alternative SQLite index...

======================================================================
TESTING C: name2
======================================================================
Processed: 100 | Candidates: 68,097 | Time: 0.01 min
Processed: 200 | Candidates: 112,616 | Time: 0.02 min
Processed: 300 | Candidates: 149,883 | Time: 0.02 min
Processed: 400 | Candidates: 177,968 | Time: 0.03 min
Processed: 500 | Candidates: 215,918 | Time: 0.04 min
Processed: 600 | Candidates: 243,716 | Time: 0.04 min
Processed: 700 | Candidates: 266,734 | Time: 0.05 min
Processed: 800 | Candidates: 349,899 | Time: 0.05 min
Processed: 900 | Candidates: 389,137 | Time: 0.06 min
Processed: 1,000 | Candidates: 416,369 | Time: 0.06 min

======================================================================
NAME2 FEASIBILITY RESULTS
======================================================================
Test records: 1000
Candidate rows: 416,369
Average candidates/record: 416.37
Ground-truth pairs: 3,517
Captured true pairs: 1,615
Missed true pairs: 1,902

Pair-level recall: 45.92%
Records with >=1 true match: 946
Records with >=1 capture: 715
Record-level recall: 75.58%

Time taken: 0.06 minutes

======================================================================
CELL 44 COMPLETE
======================================================================

In [ ]:
# ================================================================
# CELL 45 - NAME2 FULL 10K RECALL TEST
# ================================================================

import os
import sqlite3
import pandas as pd
import time

print("=" * 70)
print("CELL 45 - NAME2 FULL 10K RECALL TEST")
print("=" * 70)

SOURCE1_PATH = (
    "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/"
    "student_resource/processed_data/cleaned_train_source1.tsv"
)

GT_PATH = (
    "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/"
    "student_resource/blocking/candidates/ground_truth_aligned_10k.tsv"
)

ALT_DB = "/content/alternative_blocking_test.db"

# ---------------------------------------------------------------
# CHECK FILES
# ---------------------------------------------------------------
for path in [SOURCE1_PATH, GT_PATH, ALT_DB]:
    if os.path.exists(path):
        print("OK:", path)
    else:
        raise FileNotFoundError(path)

# ---------------------------------------------------------------
# LOAD SOURCE-1
# ---------------------------------------------------------------
print("\nLoading Source-1...")

s1 = pd.read_csv(
    SOURCE1_PATH,
    sep="\t",
    nrows=10000,
    dtype=str
).fillna("")

print("Source-1 records:", len(s1))

# ---------------------------------------------------------------
# LOAD ALIGNED GROUND TRUTH
# ---------------------------------------------------------------
print("\nLoading aligned ground truth...")

gt = pd.read_csv(
    GT_PATH,
    sep="\t",
    dtype=str
).fillna("")

test_ids = set(s1["entity_id"])
gt = gt[gt["source1_entity_id"].isin(test_ids)]

true_pairs = set()

for _, row in gt.iterrows():

    s1_id = row["source1_entity_id"]
    matched = row["matched_entity_ids"]

    if not matched:
        continue

    for target_id in matched.split(","):
        target_id = target_id.strip()

        if target_id:
            true_pairs.add((s1_id, target_id))

print("Ground-truth positive pairs:", len(true_pairs))

# ---------------------------------------------------------------
# CONNECT SQLITE
# ---------------------------------------------------------------
print("\nConnecting alternative SQLite index...")

conn = sqlite3.connect(ALT_DB)

# ---------------------------------------------------------------
# TEST NAME2
# ---------------------------------------------------------------
print("\n" + "=" * 70)
print("TESTING C: name2")
print("=" * 70)

candidate_count = 0
captured_pairs = set()

start_time = time.time()

for i, row in s1.iterrows():

    s1_id = row["entity_id"]

    name = str(row["business_name"]).strip().lower()

    tokens = [
        t.strip()
        for t in name.replace("|", " ").split()
        if t.strip()
    ]

    if len(tokens) < 2:
        continue

    token1 = tokens[0]
    token2 = tokens[1]

    block_key = f"name2|{token1}|{token2}"

    rows = conn.execute(
        """
        SELECT entity_id
        FROM alternative_blocks
        WHERE block_type = ?
          AND block_key = ?
        """,
        ("C", block_key)
    ).fetchall()

    candidate_count += len(rows)

    for (candidate_id,) in rows:

        if (s1_id, candidate_id) in true_pairs:
            captured_pairs.add((s1_id, candidate_id))

    if (i + 1) % 1000 == 0:

        elapsed = (time.time() - start_time) / 60

        print(
            f"Processed: {i+1:,} | "
            f"Candidates: {candidate_count:,} | "
            f"Time: {elapsed:.2f} min"
        )

# ---------------------------------------------------------------
# RESULTS
# ---------------------------------------------------------------
captured = len(captured_pairs)
total_true = len(true_pairs)
missed = total_true - captured

pair_recall = (
    captured / total_true * 100
    if total_true else 0
)

true_records = {
    x[0] for x in true_pairs
}

captured_records = {
    x[0] for x in captured_pairs
}

record_recall = (
    len(captured_records) / len(true_records) * 100
    if true_records else 0
)

elapsed = (time.time() - start_time) / 60

print("\n" + "=" * 70)
print("NAME2 FULL 10K RESULTS")
print("=" * 70)

print("Test records:", len(s1))
print(f"Candidate rows: {candidate_count:,}")
print(
    f"Average candidates/record: "
    f"{candidate_count / len(s1):.2f}"
)

print(f"Ground-truth pairs: {total_true:,}")
print(f"Captured true pairs: {captured:,}")
print(f"Missed true pairs: {missed:,}")

print(f"\nPair-level recall: {pair_recall:.2f}%")

print(
    f"Records with >=1 true match: "
    f"{len(true_records):,}"
)

print(
    f"Records with >=1 capture: "
    f"{len(captured_records):,}"
)

print(f"Record-level recall: {record_recall:.2f}%")

print(f"\nTime taken: {elapsed:.2f} minutes")

print("\n" + "=" * 70)
print("CELL 45 COMPLETE")
print("=" * 70)

conn.close()

======================================================================
CELL 45 - NAME2 FULL 10K RECALL TEST
======================================================================
OK: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/processed_data/cleaned_train_source1.tsv
OK: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ground_truth_aligned_10k.tsv
OK: /content/alternative_blocking_test.db

Loading Source-1...
Source-1 records: 10000

Loading aligned ground truth...
Ground-truth positive pairs: 34752

Connecting alternative SQLite index...

======================================================================
TESTING C: name2
======================================================================
Processed: 1,000 | Candidates: 416,369 | Time: 0.03 min
Processed: 2,000 | Candidates: 929,465 | Time: 0.08 min
Processed: 4,000 | Candidates: 1,788,584 | Time: 0.18 min
Processed: 5,000 | Candidates: 2,390,781 | Time: 0.24 min
Processed: 6,000 | Candidates: 2,877,286 | Time: 0.28 min
Processed: 7,000 | Candidates: 3,397,195 | Time: 0.33 min
Processed: 8,000 | Candidates: 3,889,123 | Time: 0.37 min
Processed: 9,000 | Candidates: 4,493,686 | Time: 0.44 min

======================================================================
NAME2 FULL 10K RESULTS
======================================================================
Test records: 10000
Candidate rows: 4,983,364
Average candidates/record: 498.34
Ground-truth pairs: 34,752
Captured true pairs: 15,903
Missed true pairs: 18,849

Pair-level recall: 45.76%
Records with >=1 true match: 9,440
Records with >=1 capture: 7,004
Record-level recall: 74.19%

Time taken: 0.49 minutes

======================================================================
CELL 45 COMPLETE
======================================================================

In [ ]:
# ================================================================
# CELL 46 - OPTIMIZED COMBINED ALTERNATIVE BLOCKING TEST
# name_first + name2
# ================================================================

import os
import sqlite3
import pandas as pd
import re
import time

print("=" * 70)
print("CELL 46 - OPTIMIZED COMBINED BLOCKING TEST")
print("=" * 70)

# ------------------------------------------------
# PATHS
# ------------------------------------------------
SOURCE1_PATH = (
    "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/"
    "student_resource/processed_data/cleaned_train_source1.tsv"
)

GT_PATH = (
    "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/"
    "student_resource/blocking/candidates/ground_truth_aligned_10k.tsv"
)

DB_PATH = "/content/alternative_blocking_test.db"

# ------------------------------------------------
# FILE CHECK
# ------------------------------------------------
for path in [SOURCE1_PATH, GT_PATH, DB_PATH]:
    if not os.path.exists(path):
        raise FileNotFoundError(f"Missing: {path}")

print("All required files: OK")

# ------------------------------------------------
# LOAD SOURCE-1
# ------------------------------------------------
print("\nLoading Source-1...")

s1 = pd.read_csv(
    SOURCE1_PATH,
    sep="\t",
    nrows=10000,
    dtype=str
).fillna("")

print("Source-1 records:", len(s1))

# ------------------------------------------------
# LOAD GROUND TRUTH
# ------------------------------------------------
print("\nLoading aligned ground truth...")

gt = pd.read_csv(
    GT_PATH,
    sep="\t",
    dtype=str
).fillna("")

print("Ground-truth records:", len(gt))

# ------------------------------------------------
# BUILD TRUE POSITIVE PAIR SET
# ------------------------------------------------
true_pairs = set()
records_with_true_match = set()

for _, row in gt.iterrows():

    s1_id = str(row["source1_entity_id"]).strip()
    matched = str(row["matched_entity_ids"]).strip()

    if not matched or matched.lower() == "nan":
        continue

    ids = [
        x.strip()
        for x in matched.split(",")
        if x.strip()
    ]

    for target_id in ids:
        true_pairs.add((s1_id, target_id))

    if ids:
        records_with_true_match.add(s1_id)

print("Ground-truth positive pairs:", len(true_pairs))
print("Source-1 records with true matches:",
      len(records_with_true_match))

# ------------------------------------------------
# NORMALIZATION FUNCTION
# ------------------------------------------------
def normalize_text(value):
    value = str(value).lower()
    value = re.sub(r"[^a-z0-9]+", " ", value)
    value = re.sub(r"\s+", " ", value).strip()
    return value


# ------------------------------------------------
# CREATE SAME ALTERNATIVE KEYS
# ------------------------------------------------
print("\nCreating Source-1 alternative keys...")

test_keys = []

for _, row in s1.iterrows():

    source1_id = str(row["entity_id"]).strip()

    name = normalize_text(row["business_name"])

    tokens = name.split()

    # -------------------------------
    # Strategy A: name_first
    # -------------------------------
    if len(tokens) >= 1:
        first_token = tokens[0]

        test_keys.append(
            (
                source1_id,
                "A",
                f"name_first|{first_token}"
            )
        )

    # -------------------------------
    # Strategy C: name2
    # -------------------------------
    if len(tokens) >= 2:
        token1 = tokens[0]
        token2 = tokens[1]

        test_keys.append(
            (
                source1_id,
                "C",
                f"name2|{token1}|{token2}"
            )
        )

print("Alternative keys created:", len(test_keys))

# ------------------------------------------------
# CONNECT SQLITE
# ------------------------------------------------
print("\nConnecting alternative SQLite index...")

conn = sqlite3.connect(DB_PATH)

print("SQLite connected.")

# ------------------------------------------------
# CREATE TEMPORARY SOURCE-1 KEY TABLE
# ------------------------------------------------
print("\nCreating temporary key table...")

conn.execute("DROP TABLE IF EXISTS temp_test_keys")

conn.execute("""
CREATE TEMP TABLE temp_test_keys (
    source1_id TEXT,
    block_type TEXT,
    block_key TEXT
)
""")

conn.executemany(
    """
    INSERT INTO temp_test_keys
    (source1_id, block_type, block_key)
    VALUES (?, ?, ?)
    """,
    test_keys
)

conn.execute("""
CREATE INDEX idx_temp_test_keys
ON temp_test_keys(block_type, block_key)
""")

conn.commit()

print("Temporary key index created.")

# ------------------------------------------------
# VERIFY ALTERNATIVE INDEX
# ------------------------------------------------
print("\nChecking alternative index...")

index_count = conn.execute("""
SELECT COUNT(*)
FROM alternative_blocks
""").fetchone()[0]

print("Alternative index rows:", f"{index_count:,}")

# ------------------------------------------------
# OPTIMIZED JOIN
# ------------------------------------------------
print("\nRunning optimized SQLite JOIN...")
print("No large candidate list will be stored in RAM.")

start_time = time.time()

query = """
SELECT DISTINCT
       k.source1_id,
       b.entity_id
FROM temp_test_keys k
JOIN alternative_blocks b
  ON k.block_type = b.block_type
 AND k.block_key = b.block_key
"""

cursor = conn.execute(query)

# ------------------------------------------------
# PROCESS JOIN RESULTS IN CHUNKS
# ------------------------------------------------
captured_pairs = set()
candidate_pair_count = 0

CHUNK_SIZE = 100000

while True:

    rows = cursor.fetchmany(CHUNK_SIZE)

    if not rows:
        break

    candidate_pair_count += len(rows)

    for source1_id, target_id in rows:

        pair = (
            str(source1_id),
            str(target_id)
        )

        if pair in true_pairs:
            captured_pairs.add(pair)

    if candidate_pair_count % 1000000 < CHUNK_SIZE:

        elapsed = (time.time() - start_time) / 60

        print(
            f"Processed candidate pairs: "
            f"{candidate_pair_count:,} | "
            f"Captured true pairs: "
            f"{len(captured_pairs):,} | "
            f"Time: {elapsed:.2f} min"
        )

# ------------------------------------------------
# CALCULATE RECALL
# ------------------------------------------------
missed_pairs = len(true_pairs) - len(captured_pairs)

if len(true_pairs) > 0:
    pair_recall = (
        len(captured_pairs)
        / len(true_pairs)
        * 100
    )
else:
    pair_recall = 0.0

captured_records = {
    pair[0]
    for pair in captured_pairs
}

record_recall = (
    len(captured_records)
    / len(records_with_true_match)
    * 100
    if records_with_true_match
    else 0.0
)

avg_candidates = (
    candidate_pair_count / len(s1)
    if len(s1) > 0
    else 0
)

elapsed = (time.time() - start_time) / 60

# ------------------------------------------------
# FINAL RESULTS
# ------------------------------------------------
print("\n")
print("=" * 70)
print("OPTIMIZED COMBINED RESULTS")
print("=" * 70)

print(f"Test records                  : {len(s1):,}")
print(f"Candidate pairs               : {candidate_pair_count:,}")
print(f"Average candidates/record     : {avg_candidates:.2f}")

print(f"Ground-truth positive pairs   : {len(true_pairs):,}")
print(f"Captured true pairs           : {len(captured_pairs):,}")
print(f"Missed true pairs             : {missed_pairs:,}")

print(f"Pair-level recall             : {pair_recall:.2f}%")

print(f"Records with >=1 true match   : "
      f"{len(records_with_true_match):,}")

print(f"Records with >=1 capture      : "
      f"{len(captured_records):,}")

print(f"Record-level recall           : "
      f"{record_recall:.2f}%")

print(f"Time taken                    : "
      f"{elapsed:.2f} minutes")

print("=" * 70)

# ------------------------------------------------
# COMPARE WITH BASELINES
# ------------------------------------------------
print("\nBASELINE COMPARISON")
print("-" * 70)

print("Original country|token:")
print("  Pair recall   : 8.23%")
print("  Record recall : 10.36%")

print("\nname_first:")
print("  Pair recall   : 38.55%")
print("  Record recall : 54.36%")

print("\nname2:")
print("  Pair recall   : 45.76%")
print("  Record recall : 74.19%")

print("\nCombined name_first + name2:")
print(f"  Pair recall   : {pair_recall:.2f}%")
print(f"  Record recall : {record_recall:.2f}%")

print("=" * 70)

conn.close()

print("\n======================================================================")
print("CELL 46 COMPLETE")
print("======================================================================")

======================================================================
CELL 46 - OPTIMIZED COMBINED BLOCKING TEST
======================================================================
All required files: OK

Loading Source-1...
Source-1 records: 10000

Loading aligned ground truth...
Ground-truth records: 10000
Ground-truth positive pairs: 34752
Source-1 records with true matches: 9440

Creating Source-1 alternative keys...
Alternative keys created: 19943

Connecting alternative SQLite index...
SQLite connected.

Creating temporary key table...
Temporary key index created.

Checking alternative index...
Alternative index rows: 28,557,205

Running optimized SQLite JOIN...
No large candidate list will be stored in RAM.
Processed candidate pairs: 1,000,000 | Captured true pairs: 375 | Time: 0.12 min
Processed candidate pairs: 2,000,000 | Captured true pairs: 796 | Time: 0.25 min
Processed candidate pairs: 3,000,000 | Captured true pairs: 1,201 | Time: 0.37 min
Processed candidate pairs: 4,000,000 | Captured true pairs: 1,606 | Time: 0.51 min
Processed candidate pairs: 5,000,000 | Captured true pairs: 2,024 | Time: 0.63 min
Processed candidate pairs: 6,000,000 | Captured true pairs: 2,460 | Time: 0.76 min
Processed candidate pairs: 7,000,000 | Captured true pairs: 2,958 | Time: 0.89 min
Processed candidate pairs: 8,000,000 | Captured true pairs: 3,358 | Time: 1.04 min
Processed candidate pairs: 9,000,000 | Captured true pairs: 3,688 | Time: 1.17 min
Processed candidate pairs: 10,000,000 | Captured true pairs: 4,071 | Time: 1.30 min
Processed candidate pairs: 11,000,000 | Captured true pairs: 4,533 | Time: 1.43 min
Processed candidate pairs: 12,000,000 | Captured true pairs: 4,928 | Time: 1.55 min
Processed candidate pairs: 13,000,000 | Captured true pairs: 5,438 | Time: 1.70 min
Processed candidate pairs: 14,000,000 | Captured true pairs: 5,861 | Time: 1.81 min
Processed candidate pairs: 15,000,000 | Captured true pairs: 6,184 | Time: 1.96 min
Processed candidate pairs: 16,000,000 | Captured true pairs: 6,649 | Time: 2.07 min
Processed candidate pairs: 17,000,000 | Captured true pairs: 7,065 | Time: 2.22 min
Processed candidate pairs: 18,000,000 | Captured true pairs: 7,605 | Time: 2.33 min
Processed candidate pairs: 19,000,000 | Captured true pairs: 7,917 | Time: 2.47 min
Processed candidate pairs: 20,000,000 | Captured true pairs: 8,307 | Time: 2.59 min
Processed candidate pairs: 21,000,000 | Captured true pairs: 8,687 | Time: 2.73 min
Processed candidate pairs: 22,000,000 | Captured true pairs: 9,049 | Time: 2.84 min
Processed candidate pairs: 23,000,000 | Captured true pairs: 9,345 | Time: 2.99 min
Processed candidate pairs: 24,000,000 | Captured true pairs: 9,765 | Time: 3.13 min
Processed candidate pairs: 25,000,000 | Captured true pairs: 10,152 | Time: 3.27 min
Processed candidate pairs: 26,000,000 | Captured true pairs: 10,591 | Time: 3.40 min
Processed candidate pairs: 27,000,000 | Captured true pairs: 10,973 | Time: 3.54 min
Processed candidate pairs: 28,000,000 | Captured true pairs: 11,410 | Time: 3.67 min
Processed candidate pairs: 29,000,000 | Captured true pairs: 11,764 | Time: 3.80 min
Processed candidate pairs: 30,000,000 | Captured true pairs: 12,111 | Time: 3.95 min
Processed candidate pairs: 31,000,000 | Captured true pairs: 12,419 | Time: 4.07 min
Processed candidate pairs: 32,000,000 | Captured true pairs: 12,782 | Time: 4.22 min
Processed candidate pairs: 33,000,000 | Captured true pairs: 13,202 | Time: 4.34 min
Processed candidate pairs: 34,000,000 | Captured true pairs: 13,572 | Time: 4.48 min
Processed candidate pairs: 35,000,000 | Captured true pairs: 13,962 | Time: 4.60 min
Processed candidate pairs: 36,000,000 | Captured true pairs: 14,465 | Time: 4.75 min
Processed candidate pairs: 37,000,000 | Captured true pairs: 14,792 | Time: 4.86 min
Processed candidate pairs: 38,000,000 | Captured true pairs: 15,288 | Time: 5.01 min
Processed candidate pairs: 39,000,000 | Captured true pairs: 15,695 | Time: 5.18 min
Processed candidate pairs: 40,000,000 | Captured true pairs: 16,173 | Time: 5.30 min
Processed candidate pairs: 41,000,000 | Captured true pairs: 16,530 | Time: 5.44 min
Processed candidate pairs: 42,000,000 | Captured true pairs: 16,869 | Time: 5.56 min
Processed candidate pairs: 43,000,000 | Captured true pairs: 17,233 | Time: 5.71 min
Processed candidate pairs: 44,000,000 | Captured true pairs: 17,636 | Time: 5.83 min
Processed candidate pairs: 45,000,000 | Captured true pairs: 18,028 | Time: 5.98 min
Processed candidate pairs: 46,000,000 | Captured true pairs: 18,434 | Time: 6.10 min
Processed candidate pairs: 47,000,000 | Captured true pairs: 18,806 | Time: 6.24 min
Processed candidate pairs: 48,000,000 | Captured true pairs: 19,169 | Time: 6.36 min
Processed candidate pairs: 49,000,000 | Captured true pairs: 19,443 | Time: 6.50 min
Processed candidate pairs: 50,000,000 | Captured true pairs: 19,784 | Time: 6.62 min
Processed candidate pairs: 51,000,000 | Captured true pairs: 20,172 | Time: 6.77 min
Processed candidate pairs: 52,000,000 | Captured true pairs: 20,555 | Time: 6.90 min
Processed candidate pairs: 53,000,000 | Captured true pairs: 20,916 | Time: 7.04 min
Processed candidate pairs: 54,000,000 | Captured true pairs: 21,282 | Time: 7.19 min
Processed candidate pairs: 55,000,000 | Captured true pairs: 21,669 | Time: 7.32 min
Processed candidate pairs: 56,000,000 | Captured true pairs: 22,065 | Time: 7.59 min
Processed candidate pairs: 57,000,000 | Captured true pairs: 22,465 | Time: 7.72 min
Processed candidate pairs: 58,000,000 | Captured true pairs: 22,853 | Time: 7.87 min
Processed candidate pairs: 59,000,000 | Captured true pairs: 23,212 | Time: 8.01 min
Processed candidate pairs: 60,000,000 | Captured true pairs: 23,532 | Time: 8.14 min
Processed candidate pairs: 61,000,000 | Captured true pairs: 24,025 | Time: 8.30 min
Processed candidate pairs: 62,000,000 | Captured true pairs: 24,413 | Time: 8.42 min
Processed candidate pairs: 63,000,000 | Captured true pairs: 24,901 | Time: 8.58 min
Processed candidate pairs: 64,000,000 | Captured true pairs: 25,247 | Time: 8.70 min
Processed candidate pairs: 64,047,085 | Captured true pairs: 25,297 | Time: 8.71 min


======================================================================
OPTIMIZED COMBINED RESULTS
======================================================================
Test records                  : 10,000
Candidate pairs               : 64,047,085
Average candidates/record     : 6404.71
Ground-truth positive pairs   : 34,752
Captured true pairs           : 25,297
Missed true pairs             : 9,455
Pair-level recall             : 72.79%
Records with >=1 true match   : 9,440
Records with >=1 capture      : 8,926
Record-level recall           : 94.56%
Time taken                    : 8.71 minutes
======================================================================

BASELINE COMPARISON
----------------------------------------------------------------------
Original country|token:
  Pair recall   : 8.23%
  Record recall : 10.36%

name_first:
  Pair recall   : 38.55%
  Record recall : 54.36%

name2:
  Pair recall   : 45.76%
  Record recall : 74.19%

Combined name_first + name2:
  Pair recall   : 72.79%
  Record recall : 94.56%
======================================================================

======================================================================
CELL 46 COMPLETE
======================================================================

In [ ]:
# ================================================================
# CELL 47 - FAST BLOCKING KEY STATISTICS
# ================================================================

import sqlite3
import pandas as pd

print("=" * 70)
print("CELL 47 - FAST BLOCKING KEY STATISTICS")
print("=" * 70)

DB = "/content/alternative_blocking_test.db"

print("\nConnecting SQLite...")
conn = sqlite3.connect(DB)

# ------------------------------------------------
# CHECK INDEX
# ------------------------------------------------
print("\nChecking alternative index...")

tables = pd.read_sql_query("""
SELECT name
FROM sqlite_master
WHERE type='table'
""", conn)

print(tables)

# ------------------------------------------------
# BLOCK TYPE DISTRIBUTION
# ------------------------------------------------
print("\n" + "=" * 60)
print("BLOCK TYPE DISTRIBUTION")
print("=" * 60)

df = pd.read_sql_query("""
SELECT
    block_type,
    source,
    COUNT(*) AS index_rows,
    COUNT(DISTINCT block_key) AS unique_keys
FROM alternative_blocks
GROUP BY block_type, source
ORDER BY block_type, source
""", conn)

print(df.to_string(index=False))

# ------------------------------------------------
# KEY SIZE DISTRIBUTION
# ------------------------------------------------
print("\n" + "=" * 60)
print("KEY FREQUENCY DISTRIBUTION")
print("=" * 60)

freq = pd.read_sql_query("""
SELECT
    block_type,
    source,
    COUNT(*) AS total_rows,
    COUNT(DISTINCT block_key) AS unique_keys,
    ROUND(
        CAST(COUNT(*) AS REAL) /
        COUNT(DISTINCT block_key), 2
    ) AS avg_rows_per_key
FROM alternative_blocks
GROUP BY block_type, source
ORDER BY block_type, source
""", conn)

print(freq.to_string(index=False))

# ------------------------------------------------
# TOP LARGE KEYS
# ------------------------------------------------
for block_type in ["A", "C"]:

    print("\n" + "=" * 60)
    print(f"LARGEST {block_type} BLOCKS")
    print("=" * 60)

    large = pd.read_sql_query("""
        SELECT
            block_key,
            source,
            COUNT(*) AS rows
        FROM alternative_blocks
        WHERE block_type = ?
        GROUP BY block_key, source
        ORDER BY rows DESC
        LIMIT 15
    """, conn, params=(block_type,))

    print(large.to_string(index=False))

# ------------------------------------------------
# CLOSE
# ------------------------------------------------
conn.close()

print("\n" + "=" * 70)
print("CELL 47 COMPLETE")
print("=" * 70)

print("""
IMPORTANT:
- No candidate pairs generated.
- No 64M pair scan.
- No large RAM operation.
- No database modification.

These statistics will be used to design the next
candidate-reduction strategy.
""")

======================================================================
CELL 47 - FAST BLOCKING KEY STATISTICS
======================================================================

Connecting SQLite...

Checking alternative index...
                 name
0  alternative_blocks

============================================================
BLOCK TYPE DISTRIBUTION
============================================================
block_type  source  index_rows  unique_keys
         A source2     4578854       335136
         A source3     5041960       374604
         B source2     4578854       223479
         B source3     5041960       238576
         C source2     4465215      1885478
         C source3     4850362      1988013

============================================================
KEY FREQUENCY DISTRIBUTION
============================================================
block_type  source  total_rows  unique_keys  avg_rows_per_key
         A source2     4578854       335136             13.66
         A source3     5041960       374604             13.46
         B source2     4578854       223479             20.49
         B source3     5041960       238576             21.13
         C source2     4465215      1885478              2.37
         C source3     4850362      1988013              2.44

============================================================
LARGEST A BLOCKS
============================================================
           block_key  source  rows
      name_first|the source3 53608
  name_first|private source3 48400
      name_first|the source2 42317
      name_first|llc source3 41252
  name_first|private source2 40350
      name_first|llc source2 40294
        name_first|m source3 32246
name_first|pediatric source3 29824
       name_first|mr source3 29462
      name_first|sri source3 29360
name_first|pediatric source2 29328
       name_first|dr source3 29309
      name_first|smt source3 29278
     name_first|shri source3 29199
        name_first|m source2 28489

============================================================
LARGEST C BLOCKS
============================================================
                block_key  source  rows
                name2|m|s source3 29337
                name2|m|s source2 25712
           name2|ear|nose source3  9016
           name2|ear|nose source2  8874
   name2|physical|therapy source2  8488
       name2|primary|care source3  8461
   name2|physical|therapy source3  8425
       name2|primary|care source2  8423
   name2|pediatric|dental source2  8366
name2|pediatric|dentistry source3  8327
name2|pediatric|dentistry source2  8315
   name2|pediatric|dental source3  8294
  name2|behavioral|health source2  8168
      name2|womens|health source2  8059
        name2|urgent|care source2  7979

======================================================================
CELL 47 COMPLETE
======================================================================

IMPORTANT:
- No candidate pairs generated.
- No 64M pair scan.
- No large RAM operation.
- No database modification.

These statistics will be used to design the next
candidate-reduction strategy.

In [ ]:
# ================================================================
# CELL 48 - FAST COMMON-KEY FILTER TEST
# ================================================================

import sqlite3
import pandas as pd
import time

print("=" * 70)
print("CELL 48 - FAST COMMON-KEY FILTER TEST")
print("=" * 70)

DB_PATH = "/content/alternative_blocking_test.db"

GT_PATH = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ground_truth_aligned_10k.tsv"

SOURCE1_PATH = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/processed_data/cleaned_train_source1.tsv"

# ------------------------------------------------
# Load Source-1
# ------------------------------------------------
print("\nLoading Source-1...")

s1 = pd.read_csv(
    SOURCE1_PATH,
    sep="\t",
    nrows=10000,
    dtype=str
).fillna("")

print("Source-1 records:", len(s1))

# ------------------------------------------------
# Load Ground Truth
# ------------------------------------------------
print("\nLoading ground truth...")

gt = pd.read_csv(
    GT_PATH,
    sep="\t",
    dtype=str
).fillna("")

# Build true pair set
true_pairs = set()

for _, row in gt.iterrows():

    s1_id = row["source1_entity_id"]

    matched = str(row["matched_entity_ids"])

    if not matched or matched == "nan":
        continue

    for target_id in matched.split(","):

        target_id = target_id.strip()

        if target_id:
            true_pairs.add((s1_id, target_id))

print("Ground-truth positive pairs:", len(true_pairs))

# ------------------------------------------------
# Connect SQLite
# ------------------------------------------------
print("\nConnecting SQLite...")

conn = sqlite3.connect(DB_PATH)

# ------------------------------------------------
# Check key frequencies
# ------------------------------------------------
print("\nReading key frequencies...")

freq = pd.read_sql_query("""
    SELECT
        block_type,
        source,
        block_key,
        COUNT(*) AS frequency
    FROM alternative_blocks
    GROUP BY block_type, source, block_key
""", conn)

print("Unique keys loaded:", len(freq))

# ------------------------------------------------
# Frequency thresholds
# ------------------------------------------------
thresholds = {
    "A": 1000,   # name_first
    "C": 1000    # name2
}

print("\nFrequency thresholds:")
print("name_first (A) :", thresholds["A"])
print("name2      (C) :", thresholds["C"])

# ------------------------------------------------
# Source-1 key creation
# ------------------------------------------------
def clean_text(x):
    return (
        str(x)
        .lower()
        .strip()
        .replace("|", " ")
    )

def make_tokens(text):
    return [
        x for x in clean_text(text).split()
        if x
    ]

source_keys = {}

for _, row in s1.iterrows():

    sid = row["entity_id"]

    tokens = make_tokens(row["business_name"])

    if not tokens:
        source_keys[sid] = []
        continue

    keys = set()

    # A: first token
    keys.add(("A", "name_first|" + tokens[0]))

    # C: first two tokens
    if len(tokens) >= 2:
        keys.add(("C", "name2|" + tokens[0] + "|" + tokens[1]))

    source_keys[sid] = list(keys)

print("\nSource-1 keys created.")

# ------------------------------------------------
# Build allowed keys
# ------------------------------------------------
allowed_keys = set()

for _, row in freq.iterrows():

    bt = row["block_type"]
    key = row["block_key"]
    frequency = int(row["frequency"])

    if bt in ["A", "C"]:

        if frequency <= thresholds[bt]:
            allowed_keys.add((bt, key))

print("Allowed keys:", len(allowed_keys))

# ------------------------------------------------
# TEST
# ------------------------------------------------
print("\n" + "=" * 70)
print("TESTING FILTERED A + C")
print("=" * 70)

start = time.time()

candidate_pairs = set()
captured = set()

processed = 0

for sid, keys in source_keys.items():

    for bt, key in keys:

        if (bt, key) not in allowed_keys:
            continue

        rows = conn.execute("""
            SELECT entity_id
            FROM alternative_blocks
            WHERE block_type = ?
              AND block_key = ?
        """, (bt, key)).fetchall()

        for (target_id,) in rows:

            pair = (sid, target_id)

            candidate_pairs.add(pair)

            if pair in true_pairs:
                captured.add(pair)

    processed += 1

    if processed % 1000 == 0:
        elapsed = (time.time() - start) / 60

        print(
            f"Processed: {processed:,} | "
            f"Candidates: {len(candidate_pairs):,} | "
            f"Captured: {len(captured):,} | "
            f"Time: {elapsed:.2f} min"
        )

# ------------------------------------------------
# Recall calculation
# ------------------------------------------------
missed = len(true_pairs - captured)

pair_recall = (
    len(captured) / len(true_pairs) * 100
    if true_pairs else 0
)

true_records = set(x[0] for x in true_pairs)
captured_records = set(x[0] for x in captured)

record_recall = (
    len(captured_records) / len(true_records) * 100
    if true_records else 0
)

elapsed = (time.time() - start) / 60

# ------------------------------------------------
# Results
# ------------------------------------------------
print("\n" + "=" * 70)
print("CELL 48 RESULTS")
print("=" * 70)

print(f"Candidate pairs          : {len(candidate_pairs):,}")
print(f"Average candidates/record: {len(candidate_pairs)/10000:.2f}")

print(f"Ground-truth pairs       : {len(true_pairs):,}")
print(f"Captured true pairs      : {len(captured):,}")
print(f"Missed true pairs        : {missed:,}")

print(f"\nPair-level recall        : {pair_recall:.2f}%")

print(f"Records with true match  : {len(true_records):,}")
print(f"Records with capture     : {len(captured_records):,}")

print(f"Record-level recall      : {record_recall:.2f}%")

print(f"\nTime taken               : {elapsed:.2f} minutes")

print("\n" + "=" * 70)
print("BASELINE")
print("=" * 70)

print("Original country|token : Pair 8.23% | Record 10.36%")
print("name_first             : Pair 38.55% | Record 54.36%")
print("name2                  : Pair 45.76% | Record 74.19%")
print("Combined A+C           : Pair 72.79% | Record 94.56%")

print("=" * 70)
print("CELL 48 COMPLETE")
print("=" * 70)

conn.close()

======================================================================
CELL 48 - FAST COMMON-KEY FILTER TEST
======================================================================

Loading Source-1...
Source-1 records: 10000

Loading ground truth...
Ground-truth positive pairs: 34752

Connecting SQLite...

Reading key frequencies...
Unique keys loaded: 5045286

Frequency thresholds:
name_first (A) : 1000
name2      (C) : 1000

Source-1 keys created.
Allowed keys: 3604665

======================================================================
TESTING FILTERED A + C
======================================================================
Processed: 1,000 | Candidates: 188,137 | Captured: 1,990 | Time: 0.10 min
Processed: 2,000 | Candidates: 369,350 | Captured: 3,919 | Time: 0.13 min
Processed: 3,000 | Candidates: 552,221 | Captured: 5,902 | Time: 0.15 min
Processed: 4,000 | Candidates: 718,319 | Captured: 7,781 | Time: 0.17 min
Processed: 5,000 | Candidates: 888,502 | Captured: 9,711 | Time: 0.18 min
Processed: 6,000 | Candidates: 1,086,649 | Captured: 11,772 | Time: 0.21 min
Processed: 7,000 | Candidates: 1,270,684 | Captured: 13,723 | Time: 0.23 min
Processed: 8,000 | Candidates: 1,453,536 | Captured: 15,625 | Time: 0.24 min
Processed: 9,000 | Candidates: 1,624,985 | Captured: 17,560 | Time: 0.26 min
Processed: 10,000 | Candidates: 1,791,624 | Captured: 19,468 | Time: 0.28 min

======================================================================
CELL 48 RESULTS
======================================================================
Candidate pairs          : 1,791,624
Average candidates/record: 179.16
Ground-truth pairs       : 34,752
Captured true pairs      : 19,468
Missed true pairs        : 15,284

Pair-level recall        : 56.02%
Records with true match  : 9,440
Records with capture     : 7,482
Record-level recall      : 79.26%

Time taken               : 0.28 minutes

======================================================================
BASELINE
======================================================================
Original country|token : Pair 8.23% | Record 10.36%
name_first             : Pair 38.55% | Record 54.36%
name2                  : Pair 45.76% | Record 74.19%
Combined A+C           : Pair 72.79% | Record 94.56%
======================================================================
CELL 48 COMPLETE
======================================================================

In [ ]:
# ============================================================
# CELL 49 - FAST FREQUENCY THRESHOLD OPTIMIZATION
# ============================================================

import sqlite3
import pandas as pd
import time
from collections import defaultdict

print("=" * 70)
print("CELL 49 - FAST FREQUENCY THRESHOLD OPTIMIZATION")
print("=" * 70)

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------
SOURCE1 = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/processed_data/cleaned_train_source1.tsv"

GT_PATH = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ground_truth_aligned_10k.tsv"

DB_PATH = "/content/alternative_blocking_test.db"

# ------------------------------------------------------------
# LOAD SOURCE-1
# ------------------------------------------------------------
print("\nLoading Source-1...")
s1 = pd.read_csv(SOURCE1, sep="\t", dtype=str).fillna("")
s1 = s1.iloc[:10000].copy()

print("Source-1 records:", len(s1))

# ------------------------------------------------------------
# LOAD GROUND TRUTH
# ------------------------------------------------------------
print("\nLoading ground truth...")
gt = pd.read_csv(GT_PATH, sep="\t", dtype=str).fillna("")

# Build true pairs
true_pairs = set()
true_records = set()

for _, row in gt.iterrows():

    sid = row["source1_entity_id"]
    matched = str(row["matched_entity_ids"]).strip()

    if not matched or matched.lower() == "nan":
        continue

    for tid in matched.split(","):

        tid = tid.strip()

        if not tid:
            continue

        true_pairs.add((sid, tid))
        true_records.add(sid)

print("Ground-truth positive pairs:", len(true_pairs))
print("Source-1 records with true matches:", len(true_records))

# ------------------------------------------------------------
# CREATE SOURCE-1 KEYS
# ------------------------------------------------------------
print("\nCreating Source-1 keys...")

def tokenize(text):
    import re

    text = str(text).lower()
    text = re.sub(r"[^a-z0-9]+", " ", text)

    return [x for x in text.split() if x]


def make_keys(name):

    tokens = tokenize(name)

    if not tokens:
        return []

    # A = first token
    key_a = "name_first|" + tokens[0]

    # C = first two tokens
    if len(tokens) >= 2:
        key_c = "name2|" + tokens[0] + "|" + tokens[1]
    else:
        key_c = "name2|" + tokens[0] + "|"

    return [("A", key_a), ("C", key_c)]


source1_keys = {}

for _, row in s1.iterrows():

    sid = row["entity_id"]

    keys = make_keys(row["business_name"])

    source1_keys[sid] = keys

print("Source-1 key sets created:", len(source1_keys))

# ------------------------------------------------------------
# CONNECT SQLITE
# ------------------------------------------------------------
print("\nConnecting SQLite...")

conn = sqlite3.connect(DB_PATH)

# ------------------------------------------------------------
# THRESHOLDS
# ------------------------------------------------------------
THRESHOLDS = [500, 1000, 2000, 5000, 10000]

results = []

# ------------------------------------------------------------
# TEST EACH THRESHOLD
# ------------------------------------------------------------
for threshold in THRESHOLDS:

    print("\n" + "=" * 60)
    print(f"TESTING FREQUENCY THRESHOLD = {threshold}")
    print("=" * 60)

    start = time.time()

    # --------------------------------------------------------
    # Get allowed keys
    # --------------------------------------------------------
    query = """
        SELECT block_type, block_key
        FROM alternative_blocks
        GROUP BY block_type, block_key
        HAVING COUNT(*) <= ?
    """

    allowed_rows = conn.execute(
        query,
        (threshold,)
    ).fetchall()

    allowed = set(
        (str(a), str(b))
        for a, b in allowed_rows
    )

    print("Allowed keys:", len(allowed))

    # --------------------------------------------------------
    # Candidate + recall calculation
    # --------------------------------------------------------
    candidate_pairs = 0
    captured_pairs = 0

    captured_records = set()

    # Avoid duplicate pair counting
    seen_pairs = set()

    processed = 0

    for sid, keys in source1_keys.items():

        for block_type, block_key in keys:

            if (block_type, block_key) not in allowed:
                continue

            rows = conn.execute(
                """
                SELECT entity_id
                FROM alternative_blocks
                WHERE block_type = ?
                  AND block_key = ?
                """,
                (block_type, block_key)
            ).fetchall()

            for (target_id,) in rows:

                pair = (sid, target_id)

                if pair in seen_pairs:
                    continue

                seen_pairs.add(pair)

                candidate_pairs += 1

                if pair in true_pairs:
                    captured_pairs += 1
                    captured_records.add(sid)

        processed += 1

        if processed % 2000 == 0:
            elapsed = (time.time() - start) / 60

            print(
                f"Processed: {processed:,} | "
                f"Candidates: {candidate_pairs:,} | "
                f"Captured: {captured_pairs:,} | "
                f"Time: {elapsed:.2f} min"
            )

    # --------------------------------------------------------
    # METRICS
    # --------------------------------------------------------
    missed_pairs = len(true_pairs) - captured_pairs

    pair_recall = (
        captured_pairs / len(true_pairs) * 100
        if true_pairs else 0
    )

    record_recall = (
        len(captured_records) / len(true_records) * 100
        if true_records else 0
    )

    avg_candidates = candidate_pairs / len(s1)

    elapsed = (time.time() - start) / 60

    print("\nRESULT")
    print("-" * 60)
    print("Threshold              :", threshold)
    print("Candidate pairs        :", f"{candidate_pairs:,}")
    print("Average candidates/record:", f"{avg_candidates:.2f}")
    print("Captured true pairs    :", f"{captured_pairs:,}")
    print("Missed true pairs      :", f"{missed_pairs:,}")
    print("Pair recall            :", f"{pair_recall:.2f}%")
    print("Record recall          :", f"{record_recall:.2f}%")
    print("Time                   :", f"{elapsed:.2f} min")

    results.append({
        "threshold": threshold,
        "candidate_pairs": candidate_pairs,
        "avg_candidates_per_record": round(avg_candidates, 2),
        "true_pairs": len(true_pairs),
        "captured_pairs": captured_pairs,
        "missed_pairs": missed_pairs,
        "pair_recall_percent": round(pair_recall, 2),
        "record_recall_percent": round(record_recall, 2),
        "time_minutes": round(elapsed, 2)
    })

# ------------------------------------------------------------
# FINAL SUMMARY
# ------------------------------------------------------------
result_df = pd.DataFrame(results)

print("\n" + "=" * 70)
print("CELL 49 - THRESHOLD OPTIMIZATION RESULTS")
print("=" * 70)

print(result_df.to_string(index=False))

# ------------------------------------------------------------
# SAVE RESULTS
# ------------------------------------------------------------
OUTPUT = "/content/threshold_optimization_10k.tsv"

result_df.to_csv(
    OUTPUT,
    sep="\t",
    index=False
)

print("\nResults saved to:")
print(OUTPUT)

conn.close()

print("\n" + "=" * 70)
print("CELL 49 COMPLETE")
print("=" * 70)

======================================================================
CELL 49 - FAST FREQUENCY THRESHOLD OPTIMIZATION
======================================================================

Loading Source-1...
Source-1 records: 10000

Loading ground truth...
Ground-truth positive pairs: 34752
Source-1 records with true matches: 9440

Creating Source-1 keys...
Source-1 key sets created: 10000

Connecting SQLite...

============================================================
TESTING FREQUENCY THRESHOLD = 500
============================================================
Allowed keys: 4011052
Processed: 2,000 | Candidates: 190,213 | Captured: 4,160 | Time: 0.30 min
Processed: 4,000 | Candidates: 368,076 | Captured: 8,234 | Time: 0.32 min
Processed: 6,000 | Candidates: 544,572 | Captured: 12,371 | Time: 0.35 min
Processed: 8,000 | Candidates: 718,086 | Captured: 16,434 | Time: 0.38 min
Processed: 10,000 | Candidates: 893,467 | Captured: 20,502 | Time: 0.40 min

RESULT
------------------------------------------------------------
Threshold              : 500
Candidate pairs        : 893,467
Average candidates/record: 89.35
Captured true pairs    : 20,502
Missed true pairs      : 14,250
Pair recall            : 59.00%
Record recall          : 84.14%
Time                   : 0.40 min

============================================================
TESTING FREQUENCY THRESHOLD = 1000
============================================================
Allowed keys: 4012784
Processed: 2,000 | Candidates: 273,442 | Captured: 4,302 | Time: 0.29 min
Processed: 4,000 | Candidates: 524,186 | Captured: 8,467 | Time: 0.31 min
Processed: 6,000 | Candidates: 787,691 | Captured: 12,756 | Time: 0.34 min
Processed: 8,000 | Candidates: 1,061,153 | Captured: 16,962 | Time: 0.37 min
Processed: 10,000 | Candidates: 1,319,980 | Captured: 21,153 | Time: 0.40 min

RESULT
------------------------------------------------------------
Threshold              : 1000
Candidate pairs        : 1,319,980
Average candidates/record: 132.00
Captured true pairs    : 21,153
Missed true pairs      : 13,599
Pair recall            : 60.87%
Record recall          : 86.06%
Time                   : 0.40 min

============================================================
TESTING FREQUENCY THRESHOLD = 2000
============================================================
Allowed keys: 4013259
Processed: 2,000 | Candidates: 405,466 | Captured: 4,377 | Time: 0.36 min
Processed: 4,000 | Candidates: 791,532 | Captured: 8,627 | Time: 0.40 min
Processed: 6,000 | Candidates: 1,190,360 | Captured: 13,001 | Time: 0.44 min
Processed: 8,000 | Candidates: 1,596,969 | Captured: 17,288 | Time: 0.48 min
Processed: 10,000 | Candidates: 1,978,448 | Captured: 21,568 | Time: 0.53 min

RESULT
------------------------------------------------------------
Threshold              : 2000
Candidate pairs        : 1,978,448
Average candidates/record: 197.84
Captured true pairs    : 21,568
Missed true pairs      : 13,184
Pair recall            : 62.06%
Record recall          : 86.95%
Time                   : 0.53 min

============================================================
TESTING FREQUENCY THRESHOLD = 5000
============================================================
Allowed keys: 4013620
Processed: 2,000 | Candidates: 845,780 | Captured: 4,480 | Time: 0.39 min
Processed: 4,000 | Candidates: 1,679,132 | Captured: 8,851 | Time: 0.48 min
Processed: 6,000 | Candidates: 2,521,125 | Captured: 13,323 | Time: 0.58 min
Processed: 8,000 | Candidates: 3,313,684 | Captured: 17,717 | Time: 0.65 min
Processed: 10,000 | Candidates: 4,193,976 | Captured: 22,124 | Time: 0.75 min

RESULT
------------------------------------------------------------
Threshold              : 5000
Candidate pairs        : 4,193,976
Average candidates/record: 419.40
Captured true pairs    : 22,124
Missed true pairs      : 12,628
Pair recall            : 63.66%
Record recall          : 87.93%
Time                   : 0.75 min

============================================================
TESTING FREQUENCY THRESHOLD = 10000
============================================================
Allowed keys: 4013835
Processed: 2,000 | Candidates: 3,005,261 | Captured: 4,652 | Time: 0.60 min
Processed: 4,000 | Candidates: 6,130,474 | Captured: 9,213 | Time: 0.91 min
Processed: 6,000 | Candidates: 9,280,441 | Captured: 13,882 | Time: 1.21 min
Processed: 8,000 | Candidates: 12,430,733 | Captured: 18,480 | Time: 1.55 min
Processed: 10,000 | Candidates: 15,708,797 | Captured: 23,096 | Time: 1.86 min

RESULT
------------------------------------------------------------
Threshold              : 10000
Candidate pairs        : 15,708,797
Average candidates/record: 1570.88
Captured true pairs    : 23,096
Missed true pairs      : 11,656
Pair recall            : 66.46%
Record recall          : 90.42%
Time                   : 1.86 min

======================================================================
CELL 49 - THRESHOLD OPTIMIZATION RESULTS
======================================================================
 threshold  candidate_pairs  avg_candidates_per_record  true_pairs  captured_pairs  missed_pairs  pair_recall_percent  record_recall_percent  time_minutes
       500           893467                      89.35       34752           20502         14250                59.00                  84.14          0.40
      1000          1319980                     132.00       34752           21153         13599                60.87                  86.06          0.40
      2000          1978448                     197.84       34752           21568         13184                62.06                  86.95          0.53
      5000          4193976                     419.40       34752           22124         12628                63.66                  87.93          0.75
     10000         15708797                    1570.88       34752           23096         11656                66.46                  90.42          1.86

Results saved to:
/content/threshold_optimization_10k.tsv

======================================================================
CELL 49 COMPLETE
======================================================================

In [ ]:
import gc

# Clear large variables from memory
for var in [
    "s1",
    "source1_keys",
    "batch_df",
    "buffer",
    "sample",
    "df",
    "ground_truth",
    "conn"
]:
    if var in globals():
        del globals()[var]

gc.collect()

print("RAM cleanup completed.")

RAM cleanup completed.

In [ ]:
# ================================================================
# CELL 50 - FAST BATCH CANDIDATE PREPARATION
# ================================================================

import os
import re
import gc
import sqlite3
import pandas as pd
import time

print("=" * 70)
print("CELL 50 - FAST BATCH CANDIDATE PREPARATION")
print("=" * 70)

# ------------------------------------------------
# PATHS
# ------------------------------------------------

BASE = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource"

SOURCE1 = f"{BASE}/processed_data/cleaned_train_source1.tsv"
GROUND_TRUTH = f"{BASE}/blocking/candidates/ground_truth_aligned_10k.tsv"
ALT_DB = "/content/alternative_blocking_test.db"

OUTPUT = f"{BASE}/blocking/candidates/ml_candidates_10k.tsv"

# ------------------------------------------------
# SETTINGS
# ------------------------------------------------

MAX_BLOCK_FREQUENCY = 10000

# Maximum candidates retained per Source-1 record.
# This prevents candidate explosion.
MAX_CANDIDATES_PER_RECORD = 500

# ------------------------------------------------
# CHECK FILES
# ------------------------------------------------

for path in [SOURCE1, GROUND_TRUTH, ALT_DB]:

    if not os.path.exists(path):
        raise FileNotFoundError(path)

    print("OK:", path)

# ------------------------------------------------
# LOAD SOURCE-1
# ------------------------------------------------

print("\nLoading Source-1...")

s1 = pd.read_csv(
    SOURCE1,
    sep="\t",
    dtype=str,
    keep_default_na=False
).iloc[:10000].copy()

print("Source-1 records:", len(s1))

# ------------------------------------------------
# IDENTIFY COLUMNS
# ------------------------------------------------

def find_col(df, names):

    lower = {c.lower(): c for c in df.columns}

    for name in names:

        if name.lower() in lower:
            return lower[name.lower()]

    for c in df.columns:

        for name in names:

            if name.lower() in c.lower():
                return c

    return None


ID_COL = find_col(
    s1,
    ["entity_id", "id", "business_id", "record_id"]
)

NAME_COL = find_col(
    s1,
    ["business_name", "name", "company_name"]
)

if ID_COL is None or NAME_COL is None:

    raise ValueError(
        f"Required columns not found.\n"
        f"Columns: {list(s1.columns)}"
    )

print("ID column:", ID_COL)
print("Name column:", NAME_COL)

# ------------------------------------------------
# NORMALIZATION
# ------------------------------------------------

def normalize_text(x):

    x = str(x).lower()

    x = re.sub(
        r"[^a-z0-9]+",
        " ",
        x
    )

    return " ".join(x.split())


def create_keys(name):

    tokens = normalize_text(name).split()

    if len(tokens) == 0:
        return []

    keys = []

    # A: name_first
    keys.append(
        ("A", f"name_first|{tokens[0]}")
    )

    # C: name2
    if len(tokens) >= 2:

        keys.append(
            (
                "C",
                f"name2|{tokens[0]}|{tokens[1]}"
            )
        )

    return keys

# ------------------------------------------------
# CONNECT SQLITE
# ------------------------------------------------

print("\nConnecting SQLite...")

conn = sqlite3.connect(
    ALT_DB
)

# ------------------------------------------------
# CREATE OUTPUT
# ------------------------------------------------

if os.path.exists(OUTPUT):

    os.remove(OUTPUT)

# ------------------------------------------------
# PROCESS RECORD-BY-RECORD
# ------------------------------------------------

print("\nStarting batch candidate preparation...")
print("Maximum block frequency:", MAX_BLOCK_FREQUENCY)
print("Maximum candidates / record:", MAX_CANDIDATES_PER_RECORD)

start = time.time()

output_header = True

total_candidates = 0
processed = 0

batch = []

BATCH_SIZE = 500

# ------------------------------------------------
# MAIN LOOP
# ------------------------------------------------

for _, row in s1.iterrows():

    source1_id = row[ID_COL]

    keys = create_keys(
        row[NAME_COL]
    )

    candidates = {}

    # ------------------------------------------------
    # QUERY A + C
    # ------------------------------------------------

    for block_type, block_key in keys:

        rows = conn.execute(
            """
            SELECT entity_id, source
            FROM alternative_blocks
            WHERE block_type = ?
              AND block_key = ?
            LIMIT ?
            """,
            (
                block_type,
                block_key,
                MAX_CANDIDATES_PER_RECORD
            )
        ).fetchall()

        for target_id, source in rows:

            pair = (
                target_id,
                source
            )

            candidates[pair] = (
                block_type,
                block_key
            )

    # ------------------------------------------------
    # KEEP LIMITED CANDIDATES
    # ------------------------------------------------

    for (target_id, source), (block_type, block_key) in candidates.items():

        batch.append(
            {
                "source1_id": source1_id,
                "target_id": target_id,
                "target_source": source,
                "blocking_type": block_type,
                "blocking_key": block_key
            }
        )

    processed += 1

    # ------------------------------------------------
    # WRITE BATCH
    # ------------------------------------------------

    if processed % BATCH_SIZE == 0:

        if batch:

            batch_df = pd.DataFrame(batch)

            batch_df.drop_duplicates(
                subset=[
                    "source1_id",
                    "target_id"
                ],
                inplace=True
            )

            batch_df.to_csv(
                OUTPUT,
                sep="\t",
                index=False,
                mode="a",
                header=output_header
            )

            output_header = False

            total_candidates += len(batch_df)

            batch.clear()

            del batch_df

            gc.collect()

        elapsed = (
            time.time() - start
        ) / 60

        print(
            f"Processed: {processed:,} | "
            f"Candidates saved: {total_candidates:,} | "
            f"Time: {elapsed:.2f} min"
        )

# ------------------------------------------------
# FINAL BATCH
# ------------------------------------------------

if batch:

    batch_df = pd.DataFrame(batch)

    batch_df.drop_duplicates(
        subset=[
            "source1_id",
            "target_id"
        ],
        inplace=True
    )

    batch_df.to_csv(
        OUTPUT,
        sep="\t",
        index=False,
        mode="a",
        header=output_header
    )

    total_candidates += len(batch_df)

    del batch_df

# ------------------------------------------------
# CLOSE
# ------------------------------------------------

conn.close()

gc.collect()

elapsed = (
    time.time() - start
) / 60

# ------------------------------------------------
# VERIFY
# ------------------------------------------------

print("\n" + "=" * 70)
print("CELL 50 RESULTS")
print("=" * 70)

print(
    "Source-1 records processed:",
    processed
)

print(
    "Candidate rows saved:",
    f"{total_candidates:,}"
)

print(
    "Output file:",
    OUTPUT
)

if os.path.exists(OUTPUT):

    size_gb = (
        os.path.getsize(OUTPUT)
        / (1024 ** 3)
    )

    print(
        "Output size:",
        f"{size_gb:.2f} GB"
    )

print(
    "Time taken:",
    f"{elapsed:.2f} minutes"
)

print("\nSample:")

sample = pd.read_csv(
    OUTPUT,
    sep="\t",
    dtype=str,
    nrows=10
)

print(
    sample.to_string(index=False)
)

print("\n" + "=" * 70)
print("CELL 50 COMPLETE")
print("=" * 70)

print("""
Candidate preparation completed.

Next:
Cell 51 → candidate quality / ML feature preparation.
""")

======================================================================
CELL 50 - FAST BATCH CANDIDATE PREPARATION
======================================================================
OK: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/processed_data/cleaned_train_source1.tsv
OK: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ground_truth_aligned_10k.tsv
OK: /content/alternative_blocking_test.db

Loading Source-1...
Source-1 records: 10000
ID column: entity_id
Name column: business_name

Connecting SQLite...

Starting batch candidate preparation...
Maximum block frequency: 10000
Maximum candidates / record: 500
Processed: 500 | Candidates saved: 196,937 | Time: 0.34 min
Processed: 1,000 | Candidates saved: 388,648 | Time: 0.63 min
Processed: 1,500 | Candidates saved: 576,730 | Time: 0.87 min
Processed: 2,000 | Candidates saved: 769,761 | Time: 1.06 min
Processed: 2,500 | Candidates saved: 956,998 | Time: 1.20 min
Processed: 3,000 | Candidates saved: 1,145,606 | Time: 1.35 min
Processed: 3,500 | Candidates saved: 1,345,253 | Time: 1.47 min
Processed: 4,000 | Candidates saved: 1,543,849 | Time: 1.63 min
Processed: 4,500 | Candidates saved: 1,729,864 | Time: 1.76 min
Processed: 5,000 | Candidates saved: 1,935,344 | Time: 1.92 min
Processed: 5,500 | Candidates saved: 2,130,372 | Time: 2.07 min
Processed: 6,000 | Candidates saved: 2,321,645 | Time: 2.20 min
Processed: 6,500 | Candidates saved: 2,515,671 | Time: 2.36 min
Processed: 7,000 | Candidates saved: 2,712,213 | Time: 2.48 min
Processed: 7,500 | Candidates saved: 2,907,664 | Time: 2.62 min
Processed: 8,000 | Candidates saved: 3,107,497 | Time: 2.73 min
Processed: 8,500 | Candidates saved: 3,301,668 | Time: 2.87 min
Processed: 9,000 | Candidates saved: 3,499,874 | Time: 3.03 min
Processed: 9,500 | Candidates saved: 3,697,724 | Time: 3.15 min
Processed: 10,000 | Candidates saved: 3,883,634 | Time: 3.27 min

======================================================================
CELL 50 RESULTS
======================================================================
Source-1 records processed: 10000
Candidate rows saved: 3,883,634
Output file: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ml_candidates_10k.tsv
Output size: 0.20 GB
Time taken: 3.36 minutes

Sample:
  source1_id    target_id target_source blocking_type      blocking_key
S1-925783039 S2-361957120       source2             A name_first|orelee
S1-925783039 S2-141689655       source2             A name_first|orelee
S1-925783039 S2-137340653       source2             A name_first|orelee
S1-925783039 S2-110234581       source2             A name_first|orelee
S1-925783039 S2-457695192       source2             A name_first|orelee
S1-925783039 S2-597503035       source2             A name_first|orelee
S1-925783039 S2-293992631       source2             A name_first|orelee
S1-925783039 S2-854872713       source2             A name_first|orelee
S1-925783039 S2-470914905       source2             A name_first|orelee
S1-925783039 S2-269356813       source2             A name_first|orelee

======================================================================
CELL 50 COMPLETE
======================================================================

Candidate preparation completed.

Next:
Cell 51 → candidate quality / ML feature preparation.

In [ ]:
# ======================================================================
# CELL 51R - PERSISTENT ML FEATURE PREPARATION
# ======================================================================

import os
import gc
import time
import pandas as pd

print("=" * 70)
print("CELL 51R - PERSISTENT ML FEATURE PREPARATION")
print("=" * 70)

BASE = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource"

CANDIDATE_FILE = f"{BASE}/blocking/candidates/ml_candidates_10k.tsv"
GT_FILE = f"{BASE}/blocking/candidates/ground_truth_aligned_10k.tsv"
OUTPUT_FILE = f"{BASE}/blocking/candidates/ml_features_10k.tsv"

# ------------------------------------------------------------
# CHECK
# ------------------------------------------------------------

for path in [CANDIDATE_FILE, GT_FILE]:
    if not os.path.exists(path):
        raise FileNotFoundError(path)
    print("OK:", path)

# ------------------------------------------------------------
# GROUND TRUTH
# ------------------------------------------------------------

print("\nLoading ground truth...")

gt = pd.read_csv(
    GT_FILE,
    sep="\t",
    dtype=str,
    keep_default_na=False
)

print("Ground-truth columns:", list(gt.columns))

positive_pairs = set()

for _, row in gt.iterrows():

    s1 = str(row["source1_entity_id"]).strip()
    targets = str(row["matched_entity_ids"]).strip()

    if not s1 or not targets:
        continue

    targets = (
        targets
        .replace("[", "")
        .replace("]", "")
        .replace("'", "")
        .replace('"', "")
    )

    # Handle multiple target IDs
    for target in targets.replace(";", "|").replace(",", "|").split("|"):

        target = target.strip()

        if target:
            positive_pairs.add((s1, target))

del gt
gc.collect()

print(
    "Ground-truth positive pairs:",
    f"{len(positive_pairs):,}"
)

# ------------------------------------------------------------
# REMOVE OLD INCOMPLETE OUTPUT
# ------------------------------------------------------------

if os.path.exists(OUTPUT_FILE):
    os.remove(OUTPUT_FILE)

print("\nCreating fresh feature file...")

CHUNK_SIZE = 100_000

total_rows = 0
positive_rows = 0
negative_rows = 0
chunk_no = 0

start = time.time()
first_chunk = True

# ------------------------------------------------------------
# PROCESS CANDIDATES
# ------------------------------------------------------------

for chunk in pd.read_csv(
    CANDIDATE_FILE,
    sep="\t",
    dtype=str,
    keep_default_na=False,
    chunksize=CHUNK_SIZE
):

    chunk_no += 1

    # Create pair tuples
    pairs = zip(
        chunk["source1_id"],
        chunk["target_id"]
    )

    chunk["label"] = [
        1 if pair in positive_pairs else 0
        for pair in pairs
    ]

    pos = int((chunk["label"] == 1).sum())
    neg = int((chunk["label"] == 0).sum())

    positive_rows += pos
    negative_rows += neg
    total_rows += len(chunk)

    # Save immediately
    chunk.to_csv(
        OUTPUT_FILE,
        sep="\t",
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    first_chunk = False

    # Force filesystem visibility
    if chunk_no % 5 == 0:

        size_mb = (
            os.path.getsize(OUTPUT_FILE)
            / (1024 ** 2)
        )

        elapsed = (
            time.time() - start
        ) / 60

        print(
            f"Chunk {chunk_no:02d} | "
            f"Rows: {total_rows:,} | "
            f"Positive: {positive_rows:,} | "
            f"File: {size_mb:.1f} MB | "
            f"Time: {elapsed:.2f} min"
        )

    del chunk
    gc.collect()

# ------------------------------------------------------------
# FINAL VERIFY
# ------------------------------------------------------------

elapsed = (
    time.time() - start
) / 60

print("\n" + "=" * 70)
print("CELL 51R RESULTS")
print("=" * 70)

print("Feature rows      :", f"{total_rows:,}")
print("Positive rows     :", f"{positive_rows:,}")
print("Negative rows     :", f"{negative_rows:,}")

if os.path.exists(OUTPUT_FILE):

    size_mb = (
        os.path.getsize(OUTPUT_FILE)
        / (1024 ** 2)
    )

    print("Output file       :", OUTPUT_FILE)
    print(f"Output size       : {size_mb:.2f} MB")
    print("FILE SAVED        : ✅ YES")

else:

    raise RuntimeError(
        "Output file was not created!"
    )

print(f"Time taken        : {elapsed:.2f} minutes")

print("=" * 70)
print("CELL 51R COMPLETE")
print("=" * 70)

del positive_pairs
gc.collect()

print("\nMemory cleanup completed.")

======================================================================
CELL 51R - PERSISTENT ML FEATURE PREPARATION
======================================================================
OK: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ml_candidates_10k.tsv
OK: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ground_truth_aligned_10k.tsv

Loading ground truth...
Ground-truth columns: ['source1_entity_id', 'matched_entity_ids']
Ground-truth positive pairs: 34,752

Creating fresh feature file...
Chunk 05 | Rows: 500,000 | Positive: 2,837 | File: 26.7 MB | Time: 0.74 min
Chunk 10 | Rows: 1,000,000 | Positive: 5,596 | File: 53.5 MB | Time: 1.24 min
Chunk 15 | Rows: 1,500,000 | Positive: 8,297 | File: 80.2 MB | Time: 1.73 min
Chunk 20 | Rows: 2,000,000 | Positive: 11,025 | File: 107.0 MB | Time: 2.15 min
Chunk 25 | Rows: 2,500,000 | Positive: 13,835 | File: 133.8 MB | Time: 2.57 min
Chunk 30 | Rows: 3,000,000 | Positive: 16,452 | File: 160.6 MB | Time: 3.01 min
Chunk 35 | Rows: 3,500,000 | Positive: 19,126 | File: 187.4 MB | Time: 3.46 min

======================================================================
CELL 51R RESULTS
======================================================================
Feature rows      : 3,883,634
Positive rows     : 21,254
Negative rows     : 3,862,380
Output file       : /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ml_features_10k.tsv
Output size       : 207.94 MB
FILE SAVED        : ✅ YES
Time taken        : 3.91 minutes
======================================================================
CELL 51R COMPLETE
======================================================================

Memory cleanup completed.

In [ ]:
import os

FILE = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ml_features_10k.tsv"

print("Checking Cell 51R output...")

if os.path.exists(FILE):
    size_mb = os.path.getsize(FILE) / (1024**2)

    print("FOUND ✅")
    print("Path:", FILE)
    print(f"Size: {size_mb:.2f} MB")

    # Check first few lines
    with open(FILE, "r", encoding="utf-8") as f:
        for _ in range(3):
            print(f.readline().strip())

else:
    print("NOT FOUND ❌")

Checking Cell 51R output...
FOUND ✅
Path: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ml_features_10k.tsv
Size: 207.94 MB
source1_id	target_id	target_source	blocking_type	blocking_key	label
S1-925783039	S2-361957120	source2	A	name_first|orelee	0
S1-925783039	S2-141689655	source2	A	name_first|orelee	0

In [ ]:
# ======================================================================
# CELL 52 - RAM-SAFE ML TRAINING DATA PREPARATION
# ======================================================================

import os
import gc
import time
import pandas as pd

print("=" * 70)
print("CELL 52 - RAM-SAFE ML TRAINING DATA PREPARATION")
print("=" * 70)

# ----------------------------------------------------------------------
# PATHS
# ----------------------------------------------------------------------

BASE = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource"

FEATURE_FILE = (
    f"{BASE}/blocking/candidates/ml_features_10k.tsv"
)

TRAIN_FILE = (
    f"{BASE}/blocking/candidates/ml_training_10k.tsv"
)

# ----------------------------------------------------------------------
# CHECK INPUT
# ----------------------------------------------------------------------

print("\nChecking Cell 51R output...")

if not os.path.exists(FEATURE_FILE):
    raise FileNotFoundError(
        f"Cell 51R output not found:\n{FEATURE_FILE}"
    )

feature_size = os.path.getsize(FEATURE_FILE) / (1024 ** 2)

print("FOUND ✅")
print("Feature file:", FEATURE_FILE)
print(f"Feature size: {feature_size:.2f} MB")

# ----------------------------------------------------------------------
# SETTINGS
# ----------------------------------------------------------------------

CHUNK_SIZE = 100_000
NEGATIVE_RATIO = 3

print("\nSettings")
print("-" * 40)
print("Chunk size       :", CHUNK_SIZE)
print("Negative ratio   :", f"{NEGATIVE_RATIO}:1")

# ----------------------------------------------------------------------
# REMOVE OLD TRAINING FILE
# ----------------------------------------------------------------------

if os.path.exists(TRAIN_FILE):
    os.remove(TRAIN_FILE)
    print("\nOld training file removed.")

# ======================================================================
# PASS 1
# COUNT POSITIVE / NEGATIVE ROWS
# ======================================================================

print("\n" + "=" * 70)
print("PASS 1 - COUNTING LABELS")
print("=" * 70)

positive_count = 0
negative_count = 0
total_count = 0

start = time.time()

for chunk_no, chunk in enumerate(
    pd.read_csv(
        FEATURE_FILE,
        sep="\t",
        dtype={
            "source1_id": "string",
            "target_id": "string",
            "target_source": "string",
            "blocking_type": "string",
            "blocking_key": "string",
            "label": "int8"
        },
        chunksize=CHUNK_SIZE,
        keep_default_na=False
    ),
    start=1
):

    positive_count += int(
        (chunk["label"] == 1).sum()
    )

    negative_count += int(
        (chunk["label"] == 0).sum()
    )

    total_count += len(chunk)

    if chunk_no % 10 == 0:

        elapsed = (time.time() - start) / 60

        print(
            f"Processed: {total_count:,} | "
            f"Positive: {positive_count:,} | "
            f"Negative: {negative_count:,} | "
            f"Time: {elapsed:.2f} min"
        )

    del chunk
    gc.collect()

print("\nPASS 1 COMPLETE")
print("Total rows    :", f"{total_count:,}")
print("Positive rows :", f"{positive_count:,}")
print("Negative rows :", f"{negative_count:,}")

# ----------------------------------------------------------------------
# TARGET NEGATIVE COUNT
# ----------------------------------------------------------------------

target_negative = min(
    negative_count,
    positive_count * NEGATIVE_RATIO
)

print("\nTarget negative samples:", f"{target_negative:,}")

# ======================================================================
# PASS 2
# CREATE BALANCED TRAINING DATA
# ======================================================================

print("\n" + "=" * 70)
print("PASS 2 - CREATING TRAINING DATA")
print("=" * 70)

positive_saved = 0
negative_saved = 0
total_saved = 0

first_write = True

start = time.time()

for chunk_no, chunk in enumerate(
    pd.read_csv(
        FEATURE_FILE,
        sep="\t",
        dtype={
            "source1_id": "string",
            "target_id": "string",
            "target_source": "string",
            "blocking_type": "string",
            "blocking_key": "string",
            "label": "int8"
        },
        chunksize=CHUNK_SIZE,
        keep_default_na=False
    ),
    start=1
):

    # --------------------------------------------------------------
    # ALL POSITIVE ROWS
    # --------------------------------------------------------------

    positive = chunk[
        chunk["label"] == 1
    ]

    # --------------------------------------------------------------
    # NEGATIVE ROWS
    # --------------------------------------------------------------

    negative = chunk[
        chunk["label"] == 0
    ]

    remaining = target_negative - negative_saved

    if remaining <= 0:

        negative = negative.iloc[0:0]

    elif len(negative) > remaining:

        negative = negative.sample(
            n=remaining,
            random_state=42 + chunk_no
        )

    # --------------------------------------------------------------
    # COMBINE
    # --------------------------------------------------------------

    selected = pd.concat(
        [positive, negative],
        ignore_index=True
    )

    # --------------------------------------------------------------
    # SHUFFLE CURRENT CHUNK
    # --------------------------------------------------------------

    if len(selected) > 1:

        selected = selected.sample(
            frac=1,
            random_state=100 + chunk_no
        ).reset_index(drop=True)

    # --------------------------------------------------------------
    # COUNTS
    # --------------------------------------------------------------

    pos_now = int(
        (selected["label"] == 1).sum()
    )

    neg_now = int(
        (selected["label"] == 0).sum()
    )

    positive_saved += pos_now
    negative_saved += neg_now
    total_saved += len(selected)

    # --------------------------------------------------------------
    # SAVE IMMEDIATELY
    # --------------------------------------------------------------

    if len(selected) > 0:

        selected.to_csv(
            TRAIN_FILE,
            sep="\t",
            index=False,
            mode="w" if first_write else "a",
            header=first_write
        )

        first_write = False

    # --------------------------------------------------------------
    # PROGRESS
    # --------------------------------------------------------------

    if chunk_no % 10 == 0:

        elapsed = (time.time() - start) / 60

        print(
            f"Chunk {chunk_no:02d} | "
            f"Saved: {total_saved:,} | "
            f"Positive: {positive_saved:,} | "
            f"Negative: {negative_saved:,} | "
            f"Time: {elapsed:.2f} min"
        )

    # --------------------------------------------------------------
    # MEMORY CLEANUP
    # --------------------------------------------------------------

    del chunk
    del positive
    del negative
    del selected

    gc.collect()

# ======================================================================
# FINAL RESULT
# ======================================================================

elapsed = (time.time() - start) / 60

print("\n" + "=" * 70)
print("CELL 52 RESULTS")
print("=" * 70)

print("Original feature rows :", f"{total_count:,}")
print("Positive samples      :", f"{positive_saved:,}")
print("Negative samples      :", f"{negative_saved:,}")
print("Training rows         :", f"{total_saved:,}")

if positive_saved > 0:

    print(
        "Negative:Positive     :",
        f"{negative_saved / positive_saved:.2f}:1"
    )

if total_saved > 0:

    print(
        "Positive rate         :",
        f"{positive_saved / total_saved * 100:.2f}%"
    )

print("\nOutput file:")
print(TRAIN_FILE)

# ----------------------------------------------------------------------
# VERIFY FILE
# ----------------------------------------------------------------------

if os.path.exists(TRAIN_FILE):

    train_size = (
        os.path.getsize(TRAIN_FILE)
        / (1024 ** 2)
    )

    print(f"\nOutput size           : {train_size:.2f} MB")
    print("FILE SAVED            : ✅ YES")

else:

    raise RuntimeError(
        "Training file was not created!"
    )

print(f"Time taken            : {elapsed:.2f} minutes")

print("=" * 70)
print("CELL 52 COMPLETE")
print("=" * 70)

gc.collect()

print("\nRAM cleanup completed.")

======================================================================
CELL 52 - RAM-SAFE ML TRAINING DATA PREPARATION
======================================================================

Checking Cell 51R output...
FOUND ✅
Feature file: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ml_features_10k.tsv
Feature size: 207.94 MB

Settings
----------------------------------------
Chunk size       : 100000
Negative ratio   : 3:1

======================================================================
PASS 1 - COUNTING LABELS
======================================================================
Processed: 1,000,000 | Positive: 5,596 | Negative: 994,404 | Time: 0.81 min
Processed: 2,000,000 | Positive: 11,025 | Negative: 1,988,975 | Time: 1.58 min
Processed: 3,000,000 | Positive: 16,452 | Negative: 2,983,548 | Time: 2.37 min

PASS 1 COMPLETE
Total rows    : 3,883,634
Positive rows : 21,254
Negative rows : 3,862,380

Target negative samples: 63,762

======================================================================
PASS 2 - CREATING TRAINING DATA
======================================================================
Chunk 10 | Saved: 69,358 | Positive: 5,596 | Negative: 63,762 | Time: 0.76 min
Chunk 20 | Saved: 74,787 | Positive: 11,025 | Negative: 63,762 | Time: 1.53 min
Chunk 30 | Saved: 80,214 | Positive: 16,452 | Negative: 63,762 | Time: 2.31 min

======================================================================
CELL 52 RESULTS
======================================================================
Original feature rows : 3,883,634
Positive samples      : 21,254
Negative samples      : 63,762
Training rows         : 85,016
Negative:Positive     : 3.00:1
Positive rate         : 25.00%

Output file:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ml_training_10k.tsv

Output size           : 4.58 MB
FILE SAVED            : ✅ YES
Time taken            : 3.07 minutes
======================================================================
CELL 52 COMPLETE
======================================================================

RAM cleanup completed.

In [ ]:
!pip -q install rapidfuzz

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 26.4 MB/s eta 0:00:00

In [ ]:
from rapidfuzz.fuzz import ratio, partial_ratio, token_sort_ratio, token_set_ratio

print("RapidFuzz ready ✅")

RapidFuzz ready ✅

In [ ]:
import os
from google.colab import drive

drive.mount('/content/drive', force_remount=False)

BASE = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource"

print("BASE exists:", os.path.exists(BASE))

print("\nSearching candidate file...")

found = []

for root, dirs, files in os.walk(
    "/content/drive/MyDrive"
):
    if "ml_candidates_10k.tsv" in files:
        found.append(
            os.path.join(
                root,
                "ml_candidates_10k.tsv"
            )
        )

if found:
    print("\nFOUND ✅")
    for p in found:
        size = os.path.getsize(p) / (1024**2)
        print(p)
        print(f"Size: {size:.2f} MB")
else:
    print("\nNOT FOUND ❌")

Mounted at /content/drive
BASE exists: True

Searching candidate file...

FOUND ✅
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ml_candidates_10k.tsv
Size: 200.53 MB

In [ ]:
import os

print("Searching for alternative_blocking_test.db ...")

found = []

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    if "alternative_blocking_test.db" in files:
        found.append(
            os.path.join(root, "alternative_blocking_test.db")
        )

if found:
    print("\nFOUND ✅")
    for p in found:
        size = os.path.getsize(p) / (1024**3)
        print(p)
        print(f"Size: {size:.3f} GB")
else:
    print("\nNOT FOUND ❌")

Searching for alternative_blocking_test.db ...

NOT FOUND ❌

In [ ]:
import os

BASE = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource"

print("=" * 70)
print("SEARCHING SOURCE-2 / SOURCE-3 DATA")
print("=" * 70)

matches = []

for root, dirs, files in os.walk(BASE):
    for file in files:
        name = file.lower()

        if (
            "source2" in name
            or "source3" in name
            or "cleaned" in name
        ):
            matches.append(
                os.path.join(root, file)
            )

print("\nFOUND FILES:")

for path in matches:
    size_mb = os.path.getsize(path) / (1024 ** 2)

    print(
        f"{path}  |  {size_mb:.2f} MB"
    )

print(
    f"\nTotal matching files: {len(matches)}"
)

======================================================================
SEARCHING SOURCE-2 / SOURCE-3 DATA
======================================================================

FOUND FILES:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/dataset/test/test_source2.tsv  |  485.86 MB
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/dataset/test/test_source3.tsv  |  482.56 MB
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source2.tsv  |  466.63 MB
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source3.tsv  |  480.37 MB
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/processed_data/cleaned_train_source1.tsv  |  200.34 MB
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/processed_data/cleaned_train_source2.tsv  |  466.00 MB
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/processed_data/cleaned_train_source3.tsv  |  479.82 MB
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/source_index/source2_blocking_index.tsv  |  214.26 MB
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/source_index/source3_blocking_index.tsv  |  238.49 MB

Total matching files: 9

In [ ]:
# ======================================================================
# CELL 53 - DB-FREE RAM-SAFE ML FEATURE ENGINEERING
# ======================================================================

import os
import gc
import re
import time
import pandas as pd
import numpy as np
from difflib import SequenceMatcher

print("=" * 70)
print("CELL 53 - DB-FREE RAM-SAFE ML FEATURE ENGINEERING")
print("=" * 70)

BASE = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource"

SOURCE1_FILE = (
    f"{BASE}/processed_data/cleaned_train_source1.tsv"
)

SOURCE2_FILE = (
    f"{BASE}/processed_data/cleaned_train_source2.tsv"
)

SOURCE3_FILE = (
    f"{BASE}/processed_data/cleaned_train_source3.tsv"
)

CANDIDATE_FILE = (
    f"{BASE}/blocking/candidates/ml_candidates_10k.tsv"
)

GT_FILE = (
    f"{BASE}/blocking/candidates/ground_truth_aligned_10k.tsv"
)

OUTPUT_FILE = (
    f"{BASE}/blocking/candidates/ml_features_10k.tsv"
)

# ----------------------------------------------------------------------
# CHECK FILES
# ----------------------------------------------------------------------

print("\nChecking required files...")

required_files = [
    SOURCE1_FILE,
    SOURCE2_FILE,
    SOURCE3_FILE,
    CANDIDATE_FILE,
    GT_FILE
]

for path in required_files:

    if not os.path.exists(path):
        raise FileNotFoundError(
            f"\nRequired file not found:\n{path}"
        )

    size_mb = os.path.getsize(path) / (1024 ** 2)

    print(
        f"OK: {path} | {size_mb:.2f} MB"
    )

# ----------------------------------------------------------------------
# LOAD SOURCE-1
# ----------------------------------------------------------------------

print("\nLoading Source-1...")

source1 = pd.read_csv(
    SOURCE1_FILE,
    sep="\t",
    dtype=str,
    usecols=lambda c: c in [
        "entity_id",
        "business_name"
    ]
)

if "entity_id" not in source1.columns:
    raise ValueError(
        "Source-1 entity_id column not found"
    )

if "business_name" not in source1.columns:
    raise ValueError(
        "Source-1 business_name column not found"
    )

source1_map = dict(
    zip(
        source1["entity_id"].astype(str),
        source1["business_name"]
        .fillna("")
        .astype(str)
    )
)

print(
    "Source-1 records:",
    f"{len(source1_map):,}"
)

del source1
gc.collect()

# ----------------------------------------------------------------------
# LOAD CANDIDATE TARGET IDs ONLY
# ----------------------------------------------------------------------

print("\nReading candidate IDs...")

candidate_ids = {
    "source2": set(),
    "source3": set()
}

candidate_source1_ids = set()

for chunk in pd.read_csv(
    CANDIDATE_FILE,
    sep="\t",
    dtype=str,
    usecols=[
        "source1_id",
        "target_id",
        "target_source"
    ],
    chunksize=200_000
):

    candidate_source1_ids.update(
        chunk["source1_id"].astype(str)
    )

    for source in ["source2", "source3"]:

        mask = (
            chunk["target_source"].astype(str)
            == source
        )

        if mask.any():

            candidate_ids[source].update(
                chunk.loc[
                    mask,
                    "target_id"
                ].astype(str)
            )

    del chunk
    gc.collect()

print(
    "Unique Source-1 candidate IDs:",
    f"{len(candidate_source1_ids):,}"
)

print(
    "Unique Source-2 target IDs:",
    f"{len(candidate_ids['source2']):,}"
)

print(
    "Unique Source-3 target IDs:",
    f"{len(candidate_ids['source3']):,}"
)

# ----------------------------------------------------------------------
# NORMALIZATION
# ----------------------------------------------------------------------

def normalize_name(x):

    x = str(x).lower()

    x = re.sub(
        r"[^a-z0-9\s]",
        " ",
        x
    )

    x = re.sub(
        r"\s+",
        " ",
        x
    ).strip()

    return x


def ratio(a, b):

    if not a or not b:
        return 0.0

    return (
        SequenceMatcher(
            None,
            a,
            b
        ).ratio()
        * 100
    )


def token_sort_ratio(a, b):

    if not a or not b:
        return 0.0

    a_sorted = " ".join(
        sorted(a.split())
    )

    b_sorted = " ".join(
        sorted(b.split())
    )

    return (
        SequenceMatcher(
            None,
            a_sorted,
            b_sorted
        ).ratio()
        * 100
    )


def token_set_ratio(a, b):

    if not a or not b:
        return 0.0

    a_set = set(a.split())
    b_set = set(b.split())

    if not a_set or not b_set:
        return 0.0

    intersection = a_set & b_set

    if not intersection:
        return 0.0

    common = " ".join(
        sorted(intersection)
    )

    a_full = " ".join(
        sorted(a_set)
    )

    b_full = " ".join(
        sorted(b_set)
    )

    s1 = SequenceMatcher(
        None,
        common,
        a_full
    ).ratio()

    s2 = SequenceMatcher(
        None,
        common,
        b_full
    ).ratio()

    return max(s1, s2) * 100


print("\nSimilarity functions ready ✅")

# ----------------------------------------------------------------------
# LOAD TARGET NAMES CHUNK-WISE
# ----------------------------------------------------------------------

def load_required_targets(
    filepath,
    required_ids,
    source_name
):

    print(
        f"\nScanning {source_name}..."
    )

    result = {}

    # First inspect columns
    header = pd.read_csv(
        filepath,
        sep="\t",
        dtype=str,
        nrows=0
    )

    columns = list(
        header.columns
    )

    print(
        f"{source_name} columns:",
        columns
    )

    id_col = None

    for col in [
        "entity_id",
        "id",
        f"{source_name}_entity_id"
    ]:

        if col in columns:
            id_col = col
            break

    name_col = None

    for col in [
        "business_name",
        "name",
        "name1",
        "name2"
    ]:

        if col in columns:
            name_col = col
            break

    if id_col is None:
        raise ValueError(
            f"ID column not found in {source_name}"
        )

    if name_col is None:
        raise ValueError(
            f"Name column not found in {source_name}"
        )

    print(
        f"{source_name} ID column   : {id_col}"
    )

    print(
        f"{source_name} name column : {name_col}"
    )

    required_ids = set(
        str(x)
        for x in required_ids
    )

    total_scanned = 0

    for chunk in pd.read_csv(
        filepath,
        sep="\t",
        dtype=str,
        usecols=[
            id_col,
            name_col
        ],
        chunksize=100_000
    ):

        chunk[id_col] = (
            chunk[id_col]
            .astype(str)
        )

        mask = chunk[id_col].isin(
            required_ids
        )

        if mask.any():

            selected = chunk.loc[
                mask,
                [id_col, name_col]
            ]

            for row in selected.itertuples(
                index=False,
                name=None
            ):

                result[str(row[0])] = (
                    ""
                    if pd.isna(row[1])
                    else str(row[1])
                )

        total_scanned += len(chunk)

        del chunk
        gc.collect()

    print(
        f"{source_name} scanned:",
        f"{total_scanned:,}"
    )

    print(
        f"{source_name} target names found:",
        f"{len(result):,}"
    )

    return result


source2_map = load_required_targets(
    SOURCE2_FILE,
    candidate_ids["source2"],
    "source2"
)

source3_map = load_required_targets(
    SOURCE3_FILE,
    candidate_ids["source3"],
    "source3"
)

# ----------------------------------------------------------------------
# LOAD GROUND TRUTH
# ----------------------------------------------------------------------

print("\nLoading ground truth...")

gt = pd.read_csv(
    GT_FILE,
    sep="\t",
    dtype=str
)

print(
    "Ground-truth columns:",
    list(gt.columns)
)

if (
    "source1_entity_id" not in gt.columns
    or
    "matched_entity_ids" not in gt.columns
):

    raise ValueError(
        "Unexpected ground-truth format"
    )

positive_pairs = set()

for row in gt.itertuples(
    index=False
):

    source_id = str(
        row.source1_entity_id
    )

    matched_ids = re.split(
        r"[,;|]",
        str(row.matched_entity_ids)
    )

    for target_id in matched_ids:

        target_id = target_id.strip()

        if target_id:

            positive_pairs.add(
                (
                    source_id,
                    target_id
                )
            )

print(
    "Ground-truth positive pairs:",
    f"{len(positive_pairs):,}"
)

del gt
gc.collect()

# ----------------------------------------------------------------------
# REMOVE OLD OUTPUT
# ----------------------------------------------------------------------

if os.path.exists(
    OUTPUT_FILE
):

    os.remove(
        OUTPUT_FILE
    )

# ----------------------------------------------------------------------
# PROCESS CANDIDATES
# ----------------------------------------------------------------------

print("\nCreating ML feature file...")

CHUNK_SIZE = 100_000

total_rows = 0
positive_rows = 0
negative_rows = 0

start_time = time.time()
first_write = True

for chunk_no, chunk in enumerate(
    pd.read_csv(
        CANDIDATE_FILE,
        sep="\t",
        dtype=str,
        chunksize=CHUNK_SIZE
    ),
    start=1
):

    feature_rows = []

    for row in chunk.itertuples(
        index=False
    ):

        source1_id = str(
            row.source1_id
        )

        target_id = str(
            row.target_id
        )

        target_source = str(
            row.target_source
        )

        # --------------------------------------------------------------
        # SOURCE-1 NAME
        # --------------------------------------------------------------

        name1 = source1_map.get(
            source1_id,
            ""
        )

        # --------------------------------------------------------------
        # TARGET NAME
        # --------------------------------------------------------------

        if target_source == "source2":

            name2 = source2_map.get(
                target_id,
                ""
            )

        elif target_source == "source3":

            name2 = source3_map.get(
                target_id,
                ""
            )

        else:

            name2 = ""

        name1 = normalize_name(
            name1
        )

        name2 = normalize_name(
            name2
        )

        # --------------------------------------------------------------
        # NUMERIC FEATURES
        # --------------------------------------------------------------

        name_ratio = ratio(
            name1,
            name2
        )

        token_sort = token_sort_ratio(
            name1,
            name2
        )

        token_set = token_set_ratio(
            name1,
            name2
        )

        length_difference = abs(
            len(name1) - len(name2)
        )

        exact_match = int(
            name1 != ""
            and name2 != ""
            and name1 == name2
        )

        # --------------------------------------------------------------
        # LABEL
        # --------------------------------------------------------------

        label = int(
            (
                source1_id,
                target_id
            )
            in positive_pairs
        )

        if label == 1:

            positive_rows += 1

        else:

            negative_rows += 1

        feature_rows.append({

            "source1_id":
                source1_id,

            "target_id":
                target_id,

            "target_source":
                target_source,

            "blocking_type":
                str(row.blocking_type),

            "name_ratio":
                name_ratio,

            "token_sort_ratio":
                token_sort,

            "token_set_ratio":
                token_set,

            "length_difference":
                length_difference,

            "exact_name_match":
                exact_match,

            "label":
                label
        })

    feature_df = pd.DataFrame(
        feature_rows
    )

    total_rows += len(
        feature_df
    )

    feature_df.to_csv(
        OUTPUT_FILE,
        sep="\t",
        index=False,
        mode="w"
        if first_write
        else "a",
        header=first_write
    )

    first_write = False

    elapsed = (
        time.time() - start_time
    ) / 60

    print(
        f"Chunk {chunk_no:02d} | "
        f"Rows: {total_rows:,} | "
        f"Positive: {positive_rows:,} | "
        f"Time: {elapsed:.2f} min"
    )

    del feature_rows
    del feature_df
    del chunk

    gc.collect()

# ----------------------------------------------------------------------
# FINAL RESULT
# ----------------------------------------------------------------------

elapsed = (
    time.time() - start_time
) / 60

size_mb = (
    os.path.getsize(
        OUTPUT_FILE
    )
    / (1024 ** 2)
)

print("\n" + "=" * 70)
print("CELL 53 RESULTS")
print("=" * 70)

print(
    "Feature rows      :",
    f"{total_rows:,}"
)

print(
    "Positive rows     :",
    f"{positive_rows:,}"
)

print(
    "Negative rows     :",
    f"{negative_rows:,}"
)

print(
    "Positive rate     :",
    f"{positive_rows / total_rows * 100:.4f}%"
)

print("\nNumeric ML features:")
print(" - name_ratio")
print(" - token_sort_ratio")
print(" - token_set_ratio")
print(" - length_difference")
print(" - exact_name_match")

print("\nOutput file:")
print(OUTPUT_FILE)

print(
    f"Output size       : {size_mb:.2f} MB"
)

print(
    "FILE SAVED        : ✅ YES"
)

print(
    f"Time taken        : {elapsed:.2f} minutes"
)

print("=" * 70)
print("CELL 53 COMPLETE")
print("=" * 70)

# ----------------------------------------------------------------------
# CLEANUP
# ----------------------------------------------------------------------

del source1_map
del source2_map
del source3_map
del positive_pairs
gc.collect()

print("\nMemory cleanup completed.")

======================================================================
CELL 53 - DB-FREE RAM-SAFE ML FEATURE ENGINEERING
======================================================================

Checking required files...
OK: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/processed_data/cleaned_train_source1.tsv | 200.34 MB
OK: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/processed_data/cleaned_train_source2.tsv | 466.00 MB
OK: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/processed_data/cleaned_train_source3.tsv | 479.82 MB
OK: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ml_candidates_10k.tsv | 200.53 MB
OK: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ground_truth_aligned_10k.tsv | 0.55 MB

Loading Source-1...
Source-1 records: 2,206,821

Reading candidate IDs...
Unique Source-1 candidate IDs: 9,999
Unique Source-2 target IDs: 818,089
Unique Source-3 target IDs: 456,701

Similarity functions ready ✅

Scanning source2...
source2 columns: ['entity_id', 'business_name', 'business_address', 'country']
source2 ID column   : entity_id
source2 name column : business_name
source2 scanned: 5,034,616
source2 target names found: 818,089

Scanning source3...
source3 columns: ['entity_id', 'business_name', 'business_address', 'country']
source3 ID column   : entity_id
source3 name column : business_name
source3 scanned: 5,285,603
source3 target names found: 456,701

Loading ground truth...
Ground-truth columns: ['source1_entity_id', 'matched_entity_ids']
Ground-truth positive pairs: 35,312

Creating ML feature file...
Chunk 01 | Rows: 100,000 | Positive: 525 | Time: 0.21 min
Chunk 02 | Rows: 200,000 | Positive: 1,099 | Time: 0.43 min
Chunk 03 | Rows: 300,000 | Positive: 1,644 | Time: 0.66 min
Chunk 04 | Rows: 400,000 | Positive: 2,238 | Time: 0.88 min
Chunk 05 | Rows: 500,000 | Positive: 2,837 | Time: 1.11 min
Chunk 06 | Rows: 600,000 | Positive: 3,356 | Time: 1.34 min
Chunk 07 | Rows: 700,000 | Positive: 3,941 | Time: 1.56 min
Chunk 08 | Rows: 800,000 | Positive: 4,524 | Time: 1.78 min
Chunk 09 | Rows: 900,000 | Positive: 5,070 | Time: 2.02 min
Chunk 10 | Rows: 1,000,000 | Positive: 5,596 | Time: 2.26 min
Chunk 11 | Rows: 1,100,000 | Positive: 6,195 | Time: 2.49 min
Chunk 12 | Rows: 1,200,000 | Positive: 6,733 | Time: 2.71 min
Chunk 13 | Rows: 1,300,000 | Positive: 7,287 | Time: 2.93 min
Chunk 14 | Rows: 1,400,000 | Positive: 7,770 | Time: 3.15 min
Chunk 15 | Rows: 1,500,000 | Positive: 8,297 | Time: 3.38 min
Chunk 16 | Rows: 1,600,000 | Positive: 8,853 | Time: 3.61 min
Chunk 17 | Rows: 1,700,000 | Positive: 9,476 | Time: 3.85 min
Chunk 18 | Rows: 1,800,000 | Positive: 10,017 | Time: 4.09 min
Chunk 19 | Rows: 1,900,000 | Positive: 10,480 | Time: 4.32 min
Chunk 20 | Rows: 2,000,000 | Positive: 11,025 | Time: 4.55 min
Chunk 21 | Rows: 2,100,000 | Positive: 11,532 | Time: 4.78 min
Chunk 22 | Rows: 2,200,000 | Positive: 12,133 | Time: 5.01 min
Chunk 23 | Rows: 2,300,000 | Positive: 12,705 | Time: 5.25 min
Chunk 24 | Rows: 2,400,000 | Positive: 13,275 | Time: 5.47 min
Chunk 25 | Rows: 2,500,000 | Positive: 13,835 | Time: 5.70 min
Chunk 26 | Rows: 2,600,000 | Positive: 14,331 | Time: 5.93 min
Chunk 27 | Rows: 2,700,000 | Positive: 14,922 | Time: 6.16 min
Chunk 28 | Rows: 2,800,000 | Positive: 15,446 | Time: 6.39 min
Chunk 29 | Rows: 2,900,000 | Positive: 15,987 | Time: 6.62 min
Chunk 30 | Rows: 3,000,000 | Positive: 16,452 | Time: 6.86 min
Chunk 31 | Rows: 3,100,000 | Positive: 17,003 | Time: 7.09 min
Chunk 32 | Rows: 3,200,000 | Positive: 17,514 | Time: 7.34 min
Chunk 33 | Rows: 3,300,000 | Positive: 18,064 | Time: 7.57 min
Chunk 34 | Rows: 3,400,000 | Positive: 18,582 | Time: 7.85 min
Chunk 35 | Rows: 3,500,000 | Positive: 19,126 | Time: 8.12 min
Chunk 36 | Rows: 3,600,000 | Positive: 19,624 | Time: 8.37 min
Chunk 37 | Rows: 3,700,000 | Positive: 20,214 | Time: 8.67 min
Chunk 38 | Rows: 3,800,000 | Positive: 20,801 | Time: 8.94 min
Chunk 39 | Rows: 3,883,634 | Positive: 21,254 | Time: 9.16 min

======================================================================
CELL 53 RESULTS
======================================================================
Feature rows      : 3,883,634
Positive rows     : 21,254
Negative rows     : 3,862,380
Positive rate     : 0.5473%

Numeric ML features:
 - name_ratio
 - token_sort_ratio
 - token_set_ratio
 - length_difference
 - exact_name_match

Output file:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ml_features_10k.tsv
Output size       : 321.50 MB
FILE SAVED        : ✅ YES
Time taken        : 9.17 minutes
======================================================================
CELL 53 COMPLETE
======================================================================

Memory cleanup completed.

In [ ]:
# ======================================================================
# CELL 54R - ROBUST RAM-SAFE TRAIN / VALIDATION PREPARATION
# ======================================================================

import os
import gc
import time
import random
import pandas as pd
import numpy as np

print("=" * 70)
print("CELL 54R - ROBUST RAM-SAFE TRAIN / VALIDATION PREPARATION")
print("=" * 70)

BASE = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource"

FEATURE_FILE = (
    f"{BASE}/blocking/candidates/ml_features_10k.tsv"
)

TRAIN_FILE = (
    f"{BASE}/blocking/candidates/ml_train_10k.tsv"
)

VAL_FILE = (
    f"{BASE}/blocking/candidates/ml_validation_10k.tsv"
)

CHUNK_SIZE = 100_000
NEGATIVE_RATIO = 3
VALIDATION_RATIO = 0.20
RANDOM_SEED = 42

random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

# ----------------------------------------------------------------------
# CHECK FILE
# ----------------------------------------------------------------------

print("\nChecking Cell 53 output...")

if not os.path.exists(FEATURE_FILE):
    raise FileNotFoundError(
        f"Feature file not found:\n{FEATURE_FILE}"
    )

size_mb = os.path.getsize(FEATURE_FILE) / (1024 ** 2)

print("FOUND ✅")
print("Feature file:", FEATURE_FILE)
print(f"Feature size: {size_mb:.2f} MB")

# ----------------------------------------------------------------------
# PASS 1 - COUNT LABELS
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PASS 1 - COUNTING LABELS")
print("=" * 70)

start = time.time()

total_rows = 0
positive_count = 0
negative_count = 0

# IMPORTANT:
# Do NOT force integer dtype here.
# exact_name_match contains NA values.

for chunk_no, chunk in enumerate(
    pd.read_csv(
        FEATURE_FILE,
        sep="\t",
        chunksize=CHUNK_SIZE,
        low_memory=True
    ),
    start=1
):

    total_rows += len(chunk)

    labels = pd.to_numeric(
        chunk["label"],
        errors="coerce"
    )

    positive_count += int(
        (labels == 1).sum()
    )

    negative_count += int(
        (labels == 0).sum()
    )

    if chunk_no % 10 == 0:
        elapsed = (time.time() - start) / 60

        print(
            f"Processed: {total_rows:,} | "
            f"Positive: {positive_count:,} | "
            f"Negative: {negative_count:,} | "
            f"Time: {elapsed:.2f} min"
        )

    del chunk
    del labels
    gc.collect()

print("\nPASS 1 COMPLETE")

print(
    "Total rows    :",
    f"{total_rows:,}"
)

print(
    "Positive rows :",
    f"{positive_count:,}"
)

print(
    "Negative rows :",
    f"{negative_count:,}"
)

target_negatives = positive_count * NEGATIVE_RATIO

print(
    "Target negatives:",
    f"{target_negatives:,}"
)

# ----------------------------------------------------------------------
# PASS 2 - COLLECT POSITIVES + SAMPLE NEGATIVES
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PASS 2 - CREATING TRAINING DATA")
print("=" * 70)

start = time.time()

positive_parts = []
negative_reservoir = []

negative_seen = 0

for chunk_no, chunk in enumerate(
    pd.read_csv(
        FEATURE_FILE,
        sep="\t",
        chunksize=CHUNK_SIZE,
        low_memory=True
    ),
    start=1
):

    # --------------------------------------------------------------
    # CLEAN LABEL
    # --------------------------------------------------------------

    chunk["label"] = pd.to_numeric(
        chunk["label"],
        errors="coerce"
    )

    # --------------------------------------------------------------
    # POSITIVES
    # --------------------------------------------------------------

    pos = chunk[
        chunk["label"] == 1
    ]

    if len(pos) > 0:
        positive_parts.append(
            pos.copy()
        )

    # --------------------------------------------------------------
    # NEGATIVES
    # --------------------------------------------------------------

    neg = chunk[
        chunk["label"] == 0
    ]

    for row in neg.itertuples(
        index=False,
        name=None
    ):

        negative_seen += 1

        if len(negative_reservoir) < target_negatives:

            negative_reservoir.append(row)

        else:

            j = random.randrange(
                negative_seen
            )

            if j < target_negatives:
                negative_reservoir[j] = row

    if chunk_no % 10 == 0:

        elapsed = (time.time() - start) / 60

        current_positive = sum(
            len(x)
            for x in positive_parts
        )

        print(
            f"Chunk {chunk_no:02d} | "
            f"Rows: {chunk_no * CHUNK_SIZE:,} approx | "
            f"Positive: {current_positive:,} | "
            f"Negative reservoir: {len(negative_reservoir):,} | "
            f"Time: {elapsed:.2f} min"
        )

    del chunk
    del pos
    del neg

    gc.collect()

# ----------------------------------------------------------------------
# COMBINE
# ----------------------------------------------------------------------

print("\nCombining samples...")

positive_df = pd.concat(
    positive_parts,
    ignore_index=True
)

del positive_parts
gc.collect()

columns = list(
    positive_df.columns
)

negative_df = pd.DataFrame(
    negative_reservoir,
    columns=columns
)

del negative_reservoir
gc.collect()

print(
    "Positive samples:",
    f"{len(positive_df):,}"
)

print(
    "Negative samples:",
    f"{len(negative_df):,}"
)

# ----------------------------------------------------------------------
# BALANCED DATASET
# ----------------------------------------------------------------------

dataset = pd.concat(
    [
        positive_df,
        negative_df
    ],
    ignore_index=True
)

del positive_df
del negative_df
gc.collect()

# Shuffle
dataset = dataset.sample(
    frac=1,
    random_state=RANDOM_SEED
).reset_index(drop=True)

# ----------------------------------------------------------------------
# TRAIN / VALIDATION SPLIT
# ----------------------------------------------------------------------

validation_size = int(
    len(dataset) * VALIDATION_RATIO
)

validation_df = dataset.iloc[
    :validation_size
].copy()

train_df = dataset.iloc[
    validation_size:
].copy()

del dataset
gc.collect()

# ----------------------------------------------------------------------
# SAVE
# ----------------------------------------------------------------------

if os.path.exists(TRAIN_FILE):
    os.remove(TRAIN_FILE)

if os.path.exists(VAL_FILE):
    os.remove(VAL_FILE)

train_df.to_csv(
    TRAIN_FILE,
    sep="\t",
    index=False
)

validation_df.to_csv(
    VAL_FILE,
    sep="\t",
    index=False
)

# ----------------------------------------------------------------------
# VERIFY FILES
# ----------------------------------------------------------------------

train_ok = os.path.exists(TRAIN_FILE)
val_ok = os.path.exists(VAL_FILE)

train_mb = (
    os.path.getsize(TRAIN_FILE) / (1024 ** 2)
    if train_ok else 0
)

val_mb = (
    os.path.getsize(VAL_FILE) / (1024 ** 2)
    if val_ok else 0
)

print("\n" + "=" * 70)
print("CELL 54R RESULTS")
print("=" * 70)

print(
    "Original feature rows :",
    f"{total_rows:,}"
)

print(
    "Positive samples      :",
    f"{positive_count:,}"
)

print(
    "Negative samples      :",
    f"{target_negatives:,}"
)

print(
    "Balanced dataset      :",
    f"{positive_count + target_negatives:,}"
)

print(
    "Negative:Positive     :",
    f"{NEGATIVE_RATIO}:1"
)

print(
    "Training rows         :",
    f"{len(train_df):,}"
)

print(
    "Validation rows       :",
    f"{len(validation_df):,}"
)

print("\nTraining file:")
print(TRAIN_FILE)
print(f"Size: {train_mb:.2f} MB")

print("\nValidation file:")
print(VAL_FILE)
print(f"Size: {val_mb:.2f} MB")

print("\nTraining file saved:", "✅ YES" if train_ok else "❌ NO")
print("Validation file saved:", "✅ YES" if val_ok else "❌ NO")

print("=" * 70)
print("CELL 54R COMPLETE")
print("=" * 70)

del train_df
del validation_df

gc.collect()

print("\nMemory cleanup completed.")

======================================================================
CELL 54R - ROBUST RAM-SAFE TRAIN / VALIDATION PREPARATION
======================================================================

Checking Cell 53 output...
FOUND ✅
Feature file: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ml_features_10k.tsv
Feature size: 321.50 MB

======================================================================
PASS 1 - COUNTING LABELS
======================================================================
Processed: 1,000,000 | Positive: 5,596 | Negative: 994,404 | Time: 0.07 min
Processed: 2,000,000 | Positive: 11,025 | Negative: 1,988,975 | Time: 0.12 min
Processed: 3,000,000 | Positive: 16,450 | Negative: 2,983,549 | Time: 0.16 min

PASS 1 COMPLETE
Total rows    : 3,784,393
Positive rows : 20,741
Negative rows : 3,763,651
Target negatives: 62,223

======================================================================
PASS 2 - CREATING TRAINING DATA
======================================================================
Chunk 10 | Rows: 1,000,000 approx | Positive: 5,596 | Negative reservoir: 62,223 | Time: 0.08 min
Chunk 20 | Rows: 2,000,000 approx | Positive: 11,025 | Negative reservoir: 62,223 | Time: 0.15 min
Chunk 30 | Rows: 3,000,000 approx | Positive: 16,450 | Negative reservoir: 62,223 | Time: 0.22 min

Combining samples...
Positive samples: 20,741
Negative samples: 62,223

======================================================================
CELL 54R RESULTS
======================================================================
Original feature rows : 3,784,393
Positive samples      : 20,741
Negative samples      : 62,223
Balanced dataset      : 82,964
Negative:Positive     : 3:1
Training rows         : 66,372
Validation rows       : 16,592

Training file:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ml_train_10k.tsv
Size: 5.80 MB

Validation file:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ml_validation_10k.tsv
Size: 1.45 MB

Training file saved: ✅ YES
Validation file saved: ✅ YES
======================================================================
CELL 54R COMPLETE
======================================================================

Memory cleanup completed.

In [ ]:
# ======================================================================
# CELL 55 - RAM-SAFE ML MODEL TRAINING + EVALUATION
# ======================================================================

import os
import gc
import time
import joblib
import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

print("=" * 70)
print("CELL 55 - ML MODEL TRAINING + EVALUATION")
print("=" * 70)

BASE = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource"

TRAIN_FILE = (
    f"{BASE}/blocking/candidates/ml_train_10k.tsv"
)

VAL_FILE = (
    f"{BASE}/blocking/candidates/ml_validation_10k.tsv"
)

MODEL_FILE = (
    f"{BASE}/blocking/candidates/entity_matching_model_10k.pkl"
)

# ----------------------------------------------------------------------
# CHECK FILES
# ----------------------------------------------------------------------

print("\nChecking Cell 54R outputs...")

for path in [TRAIN_FILE, VAL_FILE]:

    if not os.path.exists(path):

        raise FileNotFoundError(
            f"\nRequired file not found:\n{path}"
        )

    size_mb = (
        os.path.getsize(path)
        / (1024 ** 2)
    )

    print(
        f"FOUND ✅ {path} | "
        f"{size_mb:.2f} MB"
    )

# ----------------------------------------------------------------------
# ML FEATURES
# ----------------------------------------------------------------------

FEATURES = [
    "name_ratio",
    "token_sort_ratio",
    "token_set_ratio",
    "length_difference",
    "exact_name_match"
]

TARGET = "label"

print("\nML features:")
for feature in FEATURES:
    print(" -", feature)

# ----------------------------------------------------------------------
# LOAD TRAINING DATA
# ----------------------------------------------------------------------

print("\nLoading training data...")

train = pd.read_csv(
    TRAIN_FILE,
    sep="\t",
    low_memory=True
)

print(
    "Training rows:",
    f"{len(train):,}"
)

# ----------------------------------------------------------------------
# VALIDATE FEATURES
# ----------------------------------------------------------------------

missing_train = [
    col
    for col in FEATURES + [TARGET]
    if col not in train.columns
]

if missing_train:

    raise ValueError(
        f"Missing training columns:\n{missing_train}"
    )

# Convert numeric features safely

for col in FEATURES:

    train[col] = pd.to_numeric(
        train[col],
        errors="coerce"
    )

# Missing values → 0

train[FEATURES] = (
    train[FEATURES]
    .replace(
        [np.inf, -np.inf],
        np.nan
    )
    .fillna(0)
)

train[TARGET] = pd.to_numeric(
    train[TARGET],
    errors="coerce"
).fillna(0).astype(int)

X_train = train[FEATURES].astype(
    np.float32
)

y_train = train[TARGET].astype(
    np.int8
)

print("\nTraining label distribution:")

print(
    y_train.value_counts()
)

# ----------------------------------------------------------------------
# FREE UNUSED TRAIN DATA
# ----------------------------------------------------------------------

del train
gc.collect()

# ----------------------------------------------------------------------
# LOAD VALIDATION DATA
# ----------------------------------------------------------------------

print("\nLoading validation data...")

validation = pd.read_csv(
    VAL_FILE,
    sep="\t",
    low_memory=True
)

print(
    "Validation rows:",
    f"{len(validation):,}"
)

missing_val = [
    col
    for col in FEATURES + [TARGET]
    if col not in validation.columns
]

if missing_val:

    raise ValueError(
        f"Missing validation columns:\n{missing_val}"
    )

for col in FEATURES:

    validation[col] = pd.to_numeric(
        validation[col],
        errors="coerce"
    )

validation[FEATURES] = (
    validation[FEATURES]
    .replace(
        [np.inf, -np.inf],
        np.nan
    )
    .fillna(0)
)

validation[TARGET] = pd.to_numeric(
    validation[TARGET],
    errors="coerce"
).fillna(0).astype(int)

X_val = validation[FEATURES].astype(
    np.float32
)

y_val = validation[TARGET].astype(
    np.int8
)

print("\nValidation label distribution:")

print(
    y_val.value_counts()
)

# ----------------------------------------------------------------------
# TRAIN RANDOM FOREST
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("TRAINING RANDOM FOREST")
print("=" * 70)

start_time = time.time()

model = RandomForestClassifier(

    n_estimators=100,

    max_depth=12,

    min_samples_leaf=5,

    class_weight="balanced",

    random_state=42,

    n_jobs=-1
)

print("\nTraining model...")

model.fit(
    X_train,
    y_train
)

training_time = (
    time.time() - start_time
)

print(
    f"\nTraining completed in "
    f"{training_time:.2f} seconds"
)

# ----------------------------------------------------------------------
# PREDICTION
# ----------------------------------------------------------------------

print("\nGenerating validation predictions...")

y_pred = model.predict(
    X_val
)

y_prob = model.predict_proba(
    X_val
)[:, 1]

# ----------------------------------------------------------------------
# METRICS
# ----------------------------------------------------------------------

accuracy = accuracy_score(
    y_val,
    y_pred
)

precision = precision_score(
    y_val,
    y_pred,
    zero_division=0
)

recall = recall_score(
    y_val,
    y_pred,
    zero_division=0
)

f1 = f1_score(
    y_val,
    y_pred,
    zero_division=0
)

auc = roc_auc_score(
    y_val,
    y_prob
)

cm = confusion_matrix(
    y_val,
    y_pred
)

# ----------------------------------------------------------------------
# RESULTS
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("CELL 55 RESULTS")
print("=" * 70)

print(
    f"Accuracy  : {accuracy:.4f}"
)

print(
    f"Precision : {precision:.4f}"
)

print(
    f"Recall    : {recall:.4f}"
)

print(
    f"F1 Score  : {f1:.4f}"
)

print(
    f"ROC-AUC   : {auc:.4f}"
)

print("\nConfusion Matrix:")

print(cm)

print("\nClassification Report:")

print(
    classification_report(
        y_val,
        y_pred,
        target_names=[
            "Non-Match",
            "Match"
        ],
        zero_division=0
    )
)

# ----------------------------------------------------------------------
# FEATURE IMPORTANCE
# ----------------------------------------------------------------------

print("\nFeature Importance:")

importance = pd.DataFrame({

    "feature": FEATURES,

    "importance":
        model.feature_importances_

}).sort_values(
    "importance",
    ascending=False
)

print(
    importance.to_string(
        index=False
    )
)

# ----------------------------------------------------------------------
# SAVE MODEL
# ----------------------------------------------------------------------

print("\nSaving model...")

model_package = {

    "model": model,

    "features": FEATURES,

    "threshold": 0.50,

    "training_rows":
        int(len(X_train)),

    "validation_rows":
        int(len(X_val)),

    "random_seed": 42
}

joblib.dump(
    model_package,
    MODEL_FILE
)

model_size = (
    os.path.getsize(MODEL_FILE)
    / (1024 ** 2)
)

print(
    "\nMODEL SAVED ✅"
)

print(
    "Model file:",
    MODEL_FILE
)

print(
    f"Model size: {model_size:.2f} MB"
)

# ----------------------------------------------------------------------
# CLEANUP
# ----------------------------------------------------------------------

del X_train
del y_train
del X_val
del y_val
del validation
del model

gc.collect()

print("\nMemory cleanup completed.")

print("=" * 70)
print("CELL 55 COMPLETE")
print("=" * 70)

======================================================================
CELL 55 - ML MODEL TRAINING + EVALUATION
======================================================================

Checking Cell 54R outputs...
FOUND ✅ /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ml_train_10k.tsv | 5.80 MB
FOUND ✅ /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ml_validation_10k.tsv | 1.45 MB

ML features:
 - name_ratio
 - token_sort_ratio
 - token_set_ratio
 - length_difference
 - exact_name_match

Loading training data...
Training rows: 66,372

Training label distribution:
label
0    49698
1    16674
Name: count, dtype: int64

Loading validation data...
Validation rows: 16,592

Validation label distribution:
label
0    12525
1     4067
Name: count, dtype: int64

======================================================================
TRAINING RANDOM FOREST
======================================================================

Training model...

Training completed in 5.32 seconds

Generating validation predictions...

======================================================================
CELL 55 RESULTS
======================================================================
Accuracy  : 0.9221
Precision : 0.7833
Recall    : 0.9432
F1 Score  : 0.8559
ROC-AUC   : 0.9708

Confusion Matrix:
[[11464  1061]
 [  231  3836]]

Classification Report:
              precision    recall  f1-score   support

   Non-Match       0.98      0.92      0.95     12525
       Match       0.78      0.94      0.86      4067

    accuracy                           0.92     16592
   macro avg       0.88      0.93      0.90     16592
weighted avg       0.93      0.92      0.92     16592


Feature Importance:
          feature  importance
 token_sort_ratio    0.388605
       name_ratio    0.327776
  token_set_ratio    0.225129
length_difference    0.058307
 exact_name_match    0.000183

Saving model...

MODEL SAVED ✅
Model file: /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/entity_matching_model_10k.pkl
Model size: 10.67 MB

Memory cleanup completed.
======================================================================
CELL 55 COMPLETE
======================================================================

In [ ]:
# ======================================================================
# CELL 56R - ROBUST RAM-SAFE ML PREDICTION
# ======================================================================

import os
import gc
import time
import joblib
import pandas as pd
import numpy as np

print("=" * 70)
print("CELL 56R - ROBUST RAM-SAFE ML PREDICTION")
print("=" * 70)

BASE = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource"

FEATURE_FILE = (
    f"{BASE}/blocking/candidates/ml_features_10k.tsv"
)

MODEL_FILE = (
    f"{BASE}/blocking/candidates/entity_matching_model_10k.pkl"
)

OUTPUT_FILE = (
    f"{BASE}/blocking/candidates/ml_predictions_10k.tsv"
)

CHUNK_SIZE = 100_000
THRESHOLD = 0.50

# ----------------------------------------------------------------------
# CHECK FILES
# ----------------------------------------------------------------------

print("\nChecking required files...")

for path in [FEATURE_FILE, MODEL_FILE]:

    if not os.path.exists(path):
        raise FileNotFoundError(
            f"\nRequired file not found:\n{path}"
        )

    size_mb = os.path.getsize(path) / (1024 ** 2)

    print(
        f"FOUND ✅ {path} | "
        f"{size_mb:.2f} MB"
    )

# ----------------------------------------------------------------------
# LOAD MODEL
# ----------------------------------------------------------------------

print("\nLoading trained model...")

package = joblib.load(MODEL_FILE)

model = package["model"]
FEATURES = package["features"]

print("Model loaded ✅")
print("ML features:", FEATURES)
print("Threshold:", THRESHOLD)

# ----------------------------------------------------------------------
# CHECK FEATURE FILE COLUMNS
# ----------------------------------------------------------------------

print("\nChecking feature columns...")

sample = pd.read_csv(
    FEATURE_FILE,
    sep="\t",
    nrows=5
)

print("Available columns:")
print(list(sample.columns))

missing_features = [
    col for col in FEATURES
    if col not in sample.columns
]

if missing_features:

    raise ValueError(
        "\nRequired ML feature columns missing:\n"
        + str(missing_features)
        + "\nAvailable columns:\n"
        + str(list(sample.columns))
    )

print("All ML feature columns found ✅")

# ----------------------------------------------------------------------
# REMOVE OLD OUTPUT
# ----------------------------------------------------------------------

if os.path.exists(OUTPUT_FILE):

    os.remove(OUTPUT_FILE)

    print(
        "\nOld prediction file removed."
    )

# ----------------------------------------------------------------------
# DETERMINE ID / META COLUMNS
# ----------------------------------------------------------------------

preferred_columns = [
    "source1_id",
    "target_id",
    "target_source",
    "blocking_type",
    "blocking_key",
    "label"
]

available_meta = [
    col
    for col in preferred_columns
    if col in sample.columns
]

print(
    "\nColumns that will be preserved:"
)

print(available_meta)

# ----------------------------------------------------------------------
# PROCESS FILE
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PREDICTING ALL CANDIDATES")
print("=" * 70)

start_time = time.time()

total_rows = 0
predicted_matches = 0
first_chunk = True

for chunk_no, chunk in enumerate(
    pd.read_csv(
        FEATURE_FILE,
        sep="\t",
        chunksize=CHUNK_SIZE,
        low_memory=True
    ),
    start=1
):

    # --------------------------------------------------------------
    # CLEAN ML FEATURES
    # --------------------------------------------------------------

    for col in FEATURES:

        chunk[col] = pd.to_numeric(
            chunk[col],
            errors="coerce"
        )

    chunk[FEATURES] = (
        chunk[FEATURES]
        .replace(
            [np.inf, -np.inf],
            np.nan
        )
        .fillna(0)
    )

    # --------------------------------------------------------------
    # MODEL INPUT
    # --------------------------------------------------------------

    X = chunk[
        FEATURES
    ].astype(
        np.float32
    )

    # --------------------------------------------------------------
    # PREDICTION
    # --------------------------------------------------------------

    probabilities = model.predict_proba(
        X
    )[:, 1]

    predictions = (
        probabilities >= THRESHOLD
    ).astype(
        np.int8
    )

    # --------------------------------------------------------------
    # ADD RESULTS
    # --------------------------------------------------------------

    chunk["match_probability"] = (
        probabilities.astype(
            np.float32
        )
    )

    chunk["prediction"] = predictions

    # --------------------------------------------------------------
    # DYNAMIC OUTPUT COLUMNS
    # --------------------------------------------------------------

    output_columns = [
        col
        for col in available_meta
        if col in chunk.columns
    ]

    output_columns += [
        "match_probability",
        "prediction"
    ]

    output_chunk = chunk[
        output_columns
    ]

    # --------------------------------------------------------------
    # SAVE
    # --------------------------------------------------------------

    output_chunk.to_csv(
        OUTPUT_FILE,
        sep="\t",
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    first_chunk = False

    # --------------------------------------------------------------
    # COUNTERS
    # --------------------------------------------------------------

    rows = len(chunk)

    total_rows += rows

    predicted_matches += int(
        predictions.sum()
    )

    if chunk_no % 5 == 0:

        elapsed = (
            time.time() - start_time
        ) / 60

        print(
            f"Chunk {chunk_no:02d} | "
            f"Rows: {total_rows:,} | "
            f"Predicted matches: "
            f"{predicted_matches:,} | "
            f"Time: {elapsed:.2f} min"
        )

    # --------------------------------------------------------------
    # MEMORY CLEANUP
    # --------------------------------------------------------------

    del X
    del probabilities
    del predictions
    del output_chunk
    del chunk

    gc.collect()

# ----------------------------------------------------------------------
# FINAL RESULT
# ----------------------------------------------------------------------

elapsed_total = (
    time.time() - start_time
) / 60

output_size = (
    os.path.getsize(OUTPUT_FILE)
    / (1024 ** 2)
)

print("\n" + "=" * 70)
print("CELL 56R RESULTS")
print("=" * 70)

print(
    "Candidate rows processed :",
    f"{total_rows:,}"
)

print(
    "Predicted matches        :",
    f"{predicted_matches:,}"
)

print(
    "Prediction threshold     :",
    THRESHOLD
)

print(
    "Output file:"
)

print(
    OUTPUT_FILE
)

print(
    f"Output size              : "
    f"{output_size:.2f} MB"
)

print(
    f"Time taken               : "
    f"{elapsed_total:.2f} minutes"
)

print(
    "\nFILE SAVED: ✅ YES"
)

print("=" * 70)
print("CELL 56R COMPLETE")
print("=" * 70)

# ----------------------------------------------------------------------
# CLEANUP
# ----------------------------------------------------------------------

del model
del package
del sample

gc.collect()

print("\nMemory cleanup completed.")

======================================================================
CELL 56R - ROBUST RAM-SAFE ML PREDICTION
======================================================================

Checking required files...
FOUND ✅ /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ml_features_10k.tsv | 321.50 MB
FOUND ✅ /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/entity_matching_model_10k.pkl | 10.67 MB

Loading trained model...
Model loaded ✅
ML features: ['name_ratio', 'token_sort_ratio', 'token_set_ratio', 'length_difference', 'exact_name_match']
Threshold: 0.5

Checking feature columns...
Available columns:
['source1_id', 'target_id', 'target_source', 'blocking_type', 'name_ratio', 'token_sort_ratio', 'token_set_ratio', 'length_difference', 'exact_name_match', 'label']
All ML feature columns found ✅

Columns that will be preserved:
['source1_id', 'target_id', 'target_source', 'blocking_type', 'label']

======================================================================
PREDICTING ALL CANDIDATES
======================================================================
Chunk 05 | Rows: 500,000 | Predicted matches: 45,641 | Time: 0.14 min
Chunk 10 | Rows: 1,000,000 | Predicted matches: 89,308 | Time: 0.26 min
Chunk 15 | Rows: 1,500,000 | Predicted matches: 132,838 | Time: 0.33 min
Chunk 20 | Rows: 2,000,000 | Predicted matches: 179,112 | Time: 0.43 min
Chunk 25 | Rows: 2,500,000 | Predicted matches: 223,201 | Time: 0.52 min
Chunk 30 | Rows: 3,000,000 | Predicted matches: 267,309 | Time: 0.62 min
Chunk 35 | Rows: 3,500,000 | Predicted matches: 313,978 | Time: 0.70 min

======================================================================
CELL 56R RESULTS
======================================================================
Candidate rows processed : 3,784,393
Predicted matches        : 339,677
Prediction threshold     : 0.5
Output file:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ml_predictions_10k.tsv
Output size              : 187.36 MB
Time taken               : 0.75 minutes

FILE SAVED: ✅ YES
======================================================================
CELL 56R COMPLETE
======================================================================

Memory cleanup completed.

In [ ]:
# ======================================================================
# CELL 57 - FINAL MATCH SELECTION + EVALUATION
# ======================================================================

import os
import gc
import time
import pandas as pd
import numpy as np
from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    accuracy_score,
    confusion_matrix,
    classification_report
)

print("=" * 70)
print("CELL 57 - FINAL MATCH SELECTION + EVALUATION")
print("=" * 70)

BASE = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource"

PREDICTION_FILE = (
    f"{BASE}/blocking/candidates/ml_predictions_10k.tsv"
)

GROUND_TRUTH_FILE = (
    f"{BASE}/blocking/candidates/ground_truth_aligned_10k.tsv"
)

FINAL_FILE = (
    f"{BASE}/blocking/candidates/final_matches_10k.tsv"
)

# High-confidence threshold
HIGH_CONFIDENCE = 0.80

CHUNK_SIZE = 100_000

# ----------------------------------------------------------------------
# CHECK FILES
# ----------------------------------------------------------------------

print("\nChecking required files...")

for path in [
    PREDICTION_FILE,
    GROUND_TRUTH_FILE
]:

    if not os.path.exists(path):
        raise FileNotFoundError(
            f"\nRequired file not found:\n{path}"
        )

    size_mb = (
        os.path.getsize(path)
        / (1024 ** 2)
    )

    print(
        f"FOUND ✅ {path} | "
        f"{size_mb:.2f} MB"
    )

# ----------------------------------------------------------------------
# LOAD GROUND TRUTH
# ----------------------------------------------------------------------

print("\nLoading ground truth...")

gt = pd.read_csv(
    GROUND_TRUTH_FILE,
    sep="\t",
    dtype=str
)

print(
    "Ground-truth columns:",
    list(gt.columns)
)

# ----------------------------------------------------------------------
# BUILD GROUND-TRUTH PAIRS
# ----------------------------------------------------------------------

ground_truth_pairs = set()

for _, row in gt.iterrows():

    source_id = str(
        row["source1_entity_id"]
    ).strip()

    matched_ids = str(
        row["matched_entity_ids"]
    ).strip()

    if not matched_ids:
        continue

    # Handle common separators
    matched_ids = (
        matched_ids
        .replace("|", ",")
        .replace(";", ",")
    )

    for target_id in matched_ids.split(","):

        target_id = target_id.strip()

        if target_id:
            ground_truth_pairs.add(
                (
                    source_id,
                    target_id
                )
            )

print(
    "Ground-truth pairs:",
    f"{len(ground_truth_pairs):,}"
)

del gt
gc.collect()

# ----------------------------------------------------------------------
# REMOVE OLD FINAL FILE
# ----------------------------------------------------------------------

if os.path.exists(FINAL_FILE):

    os.remove(FINAL_FILE)

# ----------------------------------------------------------------------
# PASS 1 - COLLECT HIGH CONFIDENCE PREDICTIONS
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PASS 1 - HIGH CONFIDENCE MATCHES")
print("=" * 70)

start_time = time.time()

high_confidence_count = 0
total_prediction_rows = 0

# Store only high-confidence candidates
candidate_parts = []

for chunk_no, chunk in enumerate(
    pd.read_csv(
        PREDICTION_FILE,
        sep="\t",
        chunksize=CHUNK_SIZE,
        low_memory=True
    ),
    start=1
):

    total_prediction_rows += len(chunk)

    chunk["match_probability"] = pd.to_numeric(
        chunk["match_probability"],
        errors="coerce"
    )

    # Keep only high-confidence predictions
    selected = chunk[
        chunk["match_probability"] >= HIGH_CONFIDENCE
    ].copy()

    if len(selected) > 0:

        candidate_parts.append(
            selected[
                [
                    "source1_id",
                    "target_id",
                    "target_source",
                    "match_probability",
                    "prediction"
                ]
            ]
        )

        high_confidence_count += len(
            selected
        )

    if chunk_no % 5 == 0:

        elapsed = (
            time.time() - start_time
        ) / 60

        print(
            f"Chunk {chunk_no:02d} | "
            f"Processed: {total_prediction_rows:,} | "
            f"High-confidence: "
            f"{high_confidence_count:,} | "
            f"Time: {elapsed:.2f} min"
        )

    del selected
    del chunk

    gc.collect()

print(
    "\nHigh-confidence candidates:",
    f"{high_confidence_count:,}"
)

# ----------------------------------------------------------------------
# COMBINE HIGH-CONFIDENCE CANDIDATES
# ----------------------------------------------------------------------

if len(candidate_parts) == 0:

    raise ValueError(
        "No high-confidence matches found."
    )

matches = pd.concat(
    candidate_parts,
    ignore_index=True
)

del candidate_parts
gc.collect()

print(
    "Candidates loaded:",
    f"{len(matches):,}"
)

# ----------------------------------------------------------------------
# BEST MATCH PER SOURCE-1
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("SELECTING BEST TARGET PER SOURCE-1")
print("=" * 70)

matches = matches.sort_values(
    [
        "source1_id",
        "match_probability"
    ],
    ascending=[
        True,
        False
    ]
)

# Keep highest probability target
best_matches = (
    matches
    .drop_duplicates(
        subset=["source1_id"],
        keep="first"
    )
    .copy()
)

print(
    "Unique Source-1 matched:",
    f"{len(best_matches):,}"
)

# ----------------------------------------------------------------------
# GROUND TRUTH EVALUATION
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("EVALUATING FINAL MATCHES")
print("=" * 70)

y_true = []
y_pred = []

for _, row in best_matches.iterrows():

    pair = (
        str(row["source1_id"]),
        str(row["target_id"])
    )

    y_true.append(
        1 if pair in ground_truth_pairs else 0
    )

    y_pred.append(1)

# Precision among selected matches
if len(y_pred) > 0:

    final_precision = precision_score(
        y_true,
        y_pred,
        zero_division=0
    )

else:

    final_precision = 0.0

true_positive = sum(y_true)

# Ground truth recall
ground_truth_total = len(
    ground_truth_pairs
)

final_recall = (
    true_positive /
    ground_truth_total
    if ground_truth_total > 0
    else 0
)

final_f1 = (
    2 * final_precision * final_recall /
    (final_precision + final_recall)
    if (
        final_precision + final_recall
    ) > 0
    else 0
)

# ----------------------------------------------------------------------
# SAVE FINAL MATCHES
# ----------------------------------------------------------------------

best_matches["ground_truth_match"] = [
    1 if (
        str(row["source1_id"]),
        str(row["target_id"])
    ) in ground_truth_pairs
    else 0
    for _, row in best_matches.iterrows()
]

best_matches.to_csv(
    FINAL_FILE,
    sep="\t",
    index=False
)

# ----------------------------------------------------------------------
# RESULTS
# ----------------------------------------------------------------------

output_size = (
    os.path.getsize(FINAL_FILE)
    / (1024 ** 2)
)

elapsed_total = (
    time.time() - start_time
) / 60

print("\n" + "=" * 70)
print("CELL 57 RESULTS")
print("=" * 70)

print(
    "Total prediction rows :",
    f"{total_prediction_rows:,}"
)

print(
    "High-confidence rows  :",
    f"{high_confidence_count:,}"
)

print(
    "Final unique matches  :",
    f"{len(best_matches):,}"
)

print(
    "True positive matches :",
    f"{true_positive:,}"
)

print(
    f"Precision             : "
    f"{final_precision:.4f}"
)

print(
    f"Recall                : "
    f"{final_recall:.4f}"
)

print(
    f"F1 Score              : "
    f"{final_f1:.4f}"
)

print(
    "\nFinal output:"
)

print(
    FINAL_FILE
)

print(
    f"Output size           : "
    f"{output_size:.2f} MB"
)

print(
    f"Time taken            : "
    f"{elapsed_total:.2f} minutes"
)

print(
    "\nFILE SAVED: ✅ YES"
)

print("=" * 70)
print("CELL 57 COMPLETE")
print("=" * 70)

# ----------------------------------------------------------------------
# MEMORY CLEANUP
# ----------------------------------------------------------------------

del matches
del best_matches
del y_true
del y_pred
del ground_truth_pairs

gc.collect()

print(
    "\nMemory cleanup completed."
)

======================================================================
CELL 57 - FINAL MATCH SELECTION + EVALUATION
======================================================================

Checking required files...
FOUND ✅ /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ml_predictions_10k.tsv | 187.36 MB
FOUND ✅ /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ground_truth_aligned_10k.tsv | 0.55 MB

Loading ground truth...
Ground-truth columns: ['source1_entity_id', 'matched_entity_ids']
Ground-truth pairs: 35,312

======================================================================
PASS 1 - HIGH CONFIDENCE MATCHES
======================================================================
Chunk 05 | Processed: 500,000 | High-confidence: 30,004 | Time: 0.03 min
Chunk 10 | Processed: 1,000,000 | High-confidence: 59,045 | Time: 0.06 min
Chunk 15 | Processed: 1,500,000 | High-confidence: 87,997 | Time: 0.09 min
Chunk 20 | Processed: 2,000,000 | High-confidence: 118,098 | Time: 0.12 min
Chunk 25 | Processed: 2,500,000 | High-confidence: 145,513 | Time: 0.15 min
Chunk 30 | Processed: 3,000,000 | High-confidence: 174,160 | Time: 0.19 min
Chunk 35 | Processed: 3,500,000 | High-confidence: 204,919 | Time: 0.23 min

High-confidence candidates: 221,327
Candidates loaded: 221,327

======================================================================
SELECTING BEST TARGET PER SOURCE-1
======================================================================
Unique Source-1 matched: 9,420

======================================================================
EVALUATING FINAL MATCHES
======================================================================

======================================================================
CELL 57 RESULTS
======================================================================
Total prediction rows : 3,784,393
High-confidence rows  : 221,327
Final unique matches  : 9,420
True positive matches : 5,150
Precision             : 0.5467
Recall                : 0.1458
F1 Score              : 0.2303

Final output:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/final_matches_10k.tsv
Output size           : 0.43 MB
Time taken            : 0.28 minutes

FILE SAVED: ✅ YES
======================================================================
CELL 57 COMPLETE
======================================================================

Memory cleanup completed.

In [ ]:
# ======================================================================
# CELL 58 - THRESHOLD + TOP-K MATCHING COMPARISON
# ======================================================================

import os
import gc
import time
import heapq
import pandas as pd

print("=" * 70)
print("CELL 58 - THRESHOLD + TOP-K MATCHING COMPARISON")
print("=" * 70)

BASE = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource"

PREDICTION_FILE = (
    f"{BASE}/blocking/candidates/ml_predictions_10k.tsv"
)

GROUND_TRUTH_FILE = (
    f"{BASE}/blocking/candidates/ground_truth_aligned_10k.tsv"
)

RESULT_FILE = (
    f"{BASE}/blocking/candidates/cell58_threshold_topk_results.tsv"
)

CHUNK_SIZE = 100_000

# We keep only top 5 predictions for each Source-1
TOP_K = 5

THRESHOLDS = [
    0.30,
    0.40,
    0.50,
    0.60,
    0.70,
    0.80,
]

# ----------------------------------------------------------------------
# CHECK FILES
# ----------------------------------------------------------------------

print("\nChecking required files...")

for path in [
    PREDICTION_FILE,
    GROUND_TRUTH_FILE
]:

    if not os.path.exists(path):
        raise FileNotFoundError(path)

    print(
        "FOUND ✅",
        path,
        "|",
        f"{os.path.getsize(path)/(1024**2):.2f} MB"
    )

# ----------------------------------------------------------------------
# LOAD GROUND TRUTH
# ----------------------------------------------------------------------

print("\nLoading ground truth...")

gt = pd.read_csv(
    GROUND_TRUTH_FILE,
    sep="\t",
    dtype=str
)

ground_truth_pairs = set()

for _, row in gt.iterrows():

    source_id = str(
        row["source1_entity_id"]
    ).strip()

    matched_ids = str(
        row["matched_entity_ids"]
    ).strip()

    if not matched_ids:
        continue

    matched_ids = (
        matched_ids
        .replace("|", ",")
        .replace(";", ",")
    )

    for target_id in matched_ids.split(","):

        target_id = target_id.strip()

        if target_id:
            ground_truth_pairs.add(
                (source_id, target_id)
            )

print(
    "Ground-truth pairs:",
    f"{len(ground_truth_pairs):,}"
)

del gt
gc.collect()

# ----------------------------------------------------------------------
# STREAM PREDICTIONS
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("SCANNING PREDICTIONS")
print("=" * 70)

start_time = time.time()

# source1_id -> list of
# (probability, target_id, target_source)
top_matches = {}

total_rows = 0

for chunk_no, chunk in enumerate(
    pd.read_csv(
        PREDICTION_FILE,
        sep="\t",
        chunksize=CHUNK_SIZE,
        low_memory=True
    ),
    start=1
):

    total_rows += len(chunk)

    # Make sure probability is numeric
    chunk["match_probability"] = pd.to_numeric(
        chunk["match_probability"],
        errors="coerce"
    )

    chunk = chunk.dropna(
        subset=["match_probability"]
    )

    for row in chunk.itertuples(
        index=False
    ):

        source_id = str(
            row.source1_id
        )

        target_id = str(
            row.target_id
        )

        target_source = str(
            row.target_source
        )

        probability = float(
            row.match_probability
        )

        if source_id not in top_matches:

            top_matches[source_id] = []

        heap = top_matches[source_id]

        item = (
            probability,
            target_id,
            target_source
        )

        if len(heap) < TOP_K:

            heapq.heappush(
                heap,
                item
            )

        elif probability > heap[0][0]:

            heapq.heapreplace(
                heap,
                item
            )

    if chunk_no % 5 == 0:

        elapsed = (
            time.time() - start_time
        ) / 60

        print(
            f"Chunk {chunk_no:02d} | "
            f"Processed: {total_rows:,} | "
            f"Source-1 tracked: {len(top_matches):,} | "
            f"Time: {elapsed:.2f} min"
        )

    del chunk
    gc.collect()

print(
    "\nPrediction scan complete."
)

print(
    "Total prediction rows:",
    f"{total_rows:,}"
)

print(
    "Unique Source-1:",
    f"{len(top_matches):,}"
)

# ----------------------------------------------------------------------
# CONVERT HEAPS TO SORTED LISTS
# ----------------------------------------------------------------------

for source_id in top_matches:

    top_matches[source_id].sort(
        reverse=True
    )

# ----------------------------------------------------------------------
# EVALUATE THRESHOLD + TOP-K
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("THRESHOLD + TOP-K RESULTS")
print("=" * 70)

results = []

for threshold in THRESHOLDS:

    for k in [1, 2, 3, 5]:

        selected_pairs = set()

        for source_id, candidates in top_matches.items():

            selected_count = 0

            for probability, target_id, target_source in candidates:

                if probability < threshold:
                    continue

                selected_pairs.add(
                    (
                        source_id,
                        target_id
                    )
                )

                selected_count += 1

                if selected_count >= k:
                    break

        true_positive = len(
            selected_pairs.intersection(
                ground_truth_pairs
            )
        )

        predicted_count = len(
            selected_pairs
        )

        precision = (
            true_positive / predicted_count
            if predicted_count > 0
            else 0
        )

        recall = (
            true_positive / len(
                ground_truth_pairs
            )
            if len(ground_truth_pairs) > 0
            else 0
        )

        f1 = (
            2 * precision * recall /
            (precision + recall)
            if precision + recall > 0
            else 0
        )

        results.append({

            "threshold": threshold,

            "top_k": k,

            "predicted_matches":
                predicted_count,

            "true_positive":
                true_positive,

            "precision":
                precision,

            "recall":
                recall,

            "f1":
                f1
        })

        print(
            f"Threshold={threshold:.2f} | "
            f"Top-K={k} | "
            f"Matches={predicted_count:,} | "
            f"TP={true_positive:,} | "
            f"Precision={precision:.4f} | "
            f"Recall={recall:.4f} | "
            f"F1={f1:.4f}"
        )

# ----------------------------------------------------------------------
# SAVE RESULTS
# ----------------------------------------------------------------------

results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    "f1",
    ascending=False
)

results_df.to_csv(
    RESULT_FILE,
    sep="\t",
    index=False
)

# ----------------------------------------------------------------------
# BEST CONFIGURATION
# ----------------------------------------------------------------------

best = results_df.iloc[0]

print("\n" + "=" * 70)
print("CELL 58 RESULTS")
print("=" * 70)

print(
    f"Best threshold : "
    f"{best['threshold']:.2f}"
)

print(
    f"Best Top-K     : "
    f"{int(best['top_k'])}"
)

print(
    f"Best Precision  : "
    f"{best['precision']:.4f}"
)

print(
    f"Best Recall     : "
    f"{best['recall']:.4f}"
)

print(
    f"Best F1         : "
    f"{best['f1']:.4f}"
)

print(
    f"Best matches    : "
    f"{int(best['predicted_matches']):,}"
)

print(
    "\nTop configurations:"
)

print(
    results_df.head(5).to_string(
        index=False
    )
)

print(
    "\nOutput file:"
)

print(
    RESULT_FILE
)

print(
    f"Output size: "
    f"{os.path.getsize(RESULT_FILE)/(1024**2):.2f} MB"
)

print("=" * 70)
print("CELL 58 COMPLETE")
print("=" * 70)

# ----------------------------------------------------------------------
# CLEANUP
# ----------------------------------------------------------------------

del top_matches
del ground_truth_pairs
del results
del results_df

gc.collect()

print(
    "\nMemory cleanup completed."
)

======================================================================
CELL 58 - THRESHOLD + TOP-K MATCHING COMPARISON
======================================================================

Checking required files...
FOUND ✅ /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ml_predictions_10k.tsv | 187.36 MB
FOUND ✅ /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ground_truth_aligned_10k.tsv | 0.55 MB

Loading ground truth...
Ground-truth pairs: 35,312

======================================================================
SCANNING PREDICTIONS
======================================================================
Chunk 05 | Processed: 500,000 | Source-1 tracked: 1,299 | Time: 0.08 min
Chunk 10 | Processed: 1,000,000 | Source-1 tracked: 2,607 | Time: 0.17 min
Chunk 15 | Processed: 1,500,000 | Source-1 tracked: 3,895 | Time: 0.28 min
Chunk 20 | Processed: 2,000,000 | Source-1 tracked: 5,169 | Time: 0.33 min
Chunk 25 | Processed: 2,500,000 | Source-1 tracked: 6,460 | Time: 0.37 min
Chunk 30 | Processed: 3,000,000 | Source-1 tracked: 7,732 | Time: 0.40 min
Chunk 35 | Processed: 3,500,000 | Source-1 tracked: 8,997 | Time: 0.45 min

Prediction scan complete.
Total prediction rows: 3,784,393
Unique Source-1: 9,750

======================================================================
THRESHOLD + TOP-K RESULTS
======================================================================
Threshold=0.30 | Top-K=1 | Matches=9,712 | TP=5,204 | Precision=0.5358 | Recall=0.1474 | F1=0.2312
Threshold=0.30 | Top-K=2 | Matches=19,257 | TP=9,312 | Precision=0.4836 | Recall=0.2637 | F1=0.3413
Threshold=0.30 | Top-K=3 | Matches=28,410 | TP=12,248 | Precision=0.4311 | Recall=0.3469 | F1=0.3844
Threshold=0.30 | Top-K=5 | Matches=44,911 | TP=15,321 | Precision=0.3411 | Recall=0.4339 | F1=0.3820
Threshold=0.40 | Top-K=1 | Matches=9,689 | TP=5,204 | Precision=0.5371 | Recall=0.1474 | F1=0.2313
Threshold=0.40 | Top-K=2 | Matches=19,138 | TP=9,306 | Precision=0.4863 | Recall=0.2635 | F1=0.3418
Threshold=0.40 | Top-K=3 | Matches=28,100 | TP=12,232 | Precision=0.4353 | Recall=0.3464 | F1=0.3858
Threshold=0.40 | Top-K=5 | Matches=43,787 | TP=15,272 | Precision=0.3488 | Recall=0.4325 | F1=0.3861
Threshold=0.50 | Top-K=1 | Matches=9,652 | TP=5,202 | Precision=0.5390 | Recall=0.1473 | F1=0.2314
Threshold=0.50 | Top-K=2 | Matches=18,983 | TP=9,296 | Precision=0.4897 | Recall=0.2633 | F1=0.3424
Threshold=0.50 | Top-K=3 | Matches=27,676 | TP=12,195 | Precision=0.4406 | Recall=0.3454 | F1=0.3872
Threshold=0.50 | Top-K=5 | Matches=42,530 | TP=15,165 | Precision=0.3566 | Recall=0.4295 | F1=0.3896
Threshold=0.60 | Top-K=1 | Matches=9,612 | TP=5,198 | Precision=0.5408 | Recall=0.1472 | F1=0.2314
Threshold=0.60 | Top-K=2 | Matches=18,807 | TP=9,267 | Precision=0.4927 | Recall=0.2624 | F1=0.3425
Threshold=0.60 | Top-K=3 | Matches=27,242 | TP=12,141 | Precision=0.4457 | Recall=0.3438 | F1=0.3882
Threshold=0.60 | Top-K=5 | Matches=41,355 | TP=15,034 | Precision=0.3635 | Recall=0.4257 | F1=0.3922
Threshold=0.70 | Top-K=1 | Matches=9,545 | TP=5,189 | Precision=0.5436 | Recall=0.1469 | F1=0.2314
Threshold=0.70 | Top-K=2 | Matches=18,556 | TP=9,228 | Precision=0.4973 | Recall=0.2613 | F1=0.3426
Threshold=0.70 | Top-K=3 | Matches=26,693 | TP=12,041 | Precision=0.4511 | Recall=0.3410 | F1=0.3884
Threshold=0.70 | Top-K=5 | Matches=39,913 | TP=14,824 | Precision=0.3714 | Recall=0.4198 | F1=0.3941
Threshold=0.80 | Top-K=1 | Matches=9,420 | TP=5,162 | Precision=0.5480 | Recall=0.1462 | F1=0.2308
Threshold=0.80 | Top-K=2 | Matches=18,056 | TP=9,113 | Precision=0.5047 | Recall=0.2581 | F1=0.3415
Threshold=0.80 | Top-K=3 | Matches=25,556 | TP=11,771 | Precision=0.4606 | Recall=0.3333 | F1=0.3868
Threshold=0.80 | Top-K=5 | Matches=37,204 | TP=14,313 | Precision=0.3847 | Recall=0.4053 | F1=0.3948

======================================================================
CELL 58 RESULTS
======================================================================
Best threshold : 0.80
Best Top-K     : 5
Best Precision  : 0.3847
Best Recall     : 0.4053
Best F1         : 0.3948
Best matches    : 37,204

Top configurations:
 threshold  top_k  predicted_matches  true_positive  precision   recall       f1
       0.8      5              37204          14313   0.384717 0.405330 0.394754
       0.7      5              39913          14824   0.371408 0.419801 0.394124
       0.6      5              41355          15034   0.363535 0.425748 0.392190
       0.5      5              42530          15165   0.356572 0.429457 0.389635
       0.7      3              26693          12041   0.451092 0.340989 0.388388

Output file:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/cell58_threshold_topk_results.tsv
Output size: 0.00 MB
======================================================================
CELL 58 COMPLETE
======================================================================

Memory cleanup completed.

In [ ]:
# ======================================================================
# CELL 59 - FINAL OPTIMIZED MATCHING
# Threshold = 0.80 | Top-K = 5
# ======================================================================

import os
import gc
import heapq
import time
import pandas as pd

print("=" * 70)
print("CELL 59 - FINAL OPTIMIZED MATCHING")
print("=" * 70)

BASE = "/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource"

PREDICTION_FILE = (
    f"{BASE}/blocking/candidates/ml_predictions_10k.tsv"
)

GROUND_TRUTH_FILE = (
    f"{BASE}/blocking/candidates/ground_truth_aligned_10k.tsv"
)

FINAL_FILE = (
    f"{BASE}/blocking/candidates/final_matches_optimized_10k.tsv"
)

THRESHOLD = 0.80
TOP_K = 5
CHUNK_SIZE = 100_000

# ----------------------------------------------------------------------
# CHECK FILES
# ----------------------------------------------------------------------

print("\nChecking required files...")

for path in [
    PREDICTION_FILE,
    GROUND_TRUTH_FILE
]:

    if not os.path.exists(path):
        raise FileNotFoundError(
            f"\nFile not found:\n{path}"
        )

    print(
        "FOUND ✅",
        path,
        "|",
        f"{os.path.getsize(path)/(1024**2):.2f} MB"
    )

# ----------------------------------------------------------------------
# LOAD GROUND TRUTH
# ----------------------------------------------------------------------

print("\nLoading ground truth...")

gt = pd.read_csv(
    GROUND_TRUTH_FILE,
    sep="\t",
    dtype=str
)

ground_truth_pairs = set()

for _, row in gt.iterrows():

    source_id = str(
        row["source1_entity_id"]
    ).strip()

    matched_ids = str(
        row["matched_entity_ids"]
    ).strip()

    if not matched_ids or matched_ids.lower() == "nan":
        continue

    matched_ids = (
        matched_ids
        .replace("|", ",")
        .replace(";", ",")
    )

    for target_id in matched_ids.split(","):

        target_id = target_id.strip()

        if target_id:
            ground_truth_pairs.add(
                (source_id, target_id)
            )

print(
    "Ground-truth pairs:",
    f"{len(ground_truth_pairs):,}"
)

del gt
gc.collect()

# ----------------------------------------------------------------------
# FIND TOP-K PER SOURCE-1
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("SCANNING PREDICTIONS")
print("=" * 70)

start_time = time.time()

top_matches = {}

total_rows = 0
high_confidence_rows = 0

for chunk_no, chunk in enumerate(
    pd.read_csv(
        PREDICTION_FILE,
        sep="\t",
        chunksize=CHUNK_SIZE,
        low_memory=True
    ),
    start=1
):

    total_rows += len(chunk)

    # Safe numeric conversion
    chunk["match_probability"] = pd.to_numeric(
        chunk["match_probability"],
        errors="coerce"
    )

    # Keep only threshold-qualified predictions
    chunk = chunk[
        chunk["match_probability"] >= THRESHOLD
    ]

    high_confidence_rows += len(chunk)

    for row in chunk.itertuples(index=False):

        source_id = str(row.source1_id)
        target_id = str(row.target_id)
        target_source = str(row.target_source)

        probability = float(
            row.match_probability
        )

        if source_id not in top_matches:

            top_matches[source_id] = []

        heap = top_matches[source_id]

        item = (
            probability,
            target_id,
            target_source
        )

        if len(heap) < TOP_K:

            heapq.heappush(
                heap,
                item
            )

        elif probability > heap[0][0]:

            heapq.heapreplace(
                heap,
                item
            )

    if chunk_no % 5 == 0:

        elapsed = (
            time.time() - start_time
        ) / 60

        print(
            f"Chunk {chunk_no:02d} | "
            f"Processed: {total_rows:,} | "
            f"High-confidence: {high_confidence_rows:,} | "
            f"Source-1: {len(top_matches):,} | "
            f"Time: {elapsed:.2f} min"
        )

    del chunk
    gc.collect()

# ----------------------------------------------------------------------
# CREATE FINAL MATCHES
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("CREATING FINAL MATCHES")
print("=" * 70)

final_rows = []

for source_id, candidates in top_matches.items():

    candidates.sort(
        reverse=True
    )

    for rank, (
        probability,
        target_id,
        target_source
    ) in enumerate(
        candidates,
        start=1
    ):

        final_rows.append({

            "source1_id":
                source_id,

            "target_id":
                target_id,

            "target_source":
                target_source,

            "match_probability":
                probability,

            "rank":
                rank,

            "threshold":
                THRESHOLD
        })

# ----------------------------------------------------------------------
# SAVE
# ----------------------------------------------------------------------

final_df = pd.DataFrame(
    final_rows
)

final_df.to_csv(
    FINAL_FILE,
    sep="\t",
    index=False
)

# ----------------------------------------------------------------------
# EVALUATION
# ----------------------------------------------------------------------

predicted_pairs = set(
    zip(
        final_df["source1_id"],
        final_df["target_id"]
    )
)

true_positive = len(
    predicted_pairs.intersection(
        ground_truth_pairs
    )
)

predicted_count = len(
    predicted_pairs
)

precision = (
    true_positive / predicted_count
    if predicted_count > 0
    else 0
)

recall = (
    true_positive / len(ground_truth_pairs)
    if ground_truth_pairs
    else 0
)

f1 = (
    2 * precision * recall /
    (precision + recall)
    if precision + recall > 0
    else 0
)

# ----------------------------------------------------------------------
# FINAL RESULTS
# ----------------------------------------------------------------------

elapsed = (
    time.time() - start_time
) / 60

print("\n" + "=" * 70)
print("CELL 59 RESULTS")
print("=" * 70)

print(
    f"Threshold              : {THRESHOLD}"
)

print(
    f"Top-K                  : {TOP_K}"
)

print(
    f"Prediction rows        : {total_rows:,}"
)

print(
    f"High-confidence rows   : {high_confidence_rows:,}"
)

print(
    f"Unique Source-1        : {len(top_matches):,}"
)

print(
    f"Final match rows       : {len(final_df):,}"
)

print(
    f"True positive matches  : {true_positive:,}"
)

print(
    f"Precision              : {precision:.4f}"
)

print(
    f"Recall                 : {recall:.4f}"
)

print(
    f"F1 Score               : {f1:.4f}"
)

print(
    "\nFinal output:"
)

print(
    FINAL_FILE
)

print(
    f"Output size            : "
    f"{os.path.getsize(FINAL_FILE)/(1024**2):.2f} MB"
)

print(
    f"Time taken             : {elapsed:.2f} minutes"
)

print(
    "\nFILE SAVED: ✅ YES"
)

print("=" * 70)
print("CELL 59 COMPLETE")
print("=" * 70)

# ----------------------------------------------------------------------
# CLEANUP
# ----------------------------------------------------------------------

del top_matches
del final_rows
del final_df
del predicted_pairs
del ground_truth_pairs

gc.collect()

print("\nMemory cleanup completed.")

======================================================================
CELL 59 - FINAL OPTIMIZED MATCHING
======================================================================

Checking required files...
FOUND ✅ /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ml_predictions_10k.tsv | 187.36 MB
FOUND ✅ /content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/ground_truth_aligned_10k.tsv | 0.55 MB

Loading ground truth...
Ground-truth pairs: 34,752

======================================================================
SCANNING PREDICTIONS
======================================================================
Chunk 05 | Processed: 500,000 | High-confidence: 30,004 | Source-1: 1,259 | Time: 0.03 min
Chunk 10 | Processed: 1,000,000 | High-confidence: 59,045 | Source-1: 2,506 | Time: 0.06 min
Chunk 15 | Processed: 1,500,000 | High-confidence: 87,997 | Source-1: 3,750 | Time: 0.11 min
Chunk 20 | Processed: 2,000,000 | High-confidence: 118,098 | Source-1: 4,983 | Time: 0.14 min
Chunk 25 | Processed: 2,500,000 | High-confidence: 145,513 | Source-1: 6,237 | Time: 0.17 min
Chunk 30 | Processed: 3,000,000 | High-confidence: 174,160 | Source-1: 7,465 | Time: 0.21 min
Chunk 35 | Processed: 3,500,000 | High-confidence: 204,919 | Source-1: 8,688 | Time: 0.23 min

======================================================================
CREATING FINAL MATCHES
======================================================================

======================================================================
CELL 59 RESULTS
======================================================================
Threshold              : 0.8
Top-K                  : 5
Prediction rows        : 3,784,393
High-confidence rows   : 221,327
Unique Source-1        : 9,420
Final match rows       : 37,204
True positive matches  : 14,313
Precision              : 0.3847
Recall                 : 0.4119
F1 Score               : 0.3978

Final output:
/content/drive/MyDrive/6ab10eb3b23ba_student_resource/student_resource/blocking/candidates/final_matches_optimized_10k.tsv
Output size            : 1.79 MB
Time taken             : 0.25 minutes

FILE SAVED: ✅ YES
======================================================================
CELL 59 COMPLETE
======================================================================

Memory cleanup completed.